#ifndef GUARD_ZOKTAI_CONST_ARMOR_H
#define GUARD_ZOKTAI_CONST_ARMOR_H

enum ArmorID {
  ARMOR_CLOTH_ARMOR = 0,
  ARMOR_LEATHER_ARMOR = 1,
  ARMOR_CHAIN_MAIL = 2,
  ARMOR_SILVER_CHAIN = 3,
  ARMOR_SCALE_MAIL = 4,
  ARMOR_SAMURAI_ARMOR = 5,
  ARMOR_BLADE_MAIL = 6,
  ARMOR_BRIGANDINE = 7,
  ARMOR_MAIL_OF_SOL = 8,
  ARMOR_MAIL_OF_DARKNESS = 9,
  ARMOR_MAIL_OF_LUNA = 10,
  ARMOR_FIRE_DRAGON_FANG = 11,
  ARMOR_WATER_DRAGON_TAIL = 12,
  ARMOR_WIND_DRAGON_WING = 13,
  ARMOR_EARTH_DRAGON_CLAW = 14,
  ARMOR_DRAGON_SCALE = 15,
  ARMOR_FAIRY_ROBE = 16,
  ARMOR_EARTHLY_ROBE = 17,
  ARMOR_RAIN_COAT = 18,
  ARMOR_GARB_OF_LIGHT = 19,
  ARMOR_GARB_OF_DARKNESS = 20,
  ARMOR_MAGIC_ROBE = 21,
  ARMOR_BLOOD_CAPE = 22,
  ARMOR_SKULL_SUIT = 23,
  ARMOR_TRAINING_GEAR = 24,
  ARMOR_THIEF_CLOTHES = 25,
  ARMOR_HUNTER_CLOTHES = 26,
  ARMOR_POISON_GUARD = 27,
  ARMOR_WEAPON_GUARD = 28,
  ARMOR_PARADE_ARMOR = 29,
  ARMOR_NINJA_GI = 30,
  ARMOR_SPIKE_MAIL = 31,
  ARMOR_BLACK_ARMOR = 32,
  ARMOR_MEGA_POWER = 33,
  ARMOR_GUTS_POWER = 34,
  ARMOR_PROTO_POWER = 35,
  ARMOR_TOAD_POWER = 36,
};

#define ARMOR_NONE (-1)

#define ARMOR_NUM (ARMOR_TOAD_POWER + 1)

#endif  // GUARD_ZOKTAI_CONST_ARMOR_H
