#ifndef GUARD_ZOKTAI_CONST_COFFIN_H
#define GUARD_ZOKTAI_CONST_COFFIN_H

enum CoffinID {
  COFFIN_OAK,
  COFFIN_BRONZE,
  COFFIN_IRON,
  COFFIN_SILVER,
  COFFIN_SOLAR,
  COFFIN_ELEFAN,
  COFFIN_VAMPIRE,
  COFFIN_IRON_MAIDEN,
};

#define COFFIN_NUM (COFFIN_IRON_MAIDEN + 1)

#define COFFIN_ITEM_ID(id) (id + 0x38)

#endif  // GUARD_ZOKTAI_CONST_COFFIN_H
