#ifndef GUARD_ZOKTAI_CONST_ITEM_H
#define GUARD_ZOKTAI_CONST_ITEM_H

enum ItemID {
  ITEM_EARTHLY_NUT = 0,  // 大地の実
  ITEM_SOLAR_NUT = 1,    // 太陽の実
  ITEM_SPEED_NUT = 2,
  ITEM_TIPTOE_NUT = 3,
  ITEM_POWER_NUT = 4,
  ITEM_CHOCOLATE_BANANA = 5,
  ITEM_BEARNUT = 6,
  ITEM_SEE_ALL_NUT = 7,
  ITEM_ROTTEN_NUT = 8,
  ITEM_RED_MUSHROOM = 9,
  ITEM_BLUE_MUSHROOM = 10,
  ITEM_BAD_MUSHROOM = 11,
  ITEM_DROP_OF_SUN = 12,
  ITEM_TOMATO_JUICE = 13,
  ITEM_ROTTEN_WATER = 14,
  ITEM_TASTY_MEAT = 15,
  ITEM_JERKY = 16,
  ITEM_ROTTEN_MEAT = 17,
  ITEM_CHOCOLATE = 18,
  ITEM_MELTED_CHOCOLATE = 19,
  ITEM_CHOCOLATE_COVERED = 20,  // チョコまみれ
  ITEM_DELUXE_CHOCOLATE = 21,
  ITEM_HEALER = 22,
  ITEM_MAGICAL_POTION = 23,
  ITEM_ANTIDOTE = 24,
  ITEM_ELIXIR = 25,
  ITEM_SUNBLOCK = 26,
  ITEM_MR_RAINNOT = 27,
  ITEM_TONNIAR_RM = 28,
  ITEM_SUNNY_CLOG = 29,
  ITEM_WARP_LEAF = 30,
  ITEM_THE_FOOL = 31,
  ITEM_THE_HIGH_PRIESTESS = 32,
  ITEM_THE_EMPRESS = 33,
  ITEM_THE_EMPEROR = 34,
  ITEM_THE_LOVER = 35,
  ITEM_THE_CHARIOT = 36,
  ITEM_STRENGTH = 37,
  ITEM_WOF = 38,  // 運命の輪のカード
  ITEM_JUSTICE = 39,
  ITEM_THE_HANGED_MAN = 40,
  ITEM_DEATH = 41,
  ITEM_TEMPERANCE = 42,
  ITEM_THE_DEVIL = 43,
  ITEM_THE_TOWER = 44,
  ITEM_THE_STAR = 45,
  ITEM_THE_MOON = 46,
  ITEM_THE_SUN = 47,
  ITEM_JUDGEMENT = 48,  // 審判のカード
  ITEM_DARK_CARD = 49,  // 暗黒カード
  ITEM_PET = 50,
  ITEM_SPADE_EMBLEM = 51,
  ITEM_HEART_EMBLEM = 52,
  ITEM_DIAMOND_EMBLEM = 53,
  ITEM_CLUB_EMBLEM = 54,
  ITEM_JOKER_EMBLEM = 55,

  ITEM_OAK_COFFIN = 56,  // coffin.h

  ITEM_WAREHOUSE_KEY = 64,
  ITEM_CIRCLE_KEY = 65,
  ITEM_TRIANGLE_KEY = 66,
  ITEM_SQUARE_KEY = 67,
  ITEM_RED_CRYSTAL = 68,
  ITEM_BLUE_CRYSTAL = 69,
  ITEM_GREEN_CRYSTAL = 70,
  ITEM_YELLOW_CRYSTAL = 71,
  ITEM_STONE_TABLET_PIECE = 72,
  ITEM_TASTY_WATER = 73,
  ITEM_THE_MAGICIAN = 74,
  ITEM_THE_HIEROPHANT = 75,
  ITEM_THE_HERMIT = 76,
  ITEM_THE_WORLD = 77,
  ITEM_NONE = -1,
};

#define ITEM_NUM (ITEM_THE_WORLD + 1)

#endif  // GUARD_ZOKTAI_CONST_ITEM_H
