#ifndef GUARD_ZOKTAI_CONST_MAGIC_H
#define GUARD_ZOKTAI_CONST_MAGIC_H

#define MAGIC_SOL 0
#define MAGIC_DARK 1
#define MAGIC_FLAME 2
#define MAGIC_FROST 3
#define MAGIC_CLOUD 4
#define MAGIC_EARTH 5
#define MAGIC_TRANSFORM 6
#define MAGIC_RISING_SUN 7
#define MAGIC_FREEZE 8
#define MAGIC_DASH 9
#define MAGIC_HEALING 10
#define MAGIC_DYNAMITE 11
#define MAGIC_COFFIN 12
#define MAGIC_BAT 13
#define MAGIC_RAT 14
#define MAGIC_WOLF 15
#define MAGIC_NONE (-1)

#endif  // GUARD_ZOKTAI_CONST_MAGIC_H
