#ifndef GUARD_ZOKTAI_CONST_WEAPON_H
#define GUARD_ZOKTAI_CONST_WEAPON_H

enum WeaponID {
  WEAPON_NONE,
  WEAPON_GRADIUS,        // グラディウス
  WEAPON_SHORT_SWORD,    // ショートソード
  WEAPON_BROAD_SWORD,    // ブロードソード
  WEAPON_LONG_SWORD,     // ロングソード
  WEAPON_DULL_BLADE,     // なまくら
  WEAPON_ZWEIHANDER,     // ツヴァイハンダー
  WEAPON_FLAMEBERGE,     // フランベルジュ
  WEAPON_CLAYMORE,       // クレイモア
  WEAPON_MAGIC_SWORD,    // マジックソード
  WEAPON_KATANA,         // 刀
  WEAPON_BASTARD_SWORD,  // バスタードソード
  WEAPON_GREAT_SWORD,    // グレートソード
  WEAPON_BUSHIDO_SWORD,  // 武士道ブレード
  WEAPON_BLOOD_SWORD,    // ブラッドソード
  WEAPON_MURAMASA,       // 村正
  WEAPON_VORPAL_SWORD,   // ウォーバルソード
  WEAPON_SOLAR_SWORD,    // 太陽の剣
  WEAPON_DARK_SWORD,     // 暗黒の剣
  WEAPON_GRAM,           // グラム
  WEAPON_SHORT_SPEAR,
  WEAPON_GLAIVE,
  WEAPON_LONG_SPEAR,
  WEAPON_LANCE,
  WEAPON_STAFF,
  WEAPON_CORSESCA,
  WEAPON_FIRE_PAW,
  WEAPON_BARDICHE,
  WEAPON_ICE_GLAIVE,
  WEAPON_RUNE_GLAIVE,
  WEAPON_PARTIZAN,
  WEAPON_THUNDER_SPEAR,
  WEAPON_BLOOD_SPEAR,
  WEAPON_GRAND_LANCE,
  WEAPON_RUNE_SPEAR,
  WEAPON_HALBERD,
  WEAPON_WHITE_QUEEN,
  WEAPON_BLACK_QUEEN,
  WEAPON_GUNGNIR,
  WEAPON_CLUB,
  WEAPON_HAMMER,
  WEAPON_MACE,
  WEAPON_FLAIL,
  WEAPON_POUNDER,
  WEAPON_AXE,
  WEAPON_MAUL,
  WEAPON_SILVER_MACE,
  WEAPON_SILVER_FLAIL,
  WEAPON_HEAVY_MACE,
  WEAPON_BATTLE_AXE,
  WEAPON_WAR_HAMMER,
  WEAPON_BLOODY_MACE,
  WEAPON_MORNING_STAR,
  WEAPON_HEAVY_AXE,
  WEAPON_EARTH_SHAKER,
  WEAPON_DAYBREAK,
  WEAPON_TWILIGHT,
  WEAPON_MJOLLNIR,
  WEAPON_BROKEN_GUN,
  WEAPON_GUN_DEL_SOL,
  WEAPON_GUN_DEL_HELL,
  WEAPON_MEGA_BUSTER,
  WEAPON_STAR_PIECE,
  WEAPON_ASTRO_SWORD,  // アストロソード
  WEAPON_ASTRO_SPEAR,
  WEAPON_ASTRO_HAMMER,
};

#endif  // GUARD_ZOKTAI_CONST_WEAPON_H
