	.include "asm/macros.inc"

	.syntax unified
	
	.text

	thumb_func_start FUN_080efb60
FUN_080efb60: @ 0x080EFB60
  .include "asm/func/FUN_080efb60.inc"

	thumb_func_start FUN_080efc44
FUN_080efc44: @ 0x080EFC44
  .include "asm/func/FUN_080efc44.inc"

	thumb_func_start FUN_080efd44
FUN_080efd44: @ 0x080EFD44
  .include "asm/func/FUN_080efd44.inc"

	thumb_func_start FUN_080efe38
FUN_080efe38: @ 0x080EFE38
  .include "asm/func/FUN_080efe38.inc"

	thumb_func_start Enemy_080eff14
Enemy_080eff14: @ 0x080EFF14
  .include "asm/func/Enemy_080eff14.inc"

	thumb_func_start FUN_080f00ec
FUN_080f00ec: @ 0x080F00EC
  .include "asm/func/FUN_080f00ec.inc"

	thumb_func_start FUN_080f0320
FUN_080f0320: @ 0x080F0320
  .include "asm/func/FUN_080f0320.inc"

	thumb_func_start FUN_080f0430
FUN_080f0430: @ 0x080F0430
  .include "asm/func/FUN_080f0430.inc"

	thumb_func_start FUN_080f06ac
FUN_080f06ac: @ 0x080F06AC
  .include "asm/func/FUN_080f06ac.inc"

	thumb_func_start FUN_080f06b0
FUN_080f06b0: @ 0x080F06B0
  .include "asm/func/FUN_080f06b0.inc"

	thumb_func_start FUN_080f07d0
FUN_080f07d0: @ 0x080F07D0
  .include "asm/func/FUN_080f07d0.inc"

	thumb_func_start FUN_080f0868
FUN_080f0868: @ 0x080F0868
  .include "asm/func/FUN_080f0868.inc"

	thumb_func_start FUN_080f0914
FUN_080f0914: @ 0x080F0914
  .include "asm/func/FUN_080f0914.inc"

	thumb_func_start FUN_080f09a4
FUN_080f09a4: @ 0x080F09A4
  .include "asm/func/FUN_080f09a4.inc"

	thumb_func_start FUN_080f09e0
FUN_080f09e0: @ 0x080F09E0
  .include "asm/func/FUN_080f09e0.inc"

	thumb_func_start FUN_080f0a0c
FUN_080f0a0c: @ 0x080F0A0C
  .include "asm/func/FUN_080f0a0c.inc"

	thumb_func_start FUN_080f0b3c
FUN_080f0b3c: @ 0x080F0B3C
  .include "asm/func/FUN_080f0b3c.inc"

	thumb_func_start FUN_080f0e78
FUN_080f0e78: @ 0x080F0E78
  .include "asm/func/FUN_080f0e78.inc"

	thumb_func_start FUN_080f11d0
FUN_080f11d0: @ 0x080F11D0
  .include "asm/func/FUN_080f11d0.inc"

	thumb_func_start FUN_080f12c4
FUN_080f12c4: @ 0x080F12C4
  .include "asm/func/FUN_080f12c4.inc"

	thumb_func_start FUN_080f19cc
FUN_080f19cc: @ 0x080F19CC
  .include "asm/func/FUN_080f19cc.inc"

	thumb_func_start FUN_080f1c54
FUN_080f1c54: @ 0x080F1C54
  .include "asm/func/FUN_080f1c54.inc"

	thumb_func_start FUN_080f1cb8
FUN_080f1cb8: @ 0x080F1CB8
  .include "asm/func/FUN_080f1cb8.inc"

	thumb_func_start FUN_080f1cf0
FUN_080f1cf0: @ 0x080F1CF0
  .include "asm/func/FUN_080f1cf0.inc"

	thumb_func_start FUN_080f1de4
FUN_080f1de4: @ 0x080F1DE4
  .include "asm/func/FUN_080f1de4.inc"

	thumb_func_start FUN_080f1e0c
FUN_080f1e0c: @ 0x080F1E0C
  .include "asm/func/FUN_080f1e0c.inc"

	thumb_func_start FUN_080f1e78
FUN_080f1e78: @ 0x080F1E78
  .include "asm/func/FUN_080f1e78.inc"

	thumb_func_start FUN_080f1ef8
FUN_080f1ef8: @ 0x080F1EF8
  .include "asm/func/FUN_080f1ef8.inc"

	thumb_func_start FUN_080f2074
FUN_080f2074: @ 0x080F2074
  .include "asm/func/FUN_080f2074.inc"

	thumb_func_start FUN_080f2160
FUN_080f2160: @ 0x080F2160
  .include "asm/func/FUN_080f2160.inc"

	thumb_func_start FUN_080f2254
FUN_080f2254: @ 0x080F2254
  .include "asm/func/FUN_080f2254.inc"

	thumb_func_start FUN_080f2278
FUN_080f2278: @ 0x080F2278
  .include "asm/func/FUN_080f2278.inc"

	thumb_func_start FUN_080f229c
FUN_080f229c: @ 0x080F229C
  .include "asm/func/FUN_080f229c.inc"

	thumb_func_start FUN_080f22c0
FUN_080f22c0: @ 0x080F22C0
  .include "asm/func/FUN_080f22c0.inc"

	thumb_func_start FUN_080f22c4
FUN_080f22c4: @ 0x080F22C4
  .include "asm/func/FUN_080f22c4.inc"

	thumb_func_start FUN_080f22e8
FUN_080f22e8: @ 0x080F22E8
  .include "asm/func/FUN_080f22e8.inc"

	thumb_func_start FUN_080f230c
FUN_080f230c: @ 0x080F230C
  .include "asm/func/FUN_080f230c.inc"

	thumb_func_start FUN_080f2330
FUN_080f2330: @ 0x080F2330
  .include "asm/func/FUN_080f2330.inc"

	thumb_func_start FUN_080f2364
FUN_080f2364: @ 0x080F2364
  .include "asm/func/FUN_080f2364.inc"

	thumb_func_start FUN_080f248c
FUN_080f248c: @ 0x080F248C
  .include "asm/func/FUN_080f248c.inc"
