	.include "asm/macros.inc"

	.syntax unified
	
	.text

	thumb_func_start FUN_080efb60
FUN_080efb60: @ 0x080EFB60
  .include "asm/func/FUN_080efb60.inc"

	thumb_func_start FUN_080efc44
FUN_080efc44: @ 0x080EFC44
  .include "asm/func/FUN_080efc44.inc"

	thumb_func_start FUN_080efd44
FUN_080efd44: @ 0x080EFD44
  .include "asm/func/FUN_080efd44.inc"

	thumb_func_start FUN_080efe38
FUN_080efe38: @ 0x080EFE38
  .include "asm/func/FUN_080efe38.inc"

	thumb_func_start Enemy_080eff14
Enemy_080eff14: @ 0x080EFF14
  .include "asm/func/Enemy_080eff14.inc"

	thumb_func_start FUN_080f00ec
FUN_080f00ec: @ 0x080F00EC
  .include "asm/func/FUN_080f00ec.inc"

	thumb_func_start FUN_080f0320
FUN_080f0320: @ 0x080F0320
  .include "asm/func/FUN_080f0320.inc"

	thumb_func_start FUN_080f0430
FUN_080f0430: @ 0x080F0430
  .include "asm/func/FUN_080f0430.inc"

	thumb_func_start FUN_080f06ac
FUN_080f06ac: @ 0x080F06AC
  .include "asm/func/FUN_080f06ac.inc"

	thumb_func_start FUN_080f06b0
FUN_080f06b0: @ 0x080F06B0
  .include "asm/func/FUN_080f06b0.inc"

	thumb_func_start FUN_080f07d0
FUN_080f07d0: @ 0x080F07D0
  .include "asm/func/FUN_080f07d0.inc"

	thumb_func_start FUN_080f0868
FUN_080f0868: @ 0x080F0868
  .include "asm/func/FUN_080f0868.inc"

	thumb_func_start FUN_080f0914
FUN_080f0914: @ 0x080F0914
  .include "asm/func/FUN_080f0914.inc"

	thumb_func_start FUN_080f09a4
FUN_080f09a4: @ 0x080F09A4
  .include "asm/func/FUN_080f09a4.inc"

	thumb_func_start FUN_080f09e0
FUN_080f09e0: @ 0x080F09E0
  .include "asm/func/FUN_080f09e0.inc"

	thumb_func_start FUN_080f0a0c
FUN_080f0a0c: @ 0x080F0A0C
  .include "asm/func/FUN_080f0a0c.inc"

	thumb_func_start FUN_080f0b3c
FUN_080f0b3c: @ 0x080F0B3C
  .include "asm/func/FUN_080f0b3c.inc"

	thumb_func_start FUN_080f0e78
FUN_080f0e78: @ 0x080F0E78
  .include "asm/func/FUN_080f0e78.inc"

	thumb_func_start FUN_080f11d0
FUN_080f11d0: @ 0x080F11D0
  .include "asm/func/FUN_080f11d0.inc"

	thumb_func_start FUN_080f12c4
FUN_080f12c4: @ 0x080F12C4
  .include "asm/func/FUN_080f12c4.inc"

	thumb_func_start FUN_080f19cc
FUN_080f19cc: @ 0x080F19CC
  .include "asm/func/FUN_080f19cc.inc"

	thumb_func_start FUN_080f1c54
FUN_080f1c54: @ 0x080F1C54
  .include "asm/func/FUN_080f1c54.inc"

	thumb_func_start FUN_080f1cb8
FUN_080f1cb8: @ 0x080F1CB8
  .include "asm/func/FUN_080f1cb8.inc"

	thumb_func_start FUN_080f1cf0
FUN_080f1cf0: @ 0x080F1CF0
  .include "asm/func/FUN_080f1cf0.inc"

	thumb_func_start FUN_080f1de4
FUN_080f1de4: @ 0x080F1DE4
  .include "asm/func/FUN_080f1de4.inc"

	thumb_func_start FUN_080f1e0c
FUN_080f1e0c: @ 0x080F1E0C
  .include "asm/func/FUN_080f1e0c.inc"

	thumb_func_start FUN_080f1e78
FUN_080f1e78: @ 0x080F1E78
  .include "asm/func/FUN_080f1e78.inc"

	thumb_func_start FUN_080f1ef8
FUN_080f1ef8: @ 0x080F1EF8
  .include "asm/func/FUN_080f1ef8.inc"

	thumb_func_start FUN_080f2074
FUN_080f2074: @ 0x080F2074
  .include "asm/func/FUN_080f2074.inc"

	thumb_func_start FUN_080f2160
FUN_080f2160: @ 0x080F2160
  .include "asm/func/FUN_080f2160.inc"

	thumb_func_start FUN_080f2254
FUN_080f2254: @ 0x080F2254
  .include "asm/func/FUN_080f2254.inc"

	thumb_func_start FUN_080f2278
FUN_080f2278: @ 0x080F2278
  .include "asm/func/FUN_080f2278.inc"

	thumb_func_start FUN_080f229c
FUN_080f229c: @ 0x080F229C
  .include "asm/func/FUN_080f229c.inc"

	thumb_func_start FUN_080f22c0
FUN_080f22c0: @ 0x080F22C0
  .include "asm/func/FUN_080f22c0.inc"

	thumb_func_start FUN_080f22c4
FUN_080f22c4: @ 0x080F22C4
  .include "asm/func/FUN_080f22c4.inc"

	thumb_func_start FUN_080f22e8
FUN_080f22e8: @ 0x080F22E8
  .include "asm/func/FUN_080f22e8.inc"

	thumb_func_start FUN_080f230c
FUN_080f230c: @ 0x080F230C
  .include "asm/func/FUN_080f230c.inc"

	thumb_func_start FUN_080f2330
FUN_080f2330: @ 0x080F2330
  .include "asm/func/FUN_080f2330.inc"

	thumb_func_start FUN_080f2364
FUN_080f2364: @ 0x080F2364
  .include "asm/func/FUN_080f2364.inc"

	thumb_func_start FUN_080f248c
FUN_080f248c: @ 0x080F248C
  .include "asm/func/FUN_080f248c.inc"

	thumb_func_start FUN_080f2644
FUN_080f2644: @ 0x080F2644
  .include "asm/func/FUN_080f2644.inc"

	thumb_func_start FUN_080f2864
FUN_080f2864: @ 0x080F2864
  .include "asm/func/FUN_080f2864.inc"

	thumb_func_start FUN_080f2a40
FUN_080f2a40: @ 0x080F2A40
  .include "asm/func/FUN_080f2a40.inc"

	thumb_func_start FUN_080f2d04
FUN_080f2d04: @ 0x080F2D04
  .include "asm/func/FUN_080f2d04.inc"

	thumb_func_start FUN_080f2ec0
FUN_080f2ec0: @ 0x080F2EC0
  .include "asm/func/FUN_080f2ec0.inc"

	thumb_func_start FUN_080f31c4
FUN_080f31c4: @ 0x080F31C4
  .include "asm/func/FUN_080f31c4.inc"

	thumb_func_start FUN_080f33e8
FUN_080f33e8: @ 0x080F33E8
  .include "asm/func/FUN_080f33e8.inc"

	thumb_func_start FUN_080f34a0
FUN_080f34a0: @ 0x080F34A0
  .include "asm/func/FUN_080f34a0.inc"

	thumb_func_start FUN_080f34ec
FUN_080f34ec: @ 0x080F34EC
  .include "asm/func/FUN_080f34ec.inc"

	thumb_func_start FUN_080f3574
FUN_080f3574: @ 0x080F3574
  .include "asm/func/FUN_080f3574.inc"

	thumb_func_start FUN_080f35fc
FUN_080f35fc: @ 0x080F35FC
  .include "asm/func/FUN_080f35fc.inc"

	thumb_func_start Enemy_Init_080f3680
Enemy_Init_080f3680: @ 0x080F3680
  .include "asm/func/Enemy_Init_080f3680.inc"

	thumb_func_start FUN_080f3718
FUN_080f3718: @ 0x080F3718
  .include "asm/func/FUN_080f3718.inc"

	thumb_func_start FUN_080f3cdc
FUN_080f3cdc: @ 0x080F3CDC
  .include "asm/func/FUN_080f3cdc.inc"

	thumb_func_start FUN_080f3d28
FUN_080f3d28: @ 0x080F3D28
  .include "asm/func/FUN_080f3d28.inc"

	thumb_func_start FUN_080f410c
FUN_080f410c: @ 0x080F410C
  .include "asm/func/FUN_080f410c.inc"

	thumb_func_start FUN_080f44f4
FUN_080f44f4: @ 0x080F44F4
  .include "asm/func/FUN_080f44f4.inc"

	thumb_func_start FUN_080f46a4
FUN_080f46a4: @ 0x080F46A4
  .include "asm/func/FUN_080f46a4.inc"

	thumb_func_start FUN_080f47c8
FUN_080f47c8: @ 0x080F47C8
  .include "asm/func/FUN_080f47c8.inc"

	thumb_func_start FUN_080f48ac
FUN_080f48ac: @ 0x080F48AC
  .include "asm/func/FUN_080f48ac.inc"

	thumb_func_start FUN_080f5104
FUN_080f5104: @ 0x080F5104
  .include "asm/func/FUN_080f5104.inc"

	thumb_func_start FUN_080f5208
FUN_080f5208: @ 0x080F5208
  .include "asm/func/FUN_080f5208.inc"

	thumb_func_start FUN_080f54e4
FUN_080f54e4: @ 0x080F54E4
  .include "asm/func/FUN_080f54e4.inc"

	thumb_func_start FUN_080f56ec
FUN_080f56ec: @ 0x080F56EC
  .include "asm/func/FUN_080f56ec.inc"

	thumb_func_start FUN_080f5b34
FUN_080f5b34: @ 0x080F5B34
  .include "asm/func/FUN_080f5b34.inc"

	thumb_func_start FUN_080f5c0c
FUN_080f5c0c: @ 0x080F5C0C
  .include "asm/func/FUN_080f5c0c.inc"

	thumb_func_start FUN_080f5fac
FUN_080f5fac: @ 0x080F5FAC
  .include "asm/func/FUN_080f5fac.inc"

	thumb_func_start FUN_080f624c
FUN_080f624c: @ 0x080F624C
  .include "asm/func/FUN_080f624c.inc"

	thumb_func_start FUN_080f62a8
FUN_080f62a8: @ 0x080F62A8
  .include "asm/func/FUN_080f62a8.inc"

	thumb_func_start FUN_080f62ac
FUN_080f62ac: @ 0x080F62AC
  .include "asm/func/FUN_080f62ac.inc"

	thumb_func_start FUN_080f62b0
FUN_080f62b0: @ 0x080F62B0
  .include "asm/func/FUN_080f62b0.inc"

	thumb_func_start FUN_080f64f0
FUN_080f64f0: @ 0x080F64F0
  .include "asm/func/FUN_080f64f0.inc"

	thumb_func_start FUN_080f65a8
FUN_080f65a8: @ 0x080F65A8
  .include "asm/func/FUN_080f65a8.inc"

	thumb_func_start FUN_080f6604
FUN_080f6604: @ 0x080F6604
  .include "asm/func/FUN_080f6604.inc"

	thumb_func_start FUN_080f6868
FUN_080f6868: @ 0x080F6868
  .include "asm/func/FUN_080f6868.inc"

	thumb_func_start FUN_080f6af0
FUN_080f6af0: @ 0x080F6AF0
  .include "asm/func/FUN_080f6af0.inc"

	thumb_func_start FUN_080f6bac
FUN_080f6bac: @ 0x080F6BAC
  .include "asm/func/FUN_080f6bac.inc"

	thumb_func_start FUN_080f6c74
FUN_080f6c74: @ 0x080F6C74
  .include "asm/func/FUN_080f6c74.inc"

	thumb_func_start FUN_080f6e34
FUN_080f6e34: @ 0x080F6E34
  .include "asm/func/FUN_080f6e34.inc"

	thumb_func_start FUN_080f6e64
FUN_080f6e64: @ 0x080F6E64
  .include "asm/func/FUN_080f6e64.inc"

	thumb_func_start FUN_080f79e8
FUN_080f79e8: @ 0x080F79E8
  .include "asm/func/FUN_080f79e8.inc"

	thumb_func_start FUN_080f8400
FUN_080f8400: @ 0x080F8400
  .include "asm/func/FUN_080f8400.inc"

	thumb_func_start FUN_080f84d4
FUN_080f84d4: @ 0x080F84D4
  .include "asm/func/FUN_080f84d4.inc"

	thumb_func_start FUN_080f8844
FUN_080f8844: @ 0x080F8844
  .include "asm/func/FUN_080f8844.inc"

	thumb_func_start FUN_080f897c
FUN_080f897c: @ 0x080F897C
  .include "asm/func/FUN_080f897c.inc"

	thumb_func_start FUN_080f8abc
FUN_080f8abc: @ 0x080F8ABC
  .include "asm/func/FUN_080f8abc.inc"

	thumb_func_start FUN_080f8ae0
FUN_080f8ae0: @ 0x080F8AE0
  .include "asm/func/FUN_080f8ae0.inc"

	thumb_func_start FUN_080f8bb8
FUN_080f8bb8: @ 0x080F8BB8
  .include "asm/func/FUN_080f8bb8.inc"

	thumb_func_start FUN_080f8c10
FUN_080f8c10: @ 0x080F8C10
  .include "asm/func/FUN_080f8c10.inc"

	thumb_func_start FUN_080f8c2c
FUN_080f8c2c: @ 0x080F8C2C
  .include "asm/func/FUN_080f8c2c.inc"

	thumb_func_start FUN_080f8c58
FUN_080f8c58: @ 0x080F8C58
  .include "asm/func/FUN_080f8c58.inc"

	thumb_func_start FUN_080f8cac
FUN_080f8cac: @ 0x080F8CAC
  .include "asm/func/FUN_080f8cac.inc"

	thumb_func_start FUN_080f8cec
FUN_080f8cec: @ 0x080F8CEC
  .include "asm/func/FUN_080f8cec.inc"

	thumb_func_start FUN_080f8cf0
FUN_080f8cf0: @ 0x080F8CF0
  .include "asm/func/FUN_080f8cf0.inc"

	thumb_func_start FUN_080f8d20
FUN_080f8d20: @ 0x080F8D20
  .include "asm/func/FUN_080f8d20.inc"

	thumb_func_start FUN_080f8d60
FUN_080f8d60: @ 0x080F8D60
  .include "asm/func/FUN_080f8d60.inc"

	thumb_func_start FUN_080f8da4
FUN_080f8da4: @ 0x080F8DA4
  .include "asm/func/FUN_080f8da4.inc"

	thumb_func_start FUN_080f8e3c
FUN_080f8e3c: @ 0x080F8E3C
  .include "asm/func/FUN_080f8e3c.inc"

	thumb_func_start FUN_080f8e84
FUN_080f8e84: @ 0x080F8E84
  .include "asm/func/FUN_080f8e84.inc"

	thumb_func_start FUN_080f8f04
FUN_080f8f04: @ 0x080F8F04
  .include "asm/func/FUN_080f8f04.inc"

	thumb_func_start FUN_080f9a38
FUN_080f9a38: @ 0x080F9A38
  .include "asm/func/FUN_080f9a38.inc"

	thumb_func_start FUN_080f9b34
FUN_080f9b34: @ 0x080F9B34
  .include "asm/func/FUN_080f9b34.inc"

	thumb_func_start FUN_080f9b5c
FUN_080f9b5c: @ 0x080F9B5C
  .include "asm/func/FUN_080f9b5c.inc"

	thumb_func_start FUN_080f9b74
FUN_080f9b74: @ 0x080F9B74
  .include "asm/func/FUN_080f9b74.inc"

	thumb_func_start FUN_080f9b80
FUN_080f9b80: @ 0x080F9B80
  .include "asm/func/FUN_080f9b80.inc"

	thumb_func_start FUN_080f9b9c
FUN_080f9b9c: @ 0x080F9B9C
  .include "asm/func/FUN_080f9b9c.inc"

	thumb_func_start FUN_080f9bec
FUN_080f9bec: @ 0x080F9BEC
  .include "asm/func/FUN_080f9bec.inc"

	thumb_func_start FUN_080f9bf8
FUN_080f9bf8: @ 0x080F9BF8
  .include "asm/func/FUN_080f9bf8.inc"

	thumb_func_start FUN_080f9bfc
FUN_080f9bfc: @ 0x080F9BFC
  .include "asm/func/FUN_080f9bfc.inc"

	thumb_func_start FUN_080f9c20
FUN_080f9c20: @ 0x080F9C20
  .include "asm/func/FUN_080f9c20.inc"

	thumb_func_start FUN_080f9e34
FUN_080f9e34: @ 0x080F9E34
  .include "asm/func/FUN_080f9e34.inc"

	thumb_func_start FUN_080f9ee0
FUN_080f9ee0: @ 0x080F9EE0
  .include "asm/func/FUN_080f9ee0.inc"

	thumb_func_start FUN_080f9f20
FUN_080f9f20: @ 0x080F9F20
  .include "asm/func/FUN_080f9f20.inc"

	thumb_func_start FUN_080fa2ac
FUN_080fa2ac: @ 0x080FA2AC
  .include "asm/func/FUN_080fa2ac.inc"

	thumb_func_start FUN_080fa354
FUN_080fa354: @ 0x080FA354
  .include "asm/func/FUN_080fa354.inc"

	thumb_func_start FUN_080fa384
FUN_080fa384: @ 0x080FA384
  .include "asm/func/FUN_080fa384.inc"

	thumb_func_start FUN_080fa77c
FUN_080fa77c: @ 0x080FA77C
  .include "asm/func/FUN_080fa77c.inc"

	thumb_func_start FUN_080fa7a4
FUN_080fa7a4: @ 0x080FA7A4
  .include "asm/func/FUN_080fa7a4.inc"

	thumb_func_start FUN_080fa958
FUN_080fa958: @ 0x080FA958
  .include "asm/func/FUN_080fa958.inc"

	thumb_func_start FUN_080faa98
FUN_080faa98: @ 0x080FAA98
  .include "asm/func/FUN_080faa98.inc"

	thumb_func_start FUN_080faad8
FUN_080faad8: @ 0x080FAAD8
  .include "asm/func/FUN_080faad8.inc"

	thumb_func_start FUN_080fadd4
FUN_080fadd4: @ 0x080FADD4
  .include "asm/func/FUN_080fadd4.inc"

	thumb_func_start FUN_080fae14
FUN_080fae14: @ 0x080FAE14
  .include "asm/func/FUN_080fae14.inc"

	thumb_func_start FUN_080fb4d0
FUN_080fb4d0: @ 0x080FB4D0
  .include "asm/func/FUN_080fb4d0.inc"

	thumb_func_start FUN_080fba28
FUN_080fba28: @ 0x080FBA28
  .include "asm/func/FUN_080fba28.inc"

	thumb_func_start FUN_080fba40
FUN_080fba40: @ 0x080FBA40
  .include "asm/func/FUN_080fba40.inc"

	thumb_func_start FUN_080fba64
FUN_080fba64: @ 0x080FBA64
  .include "asm/func/FUN_080fba64.inc"

	thumb_func_start FUN_080fc0b8
FUN_080fc0b8: @ 0x080FC0B8
  .include "asm/func/FUN_080fc0b8.inc"

	thumb_func_start FUN_080fc174
FUN_080fc174: @ 0x080FC174
  .include "asm/func/FUN_080fc174.inc"

	thumb_func_start FUN_080fc1e4
FUN_080fc1e4: @ 0x080FC1E4
  .include "asm/func/FUN_080fc1e4.inc"

	thumb_func_start FUN_080fc28c
FUN_080fc28c: @ 0x080FC28C
  .include "asm/func/FUN_080fc28c.inc"

	thumb_func_start FUN_080fc4ec
FUN_080fc4ec: @ 0x080FC4EC
  .include "asm/func/FUN_080fc4ec.inc"

	thumb_func_start FUN_080fc548
FUN_080fc548: @ 0x080FC548
  .include "asm/func/FUN_080fc548.inc"

	thumb_func_start FUN_080fc6f4
FUN_080fc6f4: @ 0x080FC6F4
  .include "asm/func/FUN_080fc6f4.inc"

	thumb_func_start FUN_080fd08c
FUN_080fd08c: @ 0x080FD08C
  .include "asm/func/FUN_080fd08c.inc"

	thumb_func_start FUN_080fe1bc
FUN_080fe1bc: @ 0x080FE1BC
  .include "asm/func/FUN_080fe1bc.inc"

	thumb_func_start FUN_080fe274
FUN_080fe274: @ 0x080FE274
  .include "asm/func/FUN_080fe274.inc"

	thumb_func_start FUN_080fe704
FUN_080fe704: @ 0x080FE704
  .include "asm/func/FUN_080fe704.inc"

	thumb_func_start FUN_080fe7f4
FUN_080fe7f4: @ 0x080FE7F4
  .include "asm/func/FUN_080fe7f4.inc"

	thumb_func_start FUN_080ff048
FUN_080ff048: @ 0x080FF048
  .include "asm/func/FUN_080ff048.inc"

	thumb_func_start FUN_080ff05c
FUN_080ff05c: @ 0x080FF05C
  .include "asm/func/FUN_080ff05c.inc"

	thumb_func_start FUN_080ff06c
FUN_080ff06c: @ 0x080FF06C
  .include "asm/func/FUN_080ff06c.inc"

	thumb_func_start FUN_080ff270
FUN_080ff270: @ 0x080FF270
  .include "asm/func/FUN_080ff270.inc"

