	.include "asm/macros.inc"

	.syntax unified
	
	.text

	thumb_func_start Entity0821b7fc_Update_Helper_0821b35c
Entity0821b7fc_Update_Helper_0821b35c: @ 0x0821B35C
  .include "asm/func/Entity0821b7fc_Update_Helper_0821b35c.inc"

	thumb_func_start FUN_0821b470
FUN_0821b470: @ 0x0821B470
  .include "asm/func/FUN_0821b470.inc"

	thumb_func_start Entity0821b7fc_Update
Entity0821b7fc_Update: @ 0x0821B578
  .include "asm/func/Entity0821b7fc_Update.inc"

	thumb_func_start FUN_0821b73c
FUN_0821b73c: @ 0x0821B73C
  .include "asm/func/FUN_0821b73c.inc"

	thumb_func_start FUN_0821b760
FUN_0821b760: @ 0x0821B760
  .include "asm/func/FUN_0821b760.inc"
