	.include "asm/macros.inc"

	.syntax unified
	
	.text

	thumb_func_start FUN_080de174
FUN_080de174: @ 0x080DE174
  .include "asm/func/FUN_080de174.inc"

	thumb_func_start FUN_080de1cc
FUN_080de1cc: @ 0x080DE1CC
  .include "asm/func/FUN_080de1cc.inc"

	thumb_func_start FUN_080de344
FUN_080de344: @ 0x080DE344
  .include "asm/func/FUN_080de344.inc"

	thumb_func_start FUN_080de3b4
FUN_080de3b4: @ 0x080DE3B4
  .include "asm/func/FUN_080de3b4.inc"

	thumb_func_start FUN_080de52c
FUN_080de52c: @ 0x080DE52C
  .include "asm/func/FUN_080de52c.inc"

	thumb_func_start FUN_080de6b0
FUN_080de6b0: @ 0x080DE6B0
  .include "asm/func/FUN_080de6b0.inc"

	thumb_func_start FUN_080de7a0
FUN_080de7a0: @ 0x080DE7A0
  .include "asm/func/FUN_080de7a0.inc"

	thumb_func_start FUN_080de81c
FUN_080de81c: @ 0x080DE81C
  .include "asm/func/FUN_080de81c.inc"

	thumb_func_start FUN_080de820
FUN_080de820: @ 0x080DE820
  .include "asm/func/FUN_080de820.inc"

	thumb_func_start FUN_080debbc
FUN_080debbc: @ 0x080DEBBC
  .include "asm/func/FUN_080debbc.inc"

	thumb_func_start FUN_080defd0
FUN_080defd0: @ 0x080DEFD0
  .include "asm/func/FUN_080defd0.inc"

	thumb_func_start FUN_080df148
FUN_080df148: @ 0x080DF148
  .include "asm/func/FUN_080df148.inc"

	thumb_func_start FUN_080df31c
FUN_080df31c: @ 0x080DF31C
  .include "asm/func/FUN_080df31c.inc"

	thumb_func_start FUN_080df3b4
FUN_080df3b4: @ 0x080DF3B4
  .include "asm/func/FUN_080df3b4.inc"

	thumb_func_start FUN_080df3f4
FUN_080df3f4: @ 0x080DF3F4
  .include "asm/func/FUN_080df3f4.inc"

	thumb_func_start Entity080df420_Create
Entity080df420_Create: @ 0x080DF420
  .include "asm/func/Entity080df420_Create.inc"
