String_14BE:: @ 0x08D08B6D, ID: 5310
  .string "<WEIGHT>キャスト</WEIGHT>$"
String_14BF:: @ 0x08D08B87, ID: 5311
  .string "<WEIGHT><NAME></WEIGHT>\n水間真紀$"
String_14C0:: @ 0x08D08BA8, ID: 5312
  .string "<WEIGHT>おてんこさま/リンゴ</WEIGHT>\n大塚明夫$"
String_14C1:: @ 0x08D08BD6, ID: 5313
  .string "<WEIGHT>サバタ</WEIGHT>\n重松朋$"
String_14C2:: @ 0x08D08BF5, ID: 5314
  .string "<WEIGHT>リタ/スミレ/ドゥラスロ―ル</WEIGHT>\n小暮英麻$"
String_14C3:: @ 0x08D08C2A, ID: 5315
  .string "<WEIGHT>ザジ/ドゥネイル</WEIGHT>\n氷上恭子$"
String_14C4:: @ 0x08D08C54, ID: 5316
  .string "<WEIGHT>シャイアン/スミス/エンニオ</WEIGHT>\n上田陽司$"
String_14C5:: @ 0x08D08C89, ID: 5317
  .string "<WEIGHT>レディ/ドヴァリン</WEIGHT>\n児玉孝子$"
String_14C6:: @ 0x08D08CB5, ID: 5318
  .string "<WEIGHT>ダ―イン/キッド/棺桶屋</WEIGHT>\n中村俊洋$"
String_14C7:: @ 0x08D08CE6, ID: 5319
  .string "<WEIGHT>子供たち/</WEIGHT>\n<WEIGHT>エレファンデザイン</WEIGHT>\n坂口翔$"
String_14C8:: @ 0x08D08D2C, ID: 5320
  .string "<WEIGHT>子供たち</WEIGHT>\n松本良\n花岡智将\n高木翔平$"
String_14C9:: @ 0x08D08D5F, ID: 5321
  .string "<WEIGHT>子供たち</WEIGHT>\n宮迫幹\n宮迫慎\n菊池麻美$"
String_14CA:: @ 0x08D08D90, ID: 5322
  .string "<WEIGHT>子供たち</WEIGHT>\n小林大輔\n蓮田真優美\n山田恵太$"
String_14CB:: @ 0x08D08DC7, ID: 5323
  .string "<WEIGHT>子供たち</WEIGHT>\n川渕里奈子\n川渕貴彦\n大竹悠介$"
String_14CC:: @ 0x08D08DFE, ID: 5324
  .string "<WEIGHT>スタッフ</WEIGHT>$"
String_14CD:: @ 0x08D08E18, ID: 5325
  .string "<WEIGHT>原案</WEIGHT>\n小島秀夫$"
String_14CE:: @ 0x08D08E37, ID: 5326
  .string "<WEIGHT>監督/脚本/</WEIGHT>\n<WEIGHT>キャラクタ―原案</WEIGHT>\n中村如哉$"
String_14CF:: @ 0x08D08E7E, ID: 5327
  .string "<WEIGHT>キャラクタ―デザイン</WEIGHT>\n斎藤淳太郎$"
String_14D0:: @ 0x08D08EAF, ID: 5328
  .string "<WEIGHT>スクリプトユニット</WEIGHT>\n上原偏利\n山田昌孝$"
String_14D1:: @ 0x08D08EE5, ID: 5329
  .string "<WEIGHT>スクリプトユニット</WEIGHT>\n矢野悠子\n吉冨賢介$"
String_14D2:: @ 0x08D08F1B, ID: 5330
  .string "<WEIGHT>プログラムユニット</WEIGHT>\n奥田雅史\n國部勇太\n小林聖$"
String_14D3:: @ 0x08D08F58, ID: 5331
  .string "<WEIGHT>プログラムユニット</WEIGHT>\n石川真也\n山下直芳$"
String_14D4:: @ 0x08D08F8E, ID: 5332
  .string "<WEIGHT>デザインユニット</WEIGHT>\n寺田ひとみ\n横山賢治\n川上徹$"
String_14D5:: @ 0x08D08FCB, ID: 5333
  .string "<WEIGHT>デザインユニット</WEIGHT>\n斎藤淳太郎\n中村如哉$"
String_14D6:: @ 0x08D09001, ID: 5334
  .string "<WEIGHT>サウンドユニット</WEIGHT>\n日比野則彦\n小堀修一$"
String_14D7:: @ 0x08D09037, ID: 5335
  .string "<WEIGHT>サウンドユニット</WEIGHT>\n渡辺雅史\n村岡一樹$"
String_14D8:: @ 0x08D0906B, ID: 5336
  .string "<WEIGHT>サウンドユニット</WEIGHT>\n本田晃弘\n尾崎和一郎\n戸田色音$"
String_14D9:: @ 0x08D090AA, ID: 5337
  .string "<WEIGHT>パブリシティデザイン</WEIGHT>\n八代肇$"
String_14DA:: @ 0x08D090D7, ID: 5338
  .string "<WEIGHT>イラスト</WEIGHT>\n西村誠芳$"
String_14DB:: @ 0x08D090FA, ID: 5339
  .string "<WEIGHT>言語アドバイザ―</WEIGHT>\n寺田ひとみ\nスコット・ドルフ$"
String_14DC:: @ 0x08D09138, ID: 5340
  .string "<WEIGHT>プロモ―ション</WEIGHT>\n倉野次郎(BC)\n半田由紀子(BC)\n千葉茂(BC)$"
String_14DD:: @ 0x08D0917F, ID: 5341
  .string "<WEIGHT>ホ―ムペ―ジ</WEIGHT>\n北村隆明\n久米村隆明$"
String_14DE:: @ 0x08D091B1, ID: 5342
  .string "<WEIGHT>制作協力</WEIGHT>\n任天堂株式会社$"
String_14DF:: @ 0x08D091DA, ID: 5343
  .string "<WEIGHT>制作協力</WEIGHT>\nコロコロコミック編集部$"
String_14E0:: @ 0x08D0920B, ID: 5344
  .string "佐上靖之\n村上孝雄\n石関暁$"
String_14E1:: @ 0x08D09224, ID: 5345
  .string "<WEIGHT>制作協力</WEIGHT>\nひじおか誠\n古城宏$"
String_14E2:: @ 0x08D09250, ID: 5346
  .string "<WEIGHT>制作協力</WEIGHT>\n株式会社カプコン第二開発部$"
String_14E3:: @ 0x08D09285, ID: 5347
  .string "稲船敬二\n安間正博\n江口正和$"
String_14E4:: @ 0x08D092A0, ID: 5348
  .string "新垣秀和\n松田幸悦\n坂野光徳$"
String_14E5:: @ 0x08D092BB, ID: 5349
  .string "<WEIGHT>制作協力</WEIGHT>\n株式会社ソフィックス$"
String_14E6:: @ 0x08D092EA, ID: 5350
  .string "那須寛之\n樋下田健一\n江口信之$"
String_14E7:: @ 0x08D09307, ID: 5351
  .string "<WEIGHT>制作協力</WEIGHT>\n堤崎陽太$"
String_14E8:: @ 0x08D0932A, ID: 5352
  .string "<WEIGHT>制作協力</WEIGHT>\n田中智之(KME)$"
String_14E9:: @ 0x08D09352, ID: 5353
  .string "<WEIGHT>制作協力</WEIGHT>\n常陸亜喜\n藤原宏記\n保谷アヤ$"
String_14EA:: @ 0x08D09387, ID: 5354
  .string "<WEIGHT>ラインプロデュ―サ―</WEIGHT>\n日並雅宏$"
String_14EB:: @ 0x08D093B6, ID: 5355
  .string "<PROC=0><WEIGHT>プロデュ―サ―</WEIGHT>\n小島秀夫$"
String_14EC:: @ 0x08D093E7, ID: 5356
  .string "<WEIGHT>エグゼクティブプロデュ―サ―</WEIGHT>\n吉岡基行$"
String_14ED:: @ 0x08D0941E, ID: 5357
  .string "<WEIGHT>製作/販売</WEIGHT>\nコナミ株式会社<PROC=1>$"
String_14EE:: @ 0x08D09450, ID: 5358
  .string "<WEIGHT>制作/著作</WEIGHT>\n株式会社コナミコンピュ―タ\nエンタテインメントジャパン$"
String_14EF:: @ 0x08D094A1, ID: 5359
  .string "<PROC=0>\n<END>$"
String_14F0:: @ 0x08D094B0, ID: 5360
  .string "太陽と月、闇に帰りし時$"
String_14F1:: @ 0x08D094C7, ID: 5361
  .string " くさびたる太陽の街\n大いなる黄昏に包まれ\n　 深き影を生まん$"
String_14F2:: @ 0x08D09502, ID: 5362
  .string "そは終末を呼ぶものなり$"
String_14F3:: @ 0x08D09519, ID: 5363
  .string "　影、幼き太陽を闇に沈め\n新しき月より光を奪わんとす$"
String_14F4:: @ 0x08D0954D, ID: 5364
  .string "さすれば終末の獣目覚め\n　　世界は混沌の内\n　死界に沈むであろう$"
String_14F5:: @ 0x08D0958C, ID: 5365
  .string "<PROC=0>\n<END>$"
String_14F6:: @ 0x08D0959B, ID: 5366
  .string " 続・ボクらの太陽\n \n        終$"
String_14F7:: @ 0x08D095BA, ID: 5367
  .string "<PROC=0>\n<END>$"
