#!/usr/bin/env -S deno run --allow-read

import { Command } from "@cliffy/command";
import * as gba from "../common/gba/gba.ts";
import type { addr } from "../common/gba/gba.ts";
import * as path from "@std/path";
import * as MFT from "../encoding/mft/mft.ts";
import * as GAS from "../encoding/gas/gas.ts";
import * as ANIM from "../encoding/animation.ts";

const filename = path.basename(import.meta.filename ?? "unknown.ts");
const indent = "  ";

const ID = 0x5130;

// ./tools/dumper/animation.ts ./baserom.gba
const main = () => {
  new Command()
    .name("tilemap.ts")
    .description("Dump Boktai2 Tilemaps")
    .argument("<rom:string>", "Path to a GBA ROM file.")
    .action((opts, romPath) => {
      const rom = new DataView((Deno.readFileSync(romPath)).buffer);
      const hdr = MFT.getFSEntry(rom, ID);
      if (hdr.end == null) throw new Error("Invalid MFT header: end is null");
      const dir = MFT.ParseDirectory(rom, hdr.ptr);

      console.log(`@ Generated by tools/dumper/${filename}\n@ Do not edit this file manually.\n`);
      console.log(GAS.IncludeMacro);
      console.log(`.include "asm/animation.inc"` + "\n");
      console.log(GAS.Align4);
      console.log(GAS.Rodata + "\n");

      console.log(GAS.dumpGlobalSymbol("gAnimDirectory") + ` @ 0x${gba.toHex32(dir.addr)}`);
      console.log(MFT.StringifyDirectory(dir, indent));
      console.log(`@ Files`);

      for (let i = 0; i < dir.entryNum; i++) {
        const start: addr = dir.addr + dir.fileOffsets[i];
        const end: addr = ((i + 1) < dir.entryNum) ? dir.addr + dir.fileOffsets[i + 1] : hdr.end;
        const data = new Uint8Array<ArrayBufferLike>(rom.buffer, start - gba.BASE, end - start);
        const f = ANIM.Parse(data);

        const fileID = dir.ids[i];
        console.log(GAS.Align4);
        console.log(`Animation_${gba.toHex16(fileID)}: @ 0x${gba.toHex32(start)}, index: ${i}`);
        console.log(ANIM.Stringify(f, indent) + "\n");
      }
    })
    .parse(Deno.args);
};

if (import.meta.main) main();
