#!/usr/bin/env -S deno run --allow-read

import { Command } from "@cliffy/command";

import * as VM from "../encoding/script/script.ts";
import * as gba from "../common/gba/gba.ts";
import type { addr } from "../common/gba/gba.ts";
import * as MFT from "../encoding/mft/mft.ts";
import { ByteStream, InstructionReader } from "../bokcc/instruction_reader.ts";
import { buildPrintContext, INCLUDE_DIR } from "../bokcc/print_context.ts";
import * as path from "@std/path";

const filename = path.basename(import.meta.filename ?? "unknown.ts");

const ID = 0xA41E;

// bokcc.ts baserom.gba --strings constants/strings.h > data/scripts/scripts.bokc
const main = () => {
  new Command()
    .name("bokcc.ts")
    .description("ROM内の全スクリプトをデコンパイルして .bokc として標準出力に書き出す。")
    .argument("<rom:string>", "Path to a GBA ROM file.")
    .option("--strings <include:string>", `文字列IDの名前を定義したヘッダ, #include に書く綴りで指定する (${INCLUDE_DIR}/ 配下から読む)`)
    .action((opts, romPath) => {
      const stringsInclude = opts.strings;
      const ctx = buildPrintContext({ strings: stringsInclude });

      try {
        const rom = new DataView((Deno.readFileSync(romPath)).buffer);
        const dir = VM.ParseScriptDirectory(rom, MFT.getFSEntry(rom, ID).ptr);

        // アドレス順でソートする
        const scripts: {
          id: number;
          addr: addr;
        }[] = [];
        for (let i = 0; i < dir.scripts.length; i++) {
          const addr: addr = dir.scripts[i].addr;
          scripts.push({ id: i + 1, addr });
        }
        scripts.sort((a, b) => a.addr - b.addr);

        const alreadyDecompiledScripts = new Set<addr>(); // 同じスクリプトを重複して出力しないため

        console.log(`// Generated by tools/dumper/${filename}\n// Do not edit this file manually.\n`);
        if (stringsInclude) console.log(`#include "${stringsInclude}"\n`);

        // スクリプトを1つずつデコンパイル
        for (let i = 0; i < scripts.length; i++) {
          const script: addr = scripts[i].addr;
          if (alreadyDecompiledScripts.has(script)) continue;

          /**
           *  // 0xXXXXXXXX
           *  ScriptName() {
           *   ...
           *  }
           */
          const reader = new InstructionReader(new ByteStream(rom, script - gba.BASE));
          console.log(`// 0x${gba.toHex32(script)}`);
          try {
            const name = `Script_${gba.toHex16(scripts[i].id)}`;
            let first = true;
            for (const instr of reader.decompile()) {
              console.log(first ? `${name}() ${instr.toString(ctx)}` : instr.toString(ctx));
              first = false;
            }
            console.log("");
            alreadyDecompiledScripts.add(script);
          } catch (e) {
            console.error(`Error decompiling script at index ${i} in 0x${gba.toHex32(script)}: ${e instanceof Error ? e.message : String(e)}`);
            Deno.exit(1);
          }
        }
      } catch (e) {
        console.error(e instanceof Error ? e.message : String(e));
        Deno.exit(1);
      }
    })
    .parse(Deno.args);
};

if (import.meta.main) main();
