#!/usr/bin/env -S deno run --allow-read --allow-write --allow-run

import { getScriptDirectory } from "../parser/script.ts";
import * as gba from "../common/gba/gba.ts";
import type { addr } from "../common/gba/gba.ts";
import * as mft from "../parser/mft.ts";
import { ByteStream, InstructionReader } from "../bokcc/instruction_reader.ts";

const ROM_PATH = "./baserom.gba";

const main = () => {
  const romData = Deno.readFileSync(ROM_PATH);
  const rom = new DataView(romData.buffer);
  const dir = getScriptDirectory(rom, mft.getMftHeader(rom, 0xA41E).ptr);

  // アドレス順でソートする
  const scripts: {
    id: number;
    addr: addr;
  }[] = [];
  for (let i = 0; i < dir.scripts.length; i++) {
    const addr: addr = dir.scripts[i];
    scripts.push({ id: i + 1, addr });
  }
  scripts.sort((a, b) => a.addr - b.addr);

  const alreadyDecompiledScripts = new Set<addr>();

  console.log(`// Generated by tools/dumper/bokcc.ts\n// Do not edit this file manually.\n`);

  for (let i = 0; i < scripts.length; i++) {
    const script: addr = scripts[i].addr;
    if (alreadyDecompiledScripts.has(script)) continue;

    const reader = new InstructionReader(new ByteStream(rom, script - gba.BASE));
    console.log(`// Script_${gba.toHex16(scripts[i].id)} at 0x${gba.toHex32(script)}`);
    try {
      for (const instr of reader.decompile()) {
        console.log(instr.toString());
      }
      console.log("");
      alreadyDecompiledScripts.add(script);
    } catch (e) {
      console.error(`Error decompiling script at index ${i} in 0x${gba.toHex32(script)}: ${e instanceof Error ? e.message : String(e)}`);
      Deno.exit(1);
    }
  }
};

main();
