#!/usr/bin/env -S deno run --allow-read --allow-run --allow-write

import { Command } from "@cliffy/command";
import * as gba from "../common/gba/gba.ts";
import type { addr } from "../common/gba/gba.ts";
import * as path from "@std/path";
import * as MFT from "../encoding/mft/mft.ts";
import * as GAS from "../encoding/gas/gas.ts";
import * as CollisionMap from "../encoding/collisionmap/collisionmap.ts";

const filename = path.basename(import.meta.filename ?? "unknown.ts");
const indent = "  ";

const ID = 0xAC2C;

// ./tools/dumper/mft_bgp.ts ./baserom.gba
const main = () => {
  new Command()
    .name("collisionmap.ts")
    .description("Dump Boktai2 CollisionMaps")
    .argument("<rom:string>", "Path to a GBA ROM file.")
    .argument("<output:string>", "CollisionMap output directory.")
    .option("-d, --dry-run", "stdout only, do not write files.")
    .action((opts, romPath, outDir) => {
      const rom = new DataView((Deno.readFileSync(romPath)).buffer);
      const hdr = MFT.getFSEntry(rom, ID);
      if (hdr.end == null) throw new Error("Invalid MFT header: end is null");
      const dir = MFT.ParseDirectory(rom, hdr.ptr);

      console.log(`@ Generated by tools/dumper/${filename}\n@ Do not edit this file manually.\n`);
      console.log(GAS.IncludeMacro + "\n");
      console.log(GAS.Align4);
      console.log(GAS.Rodata + "\n");

      console.log(GAS.dumpGlobalSymbol("gCollisionMapsDirectory") + ` @ 0x${gba.toHex32(dir.addr)}`);
      console.log(MFT.StringifyDirectory(dir, indent));
      console.log(`@ Files`);

      for (let i = 0; i < dir.entryNum; i++) {
        const start: addr = dir.addr + dir.fileOffsets[i];
        const end: addr = ((i + 1) < dir.entryNum) ? dir.addr + dir.fileOffsets[i + 1] : hdr.end;
        const magic = gba.getU32(rom, start);

        let data = new Uint8Array<ArrayBufferLike>(rom.buffer, start - gba.BASE, end - start);
        const isCompressed = magic !== CollisionMap.MAGIC; // LZ77 compressed
        if (isCompressed) {
          const decompressedSize = gba.getU32(rom, start) >> 8;
          data = gba.decompressLZ77(data);
          if (data.length !== decompressedSize) {
            throw new Error(`Decompressed size mismatch: expected ${decompressedSize}, got ${data.length}`);
          }
        }

        const fileID = dir.ids[i];
        const filename = `${gba.toHex16(fileID)}.bin`;
        const filePath = path.join(outDir, filename);
        if (!opts.dryRun) {
          Deno.writeFileSync(filePath, data);
        }

        console.log(`CollisionMap_${gba.toHex16(fileID)}:` + ` @ 0x${gba.toHex32(start)}, index: ${i}`);
        const incbinPath = `${filePath}${isCompressed ? ".lz" : ""}`;
        const output = `.incbin "${incbinPath}"`;
        console.log(indent + output);
      }
    })
    .parse(Deno.args);
};

if (import.meta.main) main();
