#!/usr/bin/env -S deno run --allow-read --allow-run --allow-write

import { Command } from "@cliffy/command";
import * as gba from "../common/gba/gba.ts";
import type { addr } from "../common/gba/gba.ts";
import { fmtJascPlttRGB555 } from "../encoding/jascpal.ts";
import * as path from "@std/path";
import * as MFT from "../encoding/mft/mft.ts";
import * as GAS from "../encoding/gas/gas.ts";

const filename = path.basename(import.meta.filename ?? "unknown.ts");
const indent = "  ";

// ./tools/dumper/mft_bgp.ts ./baserom.gba
const main = () => {
  new Command()
    .name("mft_bgp.ts")
    .description("Dump Boktai2 BG Palettes")
    .argument("<rom:string>", "Path to a GBA ROM file.")
    .argument("<output:string>", "JASC palette output directory.")
    .option("-d, --dry-run", "stdout only, do not write JASC palette files.")
    .action((opts, romPath, outDir) => {
      const rom = new DataView((Deno.readFileSync(romPath)).buffer);
      const hdr = MFT.getFSEntry(rom, 0xD710);
      if (hdr.end == null) throw new Error("Invalid MFT header: end is null");
      const dir = MFT.ParseDirectory(rom, hdr.ptr);
      const [starts, ends]: [addr[], addr[]] = [[], []];

      for (let i = 0; i < dir.entryNum; i++) {
        const start: addr = dir.addr + dir.fileOffsets[i];
        const end: addr = ((i + 1) < dir.entryNum) ? dir.addr + dir.fileOffsets[i + 1] : hdr.end;
        const size: number = end - start;
        if (size !== (20 + (2 * 256))) throw new Error(`Invalid entry ${i} at 0x${gba.toHex32(start)} with size ${size}`);
        starts.push(start);
        ends.push(end);
      }

      if (!opts.dryRun) Deno.mkdirSync(outDir, { recursive: true });

      console.log(`@ Generated by tools/dumper/${filename}\n@ Do not edit this file manually.\n`);
      console.log(GAS.IncludeMacro + "\n");
      console.log(GAS.Align4);
      console.log(GAS.Rodata + "\n");

      console.log(GAS.dumpGlobalSymbol("gPlttDirectory") + ` @ 0x${gba.toHex32(dir.addr)}`);
      console.log(MFT.StringifyDirectory(dir, indent));
      console.log(`@ Files`);

      for (let i = 0; i < dir.entryNum; i++) {
        const fileID = dir.ids[i];
        const jascPalPath = path.join(outDir, `${gba.toHex16(fileID)}.pal`);
        const gbapalPath = path.join(outDir, `${gba.toHex16(fileID)}.gbapal`);
        console.log(`BGP_${gba.toHex16(fileID)}: @ 0x${gba.toHex32(starts[i])}, index: ${i}`);

        const h = gba.copyBytes(rom, starts[i], 20);
        if (!opts.dryRun) {
          const pltt = new Uint16Array(rom.buffer, starts[i] + 20 - gba.BASE, 256);
          const jascPal = fmtJascPlttRGB555(pltt) + "\n";
          Deno.writeTextFileSync(jascPalPath, jascPal);
        }
        const output = GAS.dumpU8array(h, indent, 20) + indent + `.incbin "${gbapalPath}"`;
        console.log(output);
      }
    })
    .parse(Deno.args);
};

if (import.meta.main) main();
