#!/usr/bin/env -S deno run --allow-read

import { Command } from "@cliffy/command";
import * as gba from "../common/gba/gba.ts";
import { parseSymbolFile } from "../common/symbol.ts";
import { getSubroutineTable } from "../parser/script.ts";

// ./tools/dumper/subroutine_table.ts ./baserom.gba > data/subroutine.inc
const main = () => {
  new Command()
    .name("subroutine_table.ts")
    .description("Dump Boktai2 gSubroutineTable")
    .argument("<rom:string>", "Path to a GBA ROM file.")
    .action((_, romPath) => {
      const rom = new DataView((Deno.readFileSync(romPath)).buffer);
      const tbl = getSubroutineTable(rom);
      const syms = parseSymbolFile();

      console.log(`@ Generated by tools/dumper/subroutine_table.ts\n@ Do not edit this file manually.\n`);

      let result = ".global gSubroutineTable\ngSubroutineTable:\n";
      for (const entry of tbl) {
        const addr = entry.func;
        const sym = syms.find((s) => s.offset === addr);
        const name = (sym && sym.name) ? sym.name : `0x${gba.toHex32(addr)}`;
        result += `\t.4byte 0x${gba.toHex16(entry.id)}, ${name}\n`;
      }
      console.log(result);
    })
    .parse(Deno.args);
};

main();
