SpriteSetFile5: @ 0x08B891C4
	.2byte 725 @ palStart
	.2byte 83 @ metaspriteCount
	.2byte 10 @ unk1Count
	.2byte 281 @ subspriteCount
	.2byte 60 @ unk2Count
	.2byte 512 @ tileCount
	.4byte 0x00000020, 0x0000069C, 0x000006EC, 0x00000FB4, 0x000010A4
	@ Metasprites
		.2byte 0x3192, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x0 @ subspriteOffset
		.2byte 0x3193, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x8 @ subspriteOffset
		.2byte 0x3194, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x10 @ subspriteOffset
		.2byte 0x3195, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x18 @ subspriteOffset
		.2byte 0x3196, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x20 @ subspriteOffset
		.2byte 0x3197, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x28 @ subspriteOffset
		.2byte 0x3198, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x30 @ subspriteOffset
		.2byte 0x3199, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x38 @ subspriteOffset
		.2byte 0x319A, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x40 @ subspriteOffset
		.2byte 0x319B, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x48 @ subspriteOffset
		.2byte 0x1992, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x50 @ subspriteOffset
		.2byte 0x1993, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x58 @ subspriteOffset
		.2byte 0x1994, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x60 @ subspriteOffset
		.2byte 0x1995, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x68 @ subspriteOffset
		.2byte 0x1996, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x70 @ subspriteOffset
		.2byte 0x1997, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x78 @ subspriteOffset
		.2byte 0x1998, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x80 @ subspriteOffset
		.2byte 0x1999, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x88 @ subspriteOffset
		.2byte 0x199A, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x90 @ subspriteOffset
		.2byte 0x199B, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x98 @ subspriteOffset
		.2byte 0x4A90, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0xA0 @ subspriteOffset
		.2byte 0x6298, 0x0001, 0x0000, 0x0000, 0xFFFC, 0x0000, 0x001C, 0x002C
		.4byte 0xA8 @ subspriteOffset
		.2byte 0x6299, 0x0001, 0x0000, 0x0000, 0xFFFC, 0x0000, 0x001C, 0x002C
		.4byte 0xB0 @ subspriteOffset
		.2byte 0x629A, 0x0001, 0x0000, 0x0000, 0xFFFC, 0x0000, 0x001C, 0x002C
		.4byte 0xB8 @ subspriteOffset
		.2byte 0x629B, 0x0001, 0x0000, 0x0000, 0xFFFC, 0x0000, 0x001C, 0x002C
		.4byte 0xC0 @ subspriteOffset
		.2byte 0x62B8, 0x0003, 0x0000, 0x0000, 0x0000, 0x0000, 0x00E4, 0x005C
		.4byte 0xC8 @ subspriteOffset
		.2byte 0x62B9, 0x0003, 0x0000, 0x0000, 0x0000, 0x0000, 0x00E4, 0x005C
		.4byte 0xE0 @ subspriteOffset
		.2byte 0x62BA, 0x0003, 0x0000, 0x0000, 0x0000, 0x0000, 0x00E4, 0x005C
		.4byte 0xF8 @ subspriteOffset
		.2byte 0x62BB, 0x0003, 0x0000, 0x0000, 0x0000, 0x0000, 0x00E4, 0x005C
		.4byte 0x110 @ subspriteOffset
		.2byte 0x62D8, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00DC, 0x006C
		.4byte 0x128 @ subspriteOffset
		.2byte 0x62D9, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00DC, 0x006C
		.4byte 0x138 @ subspriteOffset
		.2byte 0x62DA, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00DC, 0x006C
		.4byte 0x148 @ subspriteOffset
		.2byte 0x62DB, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00DC, 0x006C
		.4byte 0x158 @ subspriteOffset
		.2byte 0x8CF9, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A0, 0x0028
		.4byte 0x168 @ subspriteOffset
		.2byte 0x8CFA, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A0, 0x0028
		.4byte 0x170 @ subspriteOffset
		.2byte 0x8CFB, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A0, 0x0028
		.4byte 0x178 @ subspriteOffset
		.2byte 0x8CFC, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A0, 0x0028
		.4byte 0x180 @ subspriteOffset
		.2byte 0x7F3E, 0x0007, 0x0000, 0x0000, 0xFFF0, 0x0000, 0x00E0, 0x0050
		.4byte 0x188 @ subspriteOffset
		.2byte 0x7F3F, 0x0007, 0x0000, 0x0000, 0xFFF0, 0x0000, 0x00E0, 0x0050
		.4byte 0x1C0 @ subspriteOffset
		.2byte 0x7F40, 0x0007, 0x0000, 0x0000, 0xFFF0, 0x0000, 0x00E0, 0x0050
		.4byte 0x1F8 @ subspriteOffset
		.2byte 0x7F41, 0x0007, 0x0000, 0x0000, 0xFFF0, 0x0000, 0x00E0, 0x0050
		.4byte 0x230 @ subspriteOffset
		.2byte 0x1056, 0x0009, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C8, 0x0040
		.4byte 0x268 @ subspriteOffset
		.2byte 0x1057, 0x0009, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C8, 0x0040
		.4byte 0x2B0 @ subspriteOffset
		.2byte 0x1058, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C8, 0x0040
		.4byte 0x2F8 @ subspriteOffset
		.2byte 0x1059, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C8, 0x0040
		.4byte 0x338 @ subspriteOffset
		.2byte 0x105A, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C8, 0x0040
		.4byte 0x378 @ subspriteOffset
		.2byte 0x105B, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C8, 0x0040
		.4byte 0x3B8 @ subspriteOffset
		.2byte 0x105C, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C8, 0x0040
		.4byte 0x3F8 @ subspriteOffset
		.2byte 0x105D, 0x0009, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C8, 0x0040
		.4byte 0x438 @ subspriteOffset
		.2byte 0x105E, 0x0009, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C8, 0x0040
		.4byte 0x480 @ subspriteOffset
		.2byte 0x1075, 0x0009, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C8, 0x0040
		.4byte 0x4C8 @ subspriteOffset
		.2byte 0x1076, 0x0006, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C8, 0x0040
		.4byte 0x510 @ subspriteOffset
		.2byte 0x1077, 0x0009, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C8, 0x0040
		.4byte 0x540 @ subspriteOffset
		.2byte 0x1078, 0x0009, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C8, 0x0040
		.4byte 0x588 @ subspriteOffset
		.2byte 0xC350, 0x0003, 0x0000, 0x0000, 0x0000, 0x0000, 0x0058, 0x0048
		.4byte 0x5D0 @ subspriteOffset
		.2byte 0xC351, 0x0003, 0x0000, 0x0000, 0x0000, 0x0000, 0x0058, 0x0048
		.4byte 0x5E8 @ subspriteOffset
		.2byte 0xC352, 0x0003, 0x0000, 0x0000, 0x0000, 0x0000, 0x0058, 0x0048
		.4byte 0x600 @ subspriteOffset
		.2byte 0xC353, 0x0003, 0x0000, 0x0000, 0x0000, 0x0000, 0x0058, 0x0048
		.4byte 0x618 @ subspriteOffset
		.2byte 0xC370, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0088, 0x0058
		.4byte 0x630 @ subspriteOffset
		.2byte 0xC371, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0088, 0x0058
		.4byte 0x638 @ subspriteOffset
		.2byte 0xC372, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0088, 0x0058
		.4byte 0x640 @ subspriteOffset
		.2byte 0xC373, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0088, 0x0058
		.4byte 0x648 @ subspriteOffset
		.2byte 0x2160, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A8, 0x0058
		.4byte 0x650 @ subspriteOffset
		.2byte 0xC078, 0x0008, 0x0000, 0x0000, 0xFFE0, 0xFFF8, 0x00F0, 0x0038
		.4byte 0x658 @ subspriteOffset
		.2byte 0xC079, 0x0008, 0x0000, 0x0000, 0xFFE0, 0xFFF8, 0x00F0, 0x0038
		.4byte 0x698 @ subspriteOffset
		.2byte 0xC07A, 0x0008, 0x0000, 0x0000, 0xFFE0, 0xFFF8, 0x00F0, 0x0038
		.4byte 0x6D8 @ subspriteOffset
		.2byte 0xC07B, 0x0008, 0x0000, 0x0000, 0xFFE0, 0xFFF8, 0x00F0, 0x0038
		.4byte 0x718 @ subspriteOffset
		.2byte 0xB07B, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00DF, 0x0058
		.4byte 0x758 @ subspriteOffset
		.2byte 0xB07C, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00DF, 0x0070
		.4byte 0x768 @ subspriteOffset
		.2byte 0xC71F, 0x0004, 0x0000, 0x0000, 0x0000, 0x0000, 0x0097, 0x0090
		.4byte 0x778 @ subspriteOffset
		.2byte 0xC8AD, 0x0004, 0x0000, 0x0000, 0x0000, 0x0000, 0x0080, 0x00B0
		.4byte 0x798 @ subspriteOffset
		.2byte 0x5B8E, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0020, 0x0030
		.4byte 0x7B8 @ subspriteOffset
		.2byte 0x5B8F, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0020, 0x0030
		.4byte 0x7C0 @ subspriteOffset
		.2byte 0x5B90, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0020, 0x0030
		.4byte 0x7C8 @ subspriteOffset
		.2byte 0x5B91, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0020, 0x0030
		.4byte 0x7D0 @ subspriteOffset
		.2byte 0x987C, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00E0, 0x0028
		.4byte 0x7D8 @ subspriteOffset
		.2byte 0x987D, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00E0, 0x0048
		.4byte 0x7E8 @ subspriteOffset
		.2byte 0x987E, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00E0, 0x0068
		.4byte 0x7F8 @ subspriteOffset
		.2byte 0x930C, 0x000C, 0x0000, 0x0000, 0xFFF0, 0x0000, 0x00E0, 0x0058
		.4byte 0x808 @ subspriteOffset
		.2byte 0x3F13, 0x0003, 0x0000, 0x0000, 0x0000, 0x0000, 0x00DF, 0x007C
		.4byte 0x868 @ subspriteOffset
		.2byte 0x3F14, 0x0003, 0x0000, 0x0000, 0x0000, 0x0000, 0x00DF, 0x007C
		.4byte 0x880 @ subspriteOffset
		.2byte 0x3F15, 0x0003, 0x0000, 0x0000, 0x0000, 0x0000, 0x00DF, 0x007C
		.4byte 0x898 @ subspriteOffset
		.2byte 0x3F16, 0x0003, 0x0000, 0x0000, 0x0000, 0x0000, 0x00DF, 0x007C
		.4byte 0x8B0 @ subspriteOffset
	@ Unk1
		.byte 0x23, 0xA6, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00
		.byte 0xF8, 0x69, 0x06, 0x00, 0x18, 0x00, 0x00, 0x00
		.byte 0xF9, 0x69, 0x06, 0x00, 0x30, 0x00, 0x00, 0x00
		.byte 0xFA, 0x69, 0x06, 0x00, 0x48, 0x00, 0x00, 0x00
		.byte 0xF8, 0x6B, 0x06, 0x00, 0x60, 0x00, 0x00, 0x00
		.byte 0x18, 0xFE, 0x06, 0x00, 0x78, 0x00, 0x00, 0x00
		.byte 0x19, 0xFE, 0x06, 0x00, 0x90, 0x00, 0x00, 0x00
		.byte 0x2C, 0xC8, 0x06, 0x00, 0xA8, 0x00, 0x00, 0x00
		.byte 0xDA, 0xEA, 0x06, 0x00, 0xC0, 0x00, 0x00, 0x00
		.byte 0xF7, 0x11, 0x06, 0x00, 0xD8, 0x00, 0x00, 0x00
	@ Subsprites
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (129 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (130 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (131 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (132 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (133 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (135 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (136 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (137 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (128 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (129 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (130 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (131 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (132 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (133 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (134 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (135 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (136 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (137 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (138 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 12, 28, (14 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 12, 28, (14 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 12, 28, (14 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 12, 28, (14 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 188, 76, (10 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 204, 76, (11 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x04 @ flip, shape
		.2byte 212, 76, (10 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 188, 76, (10 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 204, 76, (11 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x04 @ flip, shape
		.2byte 212, 76, (10 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 188, 76, (10 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 204, 76, (11 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x04 @ flip, shape
		.2byte 212, 76, (10 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 188, 76, (10 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 204, 76, (11 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x04 @ flip, shape
		.2byte 212, 76, (10 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 188, 92, (10 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x04 @ flip, shape
		.2byte 204, 92, (10 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 188, 92, (10 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x04 @ flip, shape
		.2byte 204, 92, (10 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 188, 92, (10 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x04 @ flip, shape
		.2byte 204, 92, (10 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 188, 92, (10 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x04 @ flip, shape
		.2byte 204, 92, (10 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 144, 24, (46 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 144, 24, (46 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 144, 24, (46 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 144, 24, (46 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 16, 48, (0 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 48, 48, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 80, 48, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 128, 48, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 160, 48, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 192, 48, (0 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 112, 48, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 16, 48, (0 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 48, 48, (2 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 80, 48, (2 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 128, 48, (2 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 160, 48, (2 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 192, 48, (0 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 112, 48, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 16, 48, (0 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 48, 48, (2 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 80, 48, (2 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 128, 48, (2 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 160, 48, (2 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 192, 48, (0 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 112, 48, (2 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 16, 48, (0 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 48, 48, (2 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 80, 48, (2 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 128, 48, (2 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 160, 48, (2 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 192, 48, (0 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 112, 48, (2 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 80, 32, (160 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 96, 32, (140 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 112, 32, (172 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 32, (202 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 40, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 168, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 72, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 160, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 144, 32, (174 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 80, 32, (160 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 96, 32, (140 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 112, 32, (172 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 32, (202 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 144, 32, (142 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 40, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 168, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 72, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 160, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 32, (206 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 96, 32, (200 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 80, 32, (170 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 144, 32, (174 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 40, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 168, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 72, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 160, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 32, (206 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 80, 32, (170 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 96, 32, (200 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 40, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 168, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 72, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 160, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 144, 32, (142 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 88, 32, (162 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 104, 32, (140 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 120, 32, (162 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 40, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 168, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 72, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 152, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 136, 32, (174 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 88, 32, (162 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 104, 32, (140 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 120, 32, (162 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 40, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 168, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 72, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 152, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 136, 32, (142 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 32, (204 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 144, 32, (164 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 80, 32, (170 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 96, 32, (200 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 40, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 168, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 72, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 160, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 96, 32, (168 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 112, 32, (166 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 32, (164 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 40, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 168, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 72, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 152, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 88, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 144, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 80, 32, (200 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 128, 32, (200 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 112, 32, (168 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 64, 32, (162 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 40, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 184, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 56, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 176, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 160, 32, (174 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 80, 32, (200 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 64, 32, (162 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 112, 32, (168 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 128, 32, (200 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 40, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 184, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 160, 32, (142 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 56, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 176, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 72, 32, (192 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 104, 32, (160 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 120, 32, (196 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 152, 32, (202 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 40, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 168, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 80, 32, (172 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 96, 32, (202 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 32, (164 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 112, 32, (192 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 40, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 168, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 144, 32, (174 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 72, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 160, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 80, 32, (172 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 96, 32, (202 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 32, (164 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 112, 32, (192 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 40, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 168, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 144, 32, (142 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 72, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 160, 32, (234 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 56, 56, (7 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 40, 56, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte 72, 56, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 56, 56, (7 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 40, 56, (64 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte 72, 56, (64 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 56, 56, (7 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 40, 56, (64 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte 72, 56, (64 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 56, 56, (7 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 40, 56, (64 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte 72, 56, (64 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 104, 56, (6 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 104, 56, (6 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 104, 56, (6 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 104, 56, (6 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 152, 72, (224 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 0, 24, (0 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 208, 24, (0 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 32, 24, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 64, 24, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 96, 24, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 128, 24, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 160, 24, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 192, 24, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 0, 24, (0 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 32, 24, (2 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 64, 24, (2 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 96, 24, (2 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 128, 24, (2 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 208, 24, (0 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 160, 24, (2 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 192, 24, (2 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 0, 24, (0 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 32, 24, (2 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 64, 24, (2 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 96, 24, (2 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 128, 24, (2 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 208, 24, (0 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 160, 24, (2 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 192, 24, (2 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 0, 24, (0 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 32, 24, (2 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 64, 24, (2 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 96, 24, (2 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 128, 24, (2 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 208, 24, (0 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 160, 24, (2 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 192, 24, (2 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 65, 80, (238 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 215, 80, (239 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 65, 104, (238 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 215, 104, (239 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 87, 80, (264 | 6 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 119, 80, (268 | 6 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 87, 112, (328 | 6 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 119, 112, (332 | 6 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 104, 144, (325 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 96, 112, (260 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 72, 144, (321 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 64, 112, (256 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 16, 32, (226 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 16, 32, (228 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 16, 32, (230 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 16, 32, (232 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 72, 32, (238 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 216, 32, (239 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 168, 64, (238 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 216, 64, (239 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 168, 96, (238 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 216, 96, (239 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 16, 40, (42 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 48, 40, (42 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 80, 40, (42 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 16, 56, (42 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 48, 56, (42 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 80, 56, (42 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 128, 40, (42 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 128, 56, (42 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 160, 40, (42 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 160, 56, (42 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 192, 40, (42 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 192, 56, (42 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 185, 108, (10 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 207, 108, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 200, 108, (11 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 185, 108, (10 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 207, 108, (12 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 200, 108, (11 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 185, 108, (10 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 207, 108, (12 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 200, 108, (11 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 185, 108, (10 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 207, 108, (12 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 200, 108, (11 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
	@ Unk2
		.byte 0x21, 0x00, 0x10, 0x00
		.byte 0x22, 0x00, 0x08, 0x00
		.byte 0x23, 0x00, 0x08, 0x00
		.byte 0x24, 0x00, 0x08, 0x00
		.byte 0x23, 0x00, 0x08, 0x00
		.byte 0x22, 0x00, 0x08, 0x00
		.byte 0x15, 0x00, 0x10, 0x00
		.byte 0x16, 0x00, 0x08, 0x00
		.byte 0x17, 0x00, 0x08, 0x00
		.byte 0x18, 0x00, 0x08, 0x00
		.byte 0x17, 0x00, 0x08, 0x00
		.byte 0x16, 0x00, 0x08, 0x00
		.byte 0x19, 0x00, 0x10, 0x00
		.byte 0x1A, 0x00, 0x08, 0x00
		.byte 0x1B, 0x00, 0x08, 0x00
		.byte 0x1C, 0x00, 0x08, 0x00
		.byte 0x1B, 0x00, 0x08, 0x00
		.byte 0x1A, 0x00, 0x08, 0x00
		.byte 0x1D, 0x00, 0x10, 0x00
		.byte 0x1E, 0x00, 0x08, 0x00
		.byte 0x1F, 0x00, 0x08, 0x00
		.byte 0x20, 0x00, 0x08, 0x00
		.byte 0x1F, 0x00, 0x08, 0x00
		.byte 0x1E, 0x00, 0x08, 0x00
		.byte 0x25, 0x00, 0x10, 0x00
		.byte 0x26, 0x00, 0x08, 0x00
		.byte 0x27, 0x00, 0x08, 0x00
		.byte 0x28, 0x00, 0x08, 0x00
		.byte 0x27, 0x00, 0x08, 0x00
		.byte 0x26, 0x00, 0x08, 0x00
		.byte 0x36, 0x00, 0x10, 0x00
		.byte 0x37, 0x00, 0x08, 0x00
		.byte 0x38, 0x00, 0x08, 0x00
		.byte 0x39, 0x00, 0x08, 0x00
		.byte 0x38, 0x00, 0x08, 0x00
		.byte 0x37, 0x00, 0x08, 0x00
		.byte 0x3A, 0x00, 0x10, 0x00
		.byte 0x3B, 0x00, 0x08, 0x00
		.byte 0x3C, 0x00, 0x08, 0x00
		.byte 0x3D, 0x00, 0x08, 0x00
		.byte 0x3C, 0x00, 0x08, 0x00
		.byte 0x3B, 0x00, 0x08, 0x00
		.byte 0x3F, 0x00, 0x10, 0x00
		.byte 0x40, 0x00, 0x08, 0x00
		.byte 0x41, 0x00, 0x08, 0x00
		.byte 0x42, 0x00, 0x08, 0x00
		.byte 0x41, 0x00, 0x08, 0x00
		.byte 0x40, 0x00, 0x08, 0x00
		.byte 0x47, 0x00, 0x06, 0x00
		.byte 0x48, 0x00, 0x05, 0x00
		.byte 0x49, 0x00, 0x04, 0x00
		.byte 0x4A, 0x00, 0x03, 0x00
		.byte 0x49, 0x00, 0x04, 0x00
		.byte 0x48, 0x00, 0x05, 0x00
		.byte 0x4F, 0x00, 0x10, 0x00
		.byte 0x50, 0x00, 0x08, 0x00
		.byte 0x51, 0x00, 0x08, 0x00
		.byte 0x52, 0x00, 0x08, 0x00
		.byte 0x51, 0x00, 0x08, 0x00
		.byte 0x50, 0x00, 0x08, 0x00
	@ Tiles
		.incbin "data/spriteset/42E2.4bpp"
