SpriteSetFile38: @ 0x08CB46A4
	.2byte 746 @ palStart
	.2byte 39 @ metaspriteCount
	.2byte 0 @ unk1Count
	.2byte 144 @ subspriteCount
	.2byte 0 @ unk2Count
	.2byte 256 @ tileCount
	.4byte 0x00000020, 0x0000032C, 0x0000032C, 0x000007AC, 0x000007AC
	@ Metasprites
		.2byte 0xEF1B, 0x0004, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B8, 0x0058
		.4byte 0x0 @ subspriteOffset
		.2byte 0xB6C1, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x0098, 0x0088
		.4byte 0x20 @ subspriteOffset
		.2byte 0x2B78, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0078, 0x0070
		.4byte 0x30 @ subspriteOffset
		.2byte 0x2B79, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0078, 0x0070
		.4byte 0x38 @ subspriteOffset
		.2byte 0x2B7A, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0078, 0x0070
		.4byte 0x40 @ subspriteOffset
		.2byte 0x2B7B, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0078, 0x0070
		.4byte 0x48 @ subspriteOffset
		.2byte 0x2B7C, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0078, 0x0070
		.4byte 0x50 @ subspriteOffset
		.2byte 0x2B7D, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0078, 0x0070
		.4byte 0x58 @ subspriteOffset
		.2byte 0x2B7E, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0078, 0x0070
		.4byte 0x60 @ subspriteOffset
		.2byte 0x2B7F, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0078, 0x0070
		.4byte 0x68 @ subspriteOffset
		.2byte 0x2B80, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0078, 0x0070
		.4byte 0x70 @ subspriteOffset
		.2byte 0x2B81, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0078, 0x0070
		.4byte 0x78 @ subspriteOffset
		.2byte 0x2F78, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0070, 0x0070
		.4byte 0x80 @ subspriteOffset
		.2byte 0x2F79, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0070, 0x0070
		.4byte 0x88 @ subspriteOffset
		.2byte 0x2F7A, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0070, 0x0070
		.4byte 0x90 @ subspriteOffset
		.2byte 0x2F7B, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0070, 0x0070
		.4byte 0x98 @ subspriteOffset
		.2byte 0x2F7C, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0070, 0x0070
		.4byte 0xA0 @ subspriteOffset
		.2byte 0x2F7D, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0070, 0x0070
		.4byte 0xA8 @ subspriteOffset
		.2byte 0x2F7E, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0070, 0x0070
		.4byte 0xB0 @ subspriteOffset
		.2byte 0x2F7F, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0070, 0x0070
		.4byte 0xB8 @ subspriteOffset
		.2byte 0x2F80, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0070, 0x0070
		.4byte 0xC0 @ subspriteOffset
		.2byte 0x2F81, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0070, 0x0070
		.4byte 0xC8 @ subspriteOffset
		.2byte 0x25FE, 0x0003, 0x0000, 0x0000, 0x0000, 0x0000, 0x0098, 0x0088
		.4byte 0xD0 @ subspriteOffset
		.2byte 0xF90A, 0x0006, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A8, 0x0058
		.4byte 0xE8 @ subspriteOffset
		.2byte 0xF90B, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B8, 0x0058
		.4byte 0x118 @ subspriteOffset
		.2byte 0xF92A, 0x0004, 0x0000, 0x0000, 0x0000, 0x0000, 0x0098, 0x0058
		.4byte 0x158 @ subspriteOffset
		.2byte 0xF94A, 0x0006, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A8, 0x0058
		.4byte 0x178 @ subspriteOffset
		.2byte 0xF96A, 0x0007, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B0, 0x0058
		.4byte 0x1A8 @ subspriteOffset
		.2byte 0xF98A, 0x0007, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B0, 0x0058
		.4byte 0x1E0 @ subspriteOffset
		.2byte 0xF9AA, 0x0009, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B0, 0x0058
		.4byte 0x218 @ subspriteOffset
		.2byte 0x0D0B, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B8, 0x0058
		.4byte 0x260 @ subspriteOffset
		.2byte 0x0D0C, 0x0009, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C0, 0x0058
		.4byte 0x2A0 @ subspriteOffset
		.2byte 0x0D0D, 0x0007, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B0, 0x0058
		.4byte 0x2E8 @ subspriteOffset
		.2byte 0x0D0E, 0x0007, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B0, 0x0058
		.4byte 0x320 @ subspriteOffset
		.2byte 0x0D0F, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B8, 0x0058
		.4byte 0x358 @ subspriteOffset
		.2byte 0x0D10, 0x000A, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C8, 0x0058
		.4byte 0x398 @ subspriteOffset
		.2byte 0x0D11, 0x0009, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C0, 0x0058
		.4byte 0x3E8 @ subspriteOffset
		.2byte 0x460B, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B8, 0x0058
		.4byte 0x430 @ subspriteOffset
		.2byte 0x4764, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x0098, 0x0088
		.4byte 0x470 @ subspriteOffset
	@ Unk1
	@ Subsprites
		.byte 0x00, 0x09 @ flip, shape
		.2byte 56, 56, (0 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 88, 56, (4 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 120, 56, (8 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 152, 56, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 88, 104, (172 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 120, 104, (140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 112, 104, (225 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 112, 104, (226 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 112, 104, (227 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 112, 104, (228 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 112, 104, (229 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 112, 104, (230 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 112, 104, (231 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 112, 104, (232 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 112, 104, (233 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 112, 104, (234 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 104, 104, (225 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 104, 104, (226 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 104, 104, (227 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 104, 104, (228 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 104, 104, (229 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 104, 104, (230 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 104, 104, (231 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 104, 104, (232 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 104, 104, (233 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 104, 104, (234 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 96, 104, (192 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 104, (196 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 144, 104, (198 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 88, 72, (100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 104, 72, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 120, 72, (42 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 136, 72, (132 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 152, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 72, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 168, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 56, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 72, 72, (74 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 88, 72, (34 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 104, 72, (162 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 120, 72, (166 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 136, 72, (132 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 152, 72, (34 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 136, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 88, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 104, 72, (98 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 120, 72, (104 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 152, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 72, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 88, 72, (70 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 104, 72, (40 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 136, 72, (70 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 120, 72, (170 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 160, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 64, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 144, 72, (36 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 80, 72, (74 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 96, 72, (42 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 112, 72, (78 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 72, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 160, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 64, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 144, 72, (46 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 80, 72, (102 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 96, 72, (34 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 112, 72, (98 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 72, (72 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 160, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 64, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 112, 72, (128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 144, 72, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 72, (160 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 96, 72, (164 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 80, 72, (96 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 96, 56, (204 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 56, (174 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 168, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 56, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 152, 72, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 72, 72, (106 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 88, 72, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 104, 72, (168 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 120, 72, (128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 136, 72, (160 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 176, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 48, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 112, 72, (168 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 72, (128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 144, 72, (160 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 160, 72, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 64, 72, (166 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 80, 72, (130 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 96, 72, (34 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 160, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 64, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 96, 72, (168 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 112, 72, (128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 72, (160 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 144, 72, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 80, 72, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 160, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 64, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 96, 72, (168 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 112, 72, (128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 72, (160 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 144, 72, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 80, 72, (76 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 168, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 56, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 104, 72, (168 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 120, 72, (128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 136, 72, (160 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 152, 72, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 72, 72, (100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 88, 72, (70 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 184, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 40, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 120, 72, (168 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 136, 72, (128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 152, 72, (160 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 168, 72, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 56, 72, (166 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 72, 72, (130 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 88, 72, (34 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 104, 72, (76 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 176, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 48, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 64, 72, (108 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 80, 72, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 96, 72, (66 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 112, 72, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 128, 72, (78 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 144, 72, (38 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 160, 72, (40 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 168, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 56, 72, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 136, 72, (160 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 152, 72, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 72, 72, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 88, 72, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 104, 72, (110 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 120, 72, (34 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 88, 104, (136 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 120, 104, (140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
	@ Unk2
	@ Tiles
		.incbin "data/spriteset/E89F.4bpp" @ 0x08CB4E50 0x08CB6E50
