SpriteSetFile12: @ 0x08BB41BC
	.2byte 341 @ palStart
	.2byte 142 @ metaspriteCount
	.2byte 58 @ unk1Count
	.2byte 1416 @ subspriteCount
	.2byte 316 @ unk2Count
	.2byte 2560 @ tileCount
	.4byte 0x00000020, 0x00000B38, 0x00000D08, 0x00003948, 0x00003E38
	@ Metasprites
		.2byte 0xA3B7, 0x0007, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x0 @ subspriteOffset
		.2byte 0x2429, 0x0008, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x38 @ subspriteOffset
		.2byte 0x242A, 0x0008, 0x0000, 0x0000, 0xFF81, 0xFFC0, 0x0011, 0x0050
		.4byte 0x78 @ subspriteOffset
		.2byte 0x8594, 0x000D, 0x0000, 0x0000, 0xFF79, 0xFFB8, 0x0011, 0x0058
		.4byte 0xB8 @ subspriteOffset
		.2byte 0x8595, 0x000D, 0x0000, 0x0000, 0xFF79, 0xFFB8, 0x0011, 0x0058
		.4byte 0x120 @ subspriteOffset
		.2byte 0x8596, 0x000C, 0x0000, 0x0000, 0xFF79, 0xFFB8, 0x0011, 0x0058
		.4byte 0x188 @ subspriteOffset
		.2byte 0x242C, 0x000A, 0x0000, 0x0000, 0xFF79, 0xFFC0, 0x0011, 0x0060
		.4byte 0x1E8 @ subspriteOffset
		.2byte 0x85F7, 0x0009, 0x0000, 0x0000, 0xFF79, 0xFFC0, 0x0011, 0x0060
		.4byte 0x238 @ subspriteOffset
		.2byte 0x242D, 0x000C, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x280 @ subspriteOffset
		.2byte 0x4136, 0x000E, 0x0000, 0x0000, 0xFFB9, 0xFFC8, 0x0011, 0x0050
		.4byte 0x2E0 @ subspriteOffset
		.2byte 0x4137, 0x000E, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0058
		.4byte 0x350 @ subspriteOffset
		.2byte 0x4138, 0x0011, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0058
		.4byte 0x3C0 @ subspriteOffset
		.2byte 0xAA73, 0x000F, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0058
		.4byte 0x448 @ subspriteOffset
		.2byte 0xAA75, 0x000F, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0058
		.4byte 0x4C0 @ subspriteOffset
		.2byte 0xA658, 0x0009, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0038
		.4byte 0x538 @ subspriteOffset
		.2byte 0xA659, 0x0009, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x580 @ subspriteOffset
		.2byte 0x18B4, 0x0009, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x5C8 @ subspriteOffset
		.2byte 0x1CB4, 0x0013, 0x0000, 0x0000, 0xFF89, 0xFFC8, 0x0011, 0x0048
		.4byte 0x610 @ subspriteOffset
		.2byte 0x20B4, 0x0015, 0x0000, 0x0000, 0xFF89, 0xFFC8, 0x0011, 0x0048
		.4byte 0x6A8 @ subspriteOffset
		.2byte 0x96F0, 0x000E, 0x0000, 0x0000, 0xFF89, 0xFFC8, 0x0011, 0x0048
		.4byte 0x750 @ subspriteOffset
		.2byte 0x16F1, 0x000B, 0x0000, 0x0000, 0xFF89, 0xFFC8, 0x0011, 0x0048
		.4byte 0x7C0 @ subspriteOffset
		.2byte 0x18AE, 0x000B, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0040
		.4byte 0x818 @ subspriteOffset
		.2byte 0x1CAE, 0x000D, 0x0000, 0x0000, 0xFF89, 0xFFC8, 0x0011, 0x0048
		.4byte 0x870 @ subspriteOffset
		.2byte 0x20AE, 0x0011, 0x0000, 0x0000, 0xFF89, 0xFFC8, 0x0011, 0x0048
		.4byte 0x8D8 @ subspriteOffset
		.2byte 0x9636, 0x000C, 0x0000, 0x0000, 0xFF89, 0xFFC8, 0x0011, 0x0048
		.4byte 0x960 @ subspriteOffset
		.2byte 0x1888, 0x000C, 0x0000, 0x0000, 0xFF81, 0xFFC0, 0x0011, 0x0050
		.4byte 0x9C0 @ subspriteOffset
		.2byte 0x1889, 0x000F, 0x0000, 0x0000, 0xFF81, 0xFFC0, 0x0011, 0x0050
		.4byte 0xA20 @ subspriteOffset
		.2byte 0x188A, 0x000F, 0x0000, 0x0000, 0xFF81, 0xFFC0, 0x0011, 0x0050
		.4byte 0xA98 @ subspriteOffset
		.2byte 0x188B, 0x000E, 0x0000, 0x0000, 0xFF81, 0xFFC0, 0x0011, 0x0050
		.4byte 0xB10 @ subspriteOffset
		.2byte 0x188C, 0x000B, 0x0000, 0x0000, 0xFF81, 0xFFC0, 0x0011, 0x0050
		.4byte 0xB80 @ subspriteOffset
		.2byte 0x16E4, 0x000B, 0x0000, 0x0000, 0xFF81, 0xFFC0, 0x0011, 0x0050
		.4byte 0xBD8 @ subspriteOffset
		.2byte 0x18B5, 0x000B, 0x0000, 0x0000, 0xFF81, 0xFFC0, 0x0011, 0x0050
		.4byte 0xC30 @ subspriteOffset
		.2byte 0x18B6, 0x000B, 0x0000, 0x0000, 0xFF81, 0xFFC0, 0x0011, 0x0050
		.4byte 0xC88 @ subspriteOffset
		.2byte 0x18B7, 0x0011, 0x0000, 0x0000, 0xFF89, 0xFFC8, 0x0011, 0x0048
		.4byte 0xCE0 @ subspriteOffset
		.2byte 0x31AF, 0x0009, 0x0000, 0x0000, 0xFFB1, 0xFFC0, 0x0011, 0x0040
		.4byte 0xD68 @ subspriteOffset
		.2byte 0x31B0, 0x0004, 0x0000, 0x0000, 0xFF91, 0xFFA0, 0x0011, 0x0030
		.4byte 0xDB0 @ subspriteOffset
		.2byte 0xB799, 0x0012, 0x0000, 0x0000, 0xFFD0, 0xFFC8, 0x0020, 0x0030
		.4byte 0xDD0 @ subspriteOffset
		.2byte 0xB79A, 0x0010, 0x0000, 0x0000, 0xFFB8, 0xFFC8, 0x0020, 0x0030
		.4byte 0xE60 @ subspriteOffset
		.2byte 0xB79B, 0x000C, 0x0000, 0x0000, 0xFFC0, 0xFFC8, 0x0020, 0x0030
		.4byte 0xEE0 @ subspriteOffset
		.2byte 0xB79C, 0x000E, 0x0000, 0x0000, 0xFFB5, 0xFFC2, 0x0023, 0x0032
		.4byte 0xF40 @ subspriteOffset
		.2byte 0x1045, 0x0006, 0x0000, 0x0000, 0xFFE5, 0xFFD6, 0x0031, 0x0030
		.4byte 0xFB0 @ subspriteOffset
		.2byte 0x1046, 0x0006, 0x0000, 0x0000, 0xFFE5, 0xFFD7, 0x0031, 0x0031
		.4byte 0xFE0 @ subspriteOffset
		.2byte 0x1047, 0x0006, 0x0000, 0x0000, 0xFFE5, 0xFFD7, 0x0031, 0x0031
		.4byte 0x1010 @ subspriteOffset
		.2byte 0x1048, 0x0005, 0x0000, 0x0000, 0xFFE5, 0xFFD7, 0x0030, 0x0022
		.4byte 0x1040 @ subspriteOffset
		.2byte 0x1049, 0x0005, 0x0000, 0x0000, 0xFFE5, 0xFFD6, 0x0030, 0x0022
		.4byte 0x1068 @ subspriteOffset
		.2byte 0x104A, 0x0005, 0x0000, 0x0000, 0xFFE5, 0xFFD6, 0x0031, 0x0022
		.4byte 0x1090 @ subspriteOffset
		.2byte 0x104B, 0x0006, 0x0000, 0x0000, 0xFFE5, 0xFFD7, 0x0031, 0x0031
		.4byte 0x10B8 @ subspriteOffset
		.2byte 0x104C, 0x0006, 0x0000, 0x0000, 0xFFE5, 0xFFD7, 0x0031, 0x0031
		.4byte 0x10E8 @ subspriteOffset
		.2byte 0x104D, 0x0006, 0x0000, 0x0000, 0xFFF2, 0xFFD5, 0x004A, 0x0025
		.4byte 0x1118 @ subspriteOffset
		.2byte 0x104E, 0x0006, 0x0000, 0x0000, 0xFFE8, 0xFFD9, 0x0034, 0x0033
		.4byte 0x1148 @ subspriteOffset
		.2byte 0x76DB, 0x0002, 0x0000, 0x0000, 0xFFB8, 0xFFC8, 0x0020, 0x0030
		.4byte 0x1178 @ subspriteOffset
		.2byte 0x76DC, 0x0002, 0x0000, 0x0000, 0xFFB8, 0xFFC8, 0x0020, 0x0030
		.4byte 0x1188 @ subspriteOffset
		.2byte 0x76DD, 0x0002, 0x0000, 0x0000, 0xFFB8, 0xFFC8, 0x0020, 0x0030
		.4byte 0x1198 @ subspriteOffset
		.2byte 0x76DE, 0x0002, 0x0000, 0x0000, 0xFFB8, 0xFFBE, 0x001D, 0x0026
		.4byte 0x11A8 @ subspriteOffset
		.2byte 0x76DF, 0x0002, 0x0000, 0x0000, 0xFFB8, 0xFFBE, 0x001D, 0x0026
		.4byte 0x11B8 @ subspriteOffset
		.2byte 0x76E0, 0x0002, 0x0000, 0x0000, 0xFFB8, 0xFFBE, 0x001D, 0x0026
		.4byte 0x11C8 @ subspriteOffset
		.2byte 0x76E1, 0x0002, 0x0000, 0x0000, 0xFFB5, 0xFFC5, 0x0023, 0x0033
		.4byte 0x11D8 @ subspriteOffset
		.2byte 0x6262, 0x0007, 0x0000, 0x0000, 0xFFA8, 0xFFAA, 0x0000, 0x0000
		.4byte 0x11E8 @ subspriteOffset
		.2byte 0x6263, 0x0006, 0x0000, 0x0000, 0xFFA9, 0xFFA9, 0x0001, 0x0000
		.4byte 0x1220 @ subspriteOffset
		.2byte 0x6264, 0x0007, 0x0000, 0x0000, 0xFFA9, 0xFFA8, 0x0001, 0x0000
		.4byte 0x1250 @ subspriteOffset
		.2byte 0x6265, 0x0007, 0x0000, 0x0000, 0xFFA8, 0xFFA8, 0x0000, 0x0000
		.4byte 0x1288 @ subspriteOffset
		.2byte 0x6266, 0x0006, 0x0000, 0x0000, 0xFFA7, 0xFFA9, 0x0000, 0x0000
		.4byte 0x12C0 @ subspriteOffset
		.2byte 0x6267, 0x0006, 0x0000, 0x0000, 0xFFA6, 0xFFAA, 0x0000, 0x0000
		.4byte 0x12F0 @ subspriteOffset
		.2byte 0x6268, 0x0007, 0x0000, 0x0000, 0xFFA6, 0xFFAB, 0x0000, 0x0000
		.4byte 0x1320 @ subspriteOffset
		.2byte 0x6269, 0x0007, 0x0000, 0x0000, 0xFFA7, 0xFFAB, 0x0000, 0x0000
		.4byte 0x1358 @ subspriteOffset
		.2byte 0x626A, 0x0004, 0x0000, 0x0000, 0xFFC6, 0xFFA2, 0x0006, 0x0000
		.4byte 0x1390 @ subspriteOffset
		.2byte 0x626B, 0x0007, 0x0000, 0x0000, 0xFFA5, 0xFFA7, 0x0000, 0x0000
		.4byte 0x13B0 @ subspriteOffset
		.2byte 0xA793, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF0, 0x0018, 0x0010
		.4byte 0x13E8 @ subspriteOffset
		.2byte 0xA794, 0x0001, 0x0000, 0x0000, 0xFFE9, 0xFFE2, 0x0029, 0x0022
		.4byte 0x13F0 @ subspriteOffset
		.2byte 0xA795, 0x0005, 0x0000, 0x0000, 0xFFF8, 0xFFF0, 0x0030, 0x0018
		.4byte 0x13F8 @ subspriteOffset
		.2byte 0xA796, 0x0006, 0x0000, 0x0000, 0xFFFA, 0xFFF0, 0x0032, 0x0028
		.4byte 0x1420 @ subspriteOffset
		.2byte 0xA797, 0x0004, 0x0000, 0x0000, 0xFFF0, 0xFFE8, 0x0030, 0x0028
		.4byte 0x1450 @ subspriteOffset
		.2byte 0xA798, 0x0008, 0x0000, 0x0000, 0xFFE8, 0xFFE0, 0x0038, 0x0030
		.4byte 0x1470 @ subspriteOffset
		.2byte 0x9A5F, 0x0008, 0x0000, 0x0000, 0xFFE8, 0xFFE0, 0x0037, 0x0031
		.4byte 0x14B0 @ subspriteOffset
		.2byte 0x9C5F, 0x0007, 0x0000, 0x0000, 0xFFDD, 0xFFF2, 0x0021, 0x0033
		.4byte 0x14F0 @ subspriteOffset
		.2byte 0x9E5F, 0x0009, 0x0000, 0x0000, 0xFFD4, 0xFFF1, 0x0012, 0x0029
		.4byte 0x1528 @ subspriteOffset
		.2byte 0xA05F, 0x0009, 0x0000, 0x0000, 0xFFC6, 0xFFEB, 0x000F, 0x0020
		.4byte 0x1570 @ subspriteOffset
		.2byte 0xF05F, 0x0009, 0x0000, 0x0000, 0xFFC6, 0xFFE8, 0x000F, 0x001E
		.4byte 0x15B8 @ subspriteOffset
		.2byte 0xF25F, 0x0007, 0x0000, 0x0000, 0xFFCB, 0xFFF0, 0x0013, 0x003F
		.4byte 0x1600 @ subspriteOffset
		.2byte 0xF45F, 0x0007, 0x0000, 0x0000, 0xFFF5, 0xFFF2, 0x001D, 0x0052
		.4byte 0x1638 @ subspriteOffset
		.2byte 0xF65F, 0x0007, 0x0000, 0x0000, 0x0000, 0xFFEF, 0x003A, 0x004C
		.4byte 0x1670 @ subspriteOffset
		.2byte 0xF85F, 0x0007, 0x0000, 0x0000, 0x0000, 0xFFEE, 0x003D, 0x0049
		.4byte 0x16A8 @ subspriteOffset
		.2byte 0xFA5F, 0x0007, 0x0000, 0x0000, 0x0000, 0xFFEE, 0x003D, 0x0047
		.4byte 0x16E0 @ subspriteOffset
		.2byte 0xF0F5, 0x0009, 0x0000, 0x0000, 0xFFF5, 0xFFED, 0x0027, 0x0041
		.4byte 0x1718 @ subspriteOffset
		.2byte 0xF2F5, 0x0008, 0x0000, 0x0000, 0xFFE9, 0xFFDF, 0x0032, 0x0030
		.4byte 0x1760 @ subspriteOffset
		.2byte 0x1B3B, 0x0007, 0x0000, 0x0000, 0xFFE4, 0xFFE0, 0x0038, 0x0030
		.4byte 0x17A0 @ subspriteOffset
		.2byte 0x1D3B, 0x0008, 0x0000, 0x0000, 0xFFD8, 0xFFE0, 0x0038, 0x0030
		.4byte 0x17D8 @ subspriteOffset
		.2byte 0x3F4F, 0x0008, 0x0000, 0x0000, 0xFFC4, 0xFFE0, 0x0038, 0x0031
		.4byte 0x1818 @ subspriteOffset
		.2byte 0x3F50, 0x0008, 0x0000, 0x0000, 0xFFC4, 0xFFE0, 0x0038, 0x0031
		.4byte 0x1858 @ subspriteOffset
		.2byte 0x3F51, 0x0008, 0x0000, 0x0000, 0xFFC4, 0xFFE0, 0x0038, 0x0031
		.4byte 0x1898 @ subspriteOffset
		.2byte 0x39F9, 0x0008, 0x0000, 0x0000, 0xFFC2, 0xFFE0, 0x0037, 0x0031
		.4byte 0x18D8 @ subspriteOffset
		.2byte 0x3A03, 0x0007, 0x0000, 0x0000, 0xFFAC, 0xFFE2, 0x0021, 0x0033
		.4byte 0x1918 @ subspriteOffset
		.2byte 0x7A03, 0x000F, 0x0000, 0x0000, 0xFFB9, 0xFFDD, 0x0012, 0x0029
		.4byte 0x1950 @ subspriteOffset
		.2byte 0xBA03, 0x000B, 0x0000, 0x0000, 0xFFC3, 0xFFC3, 0x000F, 0x0020
		.4byte 0x19C8 @ subspriteOffset
		.2byte 0xFA03, 0x000B, 0x0000, 0x0000, 0xFFC4, 0xFFC1, 0x000F, 0x001E
		.4byte 0x1A20 @ subspriteOffset
		.2byte 0x8D1B, 0x000A, 0x0000, 0x0000, 0xFFD9, 0xFFE0, 0x0038, 0x0031
		.4byte 0x1A78 @ subspriteOffset
		.2byte 0x8D1C, 0x000A, 0x0000, 0x0000, 0xFFD9, 0xFFE0, 0x0038, 0x0031
		.4byte 0x1AC8 @ subspriteOffset
		.2byte 0x8D1D, 0x000A, 0x0000, 0x0000, 0xFFD9, 0xFFE0, 0x0038, 0x0031
		.4byte 0x1B18 @ subspriteOffset
		.2byte 0xDC67, 0x000A, 0x0000, 0x0000, 0xFFD7, 0xFFE0, 0x0037, 0x0031
		.4byte 0x1B68 @ subspriteOffset
		.2byte 0xDC7B, 0x0009, 0x0000, 0x0000, 0xFFC1, 0xFFE9, 0x0021, 0x0033
		.4byte 0x1BB8 @ subspriteOffset
		.2byte 0x5C7C, 0x000F, 0x0000, 0x0000, 0xFFB9, 0xFFDC, 0x0012, 0x0029
		.4byte 0x1C00 @ subspriteOffset
		.2byte 0xDC7C, 0x000E, 0x0000, 0x0000, 0xFFC3, 0xFFC8, 0x000F, 0x0020
		.4byte 0x1C78 @ subspriteOffset
		.2byte 0x5C7D, 0x000E, 0x0000, 0x0000, 0xFFC4, 0xFFC6, 0x000F, 0x001E
		.4byte 0x1CE8 @ subspriteOffset
		.2byte 0x938E, 0x000A, 0x0000, 0x0000, 0xFFD2, 0xFFE0, 0x0038, 0x0031
		.4byte 0x1D58 @ subspriteOffset
		.2byte 0x938F, 0x000A, 0x0000, 0x0000, 0xFFD2, 0xFFE0, 0x0038, 0x0031
		.4byte 0x1DA8 @ subspriteOffset
		.2byte 0x9390, 0x000A, 0x0000, 0x0000, 0xFFD2, 0xFFE0, 0x0038, 0x0031
		.4byte 0x1DF8 @ subspriteOffset
		.2byte 0x349B, 0x000A, 0x0000, 0x0000, 0xFFD3, 0xFFE0, 0x0038, 0x0030
		.4byte 0x1E48 @ subspriteOffset
		.2byte 0x34A5, 0x0009, 0x0000, 0x0000, 0xFFDF, 0xFFD1, 0x0039, 0x002B
		.4byte 0x1E98 @ subspriteOffset
		.2byte 0x74A5, 0x000E, 0x0000, 0x0000, 0xFFE8, 0xFFB5, 0x005E, 0x001A
		.4byte 0x1EE0 @ subspriteOffset
		.2byte 0xB4A5, 0x000E, 0x0000, 0x0000, 0xFFE9, 0xFFB7, 0x005F, 0x001A
		.4byte 0x1F50 @ subspriteOffset
		.2byte 0xF4A5, 0x000B, 0x0000, 0x0000, 0xFFF8, 0xFFAC, 0x0046, 0x0013
		.4byte 0x1FC0 @ subspriteOffset
		.2byte 0x34A6, 0x0008, 0x0000, 0x0000, 0xFFBD, 0xFFCB, 0x0014, 0x0028
		.4byte 0x2018 @ subspriteOffset
		.2byte 0x74A6, 0x000D, 0x0000, 0x0000, 0xFFA9, 0xFFF1, 0x0010, 0x0073
		.4byte 0x2058 @ subspriteOffset
		.2byte 0x4765, 0x000D, 0x0000, 0x0000, 0xFFA9, 0xFFF1, 0x0010, 0x0071
		.4byte 0x20C0 @ subspriteOffset
		.2byte 0x4AAD, 0x000D, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0040
		.4byte 0x2128 @ subspriteOffset
		.2byte 0x4AAE, 0x0010, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x2190 @ subspriteOffset
		.2byte 0x4AAF, 0x0011, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x2210 @ subspriteOffset
		.2byte 0x4AB0, 0x0011, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x2298 @ subspriteOffset
		.2byte 0x8A78, 0x000B, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x2320 @ subspriteOffset
		.2byte 0x8A79, 0x000B, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x2378 @ subspriteOffset
		.2byte 0x8A7A, 0x000C, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x23D0 @ subspriteOffset
		.2byte 0x8A7B, 0x000D, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x2430 @ subspriteOffset
		.2byte 0x8A7C, 0x000D, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x2498 @ subspriteOffset
		.2byte 0x8A7D, 0x000D, 0x0000, 0x0000, 0xFF9D, 0xFFC8, 0x0011, 0x0050
		.4byte 0x2500 @ subspriteOffset
		.2byte 0x8A7E, 0x000D, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x2568 @ subspriteOffset
		.2byte 0x8A7F, 0x000D, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x25D0 @ subspriteOffset
		.2byte 0x8A80, 0x000D, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0058
		.4byte 0x2638 @ subspriteOffset
		.2byte 0x8A81, 0x000A, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x26A0 @ subspriteOffset
		.2byte 0xB2E5, 0x000F, 0x0000, 0x0000, 0xFF89, 0xFFC8, 0x0011, 0x0048
		.4byte 0x26F0 @ subspriteOffset
		.2byte 0xB5A8, 0x0004, 0x0000, 0x0000, 0xFF91, 0x0000, 0x0000, 0x0058
		.4byte 0x2768 @ subspriteOffset
		.2byte 0xBA77, 0x0004, 0x0000, 0x0000, 0xFF91, 0x0000, 0x0000, 0x0058
		.4byte 0x2788 @ subspriteOffset
		.2byte 0xB5D1, 0x0006, 0x0000, 0x0000, 0xFF91, 0x0000, 0x0000, 0x0060
		.4byte 0x27A8 @ subspriteOffset
		.2byte 0xB5D2, 0x0005, 0x0000, 0x0000, 0xFF91, 0x0000, 0x0000, 0x0070
		.4byte 0x27D8 @ subspriteOffset
		.2byte 0x52D5, 0x000D, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0040
		.4byte 0x2800 @ subspriteOffset
		.2byte 0x52F5, 0x0010, 0x0000, 0x0000, 0xFFB1, 0xFFC8, 0x0011, 0x0050
		.4byte 0x2868 @ subspriteOffset
		.2byte 0x5315, 0x000A, 0x0000, 0x0000, 0xFF89, 0xFFC8, 0x0011, 0x0048
		.4byte 0x28E8 @ subspriteOffset
		.2byte 0x5335, 0x0011, 0x0000, 0x0000, 0xFF89, 0xFFC8, 0x0011, 0x0048
		.4byte 0x2938 @ subspriteOffset
		.2byte 0x5355, 0x0010, 0x0000, 0x0000, 0xFF89, 0xFFC8, 0x0011, 0x0048
		.4byte 0x29C0 @ subspriteOffset
		.2byte 0x5375, 0x000F, 0x0000, 0x0000, 0xFF89, 0xFFC8, 0x0011, 0x0048
		.4byte 0x2A40 @ subspriteOffset
		.2byte 0x5395, 0x0011, 0x0000, 0x0000, 0xFF81, 0xFFC0, 0x0011, 0x005C
		.4byte 0x2AB8 @ subspriteOffset
		.2byte 0x53B5, 0x000F, 0x0000, 0x0000, 0xFF81, 0xFFC0, 0x0011, 0x0057
		.4byte 0x2B40 @ subspriteOffset
		.2byte 0x53D5, 0x0011, 0x0000, 0x0000, 0xFF89, 0xFFC8, 0x0011, 0x0048
		.4byte 0x2BB8 @ subspriteOffset
	@ Unk1
		.byte 0xFC, 0xCB, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00
		.byte 0x28, 0x24, 0x02, 0x00, 0x04, 0x00, 0x00, 0x00
		.byte 0x29, 0x24, 0x03, 0x00, 0x0C, 0x00, 0x00, 0x00
		.byte 0x2A, 0x24, 0x02, 0x00, 0x18, 0x00, 0x00, 0x00
		.byte 0x2B, 0x24, 0x01, 0x00, 0x20, 0x00, 0x00, 0x00
		.byte 0x8D, 0x49, 0x04, 0x00, 0x24, 0x00, 0x00, 0x00
		.byte 0xE7, 0x98, 0x04, 0x00, 0x34, 0x00, 0x00, 0x00
		.byte 0x26, 0x92, 0x02, 0x00, 0x44, 0x00, 0x00, 0x00
		.byte 0xB4, 0x18, 0x02, 0x00, 0x4C, 0x00, 0x00, 0x00
		.byte 0xB4, 0x1C, 0x04, 0x00, 0x54, 0x00, 0x00, 0x00
		.byte 0xF0, 0x16, 0x02, 0x00, 0x64, 0x00, 0x00, 0x00
		.byte 0xAE, 0x18, 0x02, 0x00, 0x6C, 0x00, 0x00, 0x00
		.byte 0xAE, 0x1C, 0x04, 0x00, 0x74, 0x00, 0x00, 0x00
		.byte 0x36, 0x16, 0x02, 0x00, 0x84, 0x00, 0x00, 0x00
		.byte 0xDC, 0x7C, 0x02, 0x00, 0x8C, 0x00, 0x00, 0x00
		.byte 0xDD, 0x7C, 0x04, 0x00, 0x94, 0x00, 0x00, 0x00
		.byte 0xDE, 0x7C, 0x02, 0x00, 0xA4, 0x00, 0x00, 0x00
		.byte 0xAF, 0x31, 0x01, 0x00, 0xAC, 0x00, 0x00, 0x00
		.byte 0xB0, 0x31, 0x01, 0x00, 0xB0, 0x00, 0x00, 0x00
		.byte 0xAD, 0x4A, 0x04, 0x00, 0xB4, 0x00, 0x00, 0x00
		.byte 0xAE, 0x4A, 0x02, 0x00, 0xC4, 0x00, 0x00, 0x00
		.byte 0xAF, 0x4A, 0x04, 0x00, 0xCC, 0x00, 0x00, 0x00
		.byte 0x1F, 0x9A, 0x0F, 0x00, 0xDC, 0x00, 0x00, 0x00
		.byte 0x99, 0xB7, 0x01, 0x00, 0x18, 0x01, 0x00, 0x00
		.byte 0x9A, 0xB7, 0x01, 0x00, 0x1C, 0x01, 0x00, 0x00
		.byte 0x9B, 0xB7, 0x01, 0x00, 0x20, 0x01, 0x00, 0x00
		.byte 0x9C, 0xB7, 0x01, 0x00, 0x24, 0x01, 0x00, 0x00
		.byte 0x45, 0x10, 0x08, 0x00, 0x28, 0x01, 0x00, 0x00
		.byte 0x46, 0x10, 0x01, 0x00, 0x48, 0x01, 0x00, 0x00
		.byte 0x47, 0x10, 0x01, 0x00, 0x4C, 0x01, 0x00, 0x00
		.byte 0xDB, 0x76, 0x04, 0x00, 0x50, 0x01, 0x00, 0x00
		.byte 0xDC, 0x76, 0x04, 0x00, 0x60, 0x01, 0x00, 0x00
		.byte 0xDD, 0x76, 0x01, 0x00, 0x70, 0x01, 0x00, 0x00
		.byte 0x62, 0x62, 0x08, 0x00, 0x74, 0x01, 0x00, 0x00
		.byte 0x63, 0x62, 0x01, 0x00, 0x94, 0x01, 0x00, 0x00
		.byte 0x64, 0x62, 0x01, 0x00, 0x98, 0x01, 0x00, 0x00
		.byte 0x59, 0x72, 0x0B, 0x00, 0x9C, 0x01, 0x00, 0x00
		.byte 0x5A, 0x72, 0x0F, 0x00, 0xC8, 0x01, 0x00, 0x00
		.byte 0x58, 0x51, 0x10, 0x00, 0x04, 0x02, 0x00, 0x00
		.byte 0x59, 0x51, 0x0F, 0x00, 0x44, 0x02, 0x00, 0x00
		.byte 0x42, 0x6C, 0x10, 0x00, 0x80, 0x02, 0x00, 0x00
		.byte 0x43, 0x6C, 0x0F, 0x00, 0xC0, 0x02, 0x00, 0x00
		.byte 0x42, 0xD9, 0x11, 0x00, 0xFC, 0x02, 0x00, 0x00
		.byte 0x43, 0xD9, 0x02, 0x00, 0x40, 0x03, 0x00, 0x00
		.byte 0x44, 0xD9, 0x11, 0x00, 0x48, 0x03, 0x00, 0x00
		.byte 0xE5, 0xB2, 0x06, 0x00, 0x8C, 0x03, 0x00, 0x00
		.byte 0xA0, 0xB5, 0x04, 0x00, 0xA4, 0x03, 0x00, 0x00
		.byte 0x97, 0xFB, 0x05, 0x00, 0xB4, 0x03, 0x00, 0x00
		.byte 0x98, 0xFB, 0x0B, 0x00, 0xC8, 0x03, 0x00, 0x00
		.byte 0x99, 0xFB, 0x0B, 0x00, 0xF4, 0x03, 0x00, 0x00
		.byte 0x9A, 0xFB, 0x09, 0x00, 0x20, 0x04, 0x00, 0x00
		.byte 0x9B, 0xFB, 0x09, 0x00, 0x44, 0x04, 0x00, 0x00
		.byte 0x9C, 0xFB, 0x06, 0x00, 0x68, 0x04, 0x00, 0x00
		.byte 0x93, 0xEA, 0x08, 0x00, 0x80, 0x04, 0x00, 0x00
		.byte 0x94, 0xEA, 0x0C, 0x00, 0xA0, 0x04, 0x00, 0x00
		.byte 0x95, 0xEA, 0x06, 0x00, 0xD0, 0x04, 0x00, 0x00
		.byte 0x78, 0x8A, 0x01, 0x00, 0xE8, 0x04, 0x00, 0x00
		.byte 0x79, 0x8A, 0x01, 0x00, 0xEC, 0x04, 0x00, 0x00
	@ Subsprites
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (688 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (752 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, 8, (676 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -15, 40, (740 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (601 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -15, 16, (605 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (665 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -63, 0, (1280 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -39, 64, (890 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -23, 8, (675 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -55, 8, (460 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -71, -8, (1408 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, 56, (1370 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 16, (1352 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 48, (1357 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 1, 8, (678 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -23, -24, (611 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 9, -24, (615 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, -16, (626 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, 16, (1688 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -7, -16, (1768 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -39, -32, (1560 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -39, 0, (1764 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 48, (1357 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 16, (1352 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, 56, (1370 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -71, -8, (1408 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, -16, (626 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 9, -24, (615 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -23, -24, (611 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 1, 8, (678 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -39, -24, (1641 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -23, -32, (1640 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -7, -16, (1580 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 8, (1612 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 48, (1357 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 16, (1352 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, 56, (1370 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -71, -8, (1408 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, -16, (626 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 9, -24, (615 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -23, -24, (611 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 1, 8, (678 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (1705 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 8, (1614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -15, -32, (1656 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -71, 0, (1632 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -7, 16, (1704 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 64, (1760 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -56, 23, (92 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -23, -24, (611 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 9, -24, (615 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, 8, (678 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -31, -16, (626 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -15, 8, (676 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -55, 8, (460 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -15, 8, (676 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -31, -16, (626 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 9, -24, (615 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, 8, (678 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -23, -24, (611 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 64, (1760 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -7, 16, (1704 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -71, 0, (1632 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -55, 8, (460 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, 8, (674 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -23, -24, (611 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 9, -24, (615 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, 8, (678 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, -16, (626 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, 16, (1450 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -47, 16, (1448 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (1012 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -55, 24, (1416 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 40, (748 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 0, (1417 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, -8, (764 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -23, -24, (611 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -23, -8, (643 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -31, -16, (626 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 9, -16, (631 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -7, 0, (661 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, 16, (694 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -39, 0, (772 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -39, 32, (836 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 48, (880 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -39, 56, (888 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -47, 8, (616 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -47, 40, (992 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -7, 16, (607 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 1, 24, (1143 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, 16, (694 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -7, 0, (661 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 9, -16, (631 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -31, -16, (626 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -23, -8, (643 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -23, -24, (611 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -39, 8, (780 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -39, 40, (844 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -47, 8, (898 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -47, 40, (993 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 56, (872 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -7, 16, (899 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, 24, (1039 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 0, (868 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, 16, (694 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -7, 0, (661 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 9, -16, (631 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -31, -16, (626 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -23, -8, (643 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -23, -24, (611 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -7, 16, (1032 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -39, 8, (768 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, 24, (1034 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -23, 0, (1025 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -39, 40, (832 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, 0, (1024 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 56, (1172 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -47, 8, (1040 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -47, 40, (1033 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -55, 32, (1041 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 48, (1073 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, 16, (694 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -7, 0, (661 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 9, -16, (631 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -31, -16, (626 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -23, -8, (643 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -23, -24, (611 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -39, 8, (876 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -39, 40, (940 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -47, 8, (972 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -47, 40, (995 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -55, 24, (994 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 56, (996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -7, 16, (973 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, 24, (669 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 0, (976 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, 16, (694 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -7, 0, (661 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 9, -16, (631 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -31, -16, (626 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -23, -8, (643 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -23, -24, (611 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -39, 8, (776 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -39, 40, (840 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -47, 8, (896 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -47, 40, (1252 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 56, (884 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -7, 16, (897 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 1, 24, (1142 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -7, 48, (1096 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 0, (864 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 24, (1128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -39, -8, (1065 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -15, 24, (1132 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -47, 16, (1112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 1, 24, (1134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, -8, (1069 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -23, -24, (1035 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 9, -16, (1055 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, -16, (1050 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (1104 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -16, (1042 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -39, 8, (1089 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -15, 16, (1108 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (1168 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -16, (1046 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 1, 16, (1110 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -23, -24, (1027 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, -24, (1031 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (752 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (688 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, 8, (676 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -15, 40, (740 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -46, 15, (1195 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -35, 2, (1166 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, -8, (642 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, 0, (658 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -55, 8, (1288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 40, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 40, (670 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 40, (750 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, 0, (251 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 28, (216 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -3, 5, (230 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -22, 13, (220 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -6, 13, (218 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -3, 21, (211 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -16, 31, (2484 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -32, 31, (2482 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -32, 47, (2514 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, 47, (2516 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, 0, (658 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, -8, (642 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, 0, (251 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 40, (750 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 40, (670 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 40, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -55, 8, (1288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -53, 15, (1193 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -36, 3, (1257 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -3, 21, (211 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -6, 13, (218 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -22, 13, (220 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -3, 5, (230 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 28, (216 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -16, 31, (2484 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -32, 31, (2482 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -32, 47, (2514 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, 47, (2516 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, 0, (658 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, -8, (642 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -55, 8, (1288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 40, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 40, (670 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 40, (750 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, 0, (251 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -28, 27, (1221 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -29, 14, (1189 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 3, (1224 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -10, 26, (1223 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, 0, (658 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, -8, (642 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -55, 8, (1288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 40, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 40, (670 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 40, (750 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, 0, (251 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, 0, (252 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, 8, (676 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (688 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -15, 40, (740 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -43, 31, (1196 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -30, 14, (1258 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 28, (1262 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 2, (1135 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -47, 48, (752 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, 0, (658 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -55, 8, (1288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 40, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 40, (670 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 40, (750 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, -8, (642 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, 0, (252 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 2, (154 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -53, 24, (2496 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -53, 16, (2480 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, 0, (658 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -55, 8, (1288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 40, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 40, (670 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 40, (750 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -29, 27, (713 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -24, 15, (741 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -10, 29, (747 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 4, (606 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, -8, (642 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, 0, (252 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 2, (154 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -53, 24, (2496 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -53, 16, (2480 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, 0, (658 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, -8, (642 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -55, 8, (1288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 40, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 40, (670 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 40, (750 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -55, 10, (546 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 2, (640 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, 0, (252 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -23, 8, (675 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -63, 0, (1280 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -39, 64, (890 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -40, 2, (681 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 2, (683 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -25, 17, (684 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -25, 49, (520 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -55, 8, (460 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -63, 0, (1280 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -39, 64, (890 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -23, 8, (675 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -40, 2, (681 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 2, (683 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -25, 17, (684 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -25, 49, (520 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, -24, (1560 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 8, (1764 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -39, 24, (1688 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -15, -8, (1768 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -23, 8, (675 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -63, 0, (1280 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -39, 64, (890 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -40, 2, (681 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 2, (683 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -25, 17, (684 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -25, 49, (520 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, -16, (1641 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -47, 16, (1612 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, -24, (1640 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -15, -8, (1580 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -23, 8, (675 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -63, 0, (1280 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -39, 64, (890 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -40, 2, (681 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 2, (683 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -25, 17, (684 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -25, 49, (520 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -39, -16, (1705 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -47, 16, (1614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -23, -24, (1656 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -23, 8, (675 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -63, 0, (1280 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -39, 64, (890 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -40, 2, (681 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -25, 17, (684 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -25, 49, (520 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 2, (683 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -23, 8, (675 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -63, 0, (1280 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -39, 64, (890 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -40, 2, (681 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -25, 17, (684 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -25, 49, (520 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 2, (683 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -23, 8, (675 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -63, 0, (1280 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -39, 64, (890 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -40, 2, (681 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -25, 17, (684 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -25, 49, (520 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 2, (683 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -23, 8, (675 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -63, 0, (1280 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -39, 64, (890 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -40, 2, (681 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -25, 17, (684 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -25, 49, (520 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 2, (683 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -55, 8, (1288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 40, (750 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 40, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, 0, (658 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, -8, (642 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 40, (670 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -65, 35, (1792 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -50, 21, (156 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -28, 27, (1221 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -10, 26, (1223 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 3, (1224 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -29, 14, (1189 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -55, 10, (546 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 2, (640 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 0, (1568 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, -24, (1540 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -15, 8, (1604 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -15, 24, (1672 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 32, (1544 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -31, -16, (1538 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -31, -24, (588 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -47, -16, (1536 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -15, -32, (1624 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -47, -32, (900 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 0, (964 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -15, 0, (968 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -23, 16, (960 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -30, -9, (1780 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -24, (1404 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -32, -24, (1548 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -24, -32, (1402 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -32, -8, (1391 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -16, (33 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, -24, (16 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 16, -16, (37 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -24, -16, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, 16, (9 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -24, 16, (8 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 16, -24, (4 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -16, -32, (0 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 8, 8, (1550 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 8, 40, (1119 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 24, 16, (1439 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 0, 8, (1423 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 8, 0, (1403 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -40, -24, (1516 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -24, -32, (253 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -40, -8, (1454 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -16, (39 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 16, -16, (43 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, 16, (24 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -24, -16, (38 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, -24, (20 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, -32, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -24, -24, (5 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 16, -24, (6 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -24, 16, (7 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 8, 0, (974 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 24, (1359 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 0, 8, (254 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 24, 16, (255 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -32, -24, (1419 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -40, -32, (1354 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -40, -24, (1356 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -16, (113 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, -24, (96 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -24, -16, (112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, 16, (100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 16, -16, (117 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 16, -24, (15 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, -32, (13 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -8, 0, (1512 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 8, 16, (1486 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -43, -27, (1516 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -27, -35, (253 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -43, -11, (1454 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -25, -30, (2304 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 7, -30, (2308 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -25, 2, (2368 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 7, 2, (2372 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -25, 18, (2400 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 7, 18, (2404 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 23, -14, (2310 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 11, 3, (974 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 3, 27, (1359 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 3, 11, (254 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 27, 19, (255 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 33, -26, (263 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 41, -34, (356 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 13, 0, (388 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 21, 32, (106 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0E @ flip, shape
		.2byte 5, -8, (368 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 25, -10, (324 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 21, 33, (106 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 13, 1, (388 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0E @ flip, shape
		.2byte 5, -8, (368 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 25, -9, (302 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 41, -33, (249 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 33, -25, (270 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 21, 33, (106 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 13, 1, (388 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0E @ flip, shape
		.2byte 5, -9, (368 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 25, -9, (364 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 41, -9, (250 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 33, -25, (332 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 12, 2, (388 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 24, -8, (366 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 40, -8, (455 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 32, -24, (334 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0E @ flip, shape
		.2byte 5, -9, (368 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 12, 2, (388 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 32, -24, (334 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 40, -8, (455 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 24, -8, (366 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0E @ flip, shape
		.2byte 5, -10, (368 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 13, 2, (388 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 41, -8, (250 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 33, -24, (332 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 25, -8, (364 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0E @ flip, shape
		.2byte 5, -10, (368 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 21, 33, (106 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 13, 1, (388 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0E @ flip, shape
		.2byte 5, -9, (368 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 41, -33, (249 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 33, -25, (270 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 25, -9, (302 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 21, 33, (106 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 13, 1, (388 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0E @ flip, shape
		.2byte 5, -9, (368 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 41, -33, (356 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 33, -25, (263 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 25, -9, (324 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 18, -11, (536 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 50, -19, (524 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 66, -19, (526 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 34, -19, (522 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 50, 13, (756 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 10, 21, (599 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 36, -23, (263 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 44, -31, (356 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 16, 3, (388 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 24, 35, (106 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0E @ flip, shape
		.2byte 8, -5, (368 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 28, -7, (324 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -40, -24, (264 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 0, 16, (256 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -40, -24, (259 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 0, 16, (325 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -40, -24, (328 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 0, 16, (320 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -3, 6, (256 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -40, -34, (264 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -40, -34, (259 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -3, 6, (325 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -40, -34, (328 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -3, 6, (320 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -43, -27, (264 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 3, 19, (256 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -45, -48, (396 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -56, -54, (512 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -24, -54, (516 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -16, -22, (581 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -8, -38, (550 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, -46, (534 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -32, -38, (7 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -45, -49, (396 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -55, -55, (512 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -23, -55, (516 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, -23, (581 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -7, -39, (550 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -7, -47, (534 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -45, -50, (456 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -55, -56, (512 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -23, -56, (516 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, -24, (581 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -7, -40, (550 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -7, -48, (534 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, -40, (7 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -46, -50, (456 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -56, -56, (512 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -24, -56, (516 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -16, -24, (581 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -8, -40, (550 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, -48, (534 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -32, -40, (7 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, -49, (396 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -57, -55, (512 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -25, -55, (516 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -17, -23, (581 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -9, -39, (550 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -9, -47, (534 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -49, -49, (392 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -58, -54, (512 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -26, -54, (516 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -18, -22, (581 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -10, -38, (550 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -10, -46, (534 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -48, -49, (392 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -58, -53, (512 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -26, -53, (516 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -18, -21, (581 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -10, -37, (550 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -10, -45, (534 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -34, -37, (7 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -46, -49, (396 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -57, -53, (512 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -25, -53, (516 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -17, -21, (581 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -9, -37, (550 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -9, -45, (534 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -33, -37, (7 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -26, -62, (28 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -10, -30, (121 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -10, -70, (104 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -42, -54, (119 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -48, -51, (396 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -59, -57, (512 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -27, -57, (516 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -19, -25, (581 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -11, -41, (550 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -11, -49, (534 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -35, -41, (7 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 8, 0, (1940 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 9, 2, (1920 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 8, 0, (1984 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 24, 8, (1986 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 24, 0, (1989 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 40, 0, (1988 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 16, (2005 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 10, 0, (1990 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 26, 8, (1992 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 26, 0, (1998 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 42, 8, (1994 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 26, 24, (1995 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 42, 24, (1997 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 16, 8, (1952 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 8, 0, (1972 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 8, 8, (1958 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 24, 0, (1974 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 24, 16, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 10, 7, (2107 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 26, 7, (2031 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 10, 23, (2139 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 26, 23, (2089 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 23, 17, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 8, 8, (2107 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 8, 24, (2139 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 24, 24, (2089 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 24, 8, (2031 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 9, 2, (2155 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 25, 18, (2154 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -19, 7, (2173 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -19, 23, (2205 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, 7, (2175 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -3, 23, (2207 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -3, 19, (2147 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -16, 14, (2057 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 22, (2059 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, 30, (2090 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -28, 1, (2025 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -12, 1, (2027 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -28, 17, (2028 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -12, 17, (2030 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 2, 1, (2048 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 2, 33, (2084 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -26, -5, (2027 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -42, 11, (2028 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -26, 11, (2030 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -42, -5, (2025 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -20, 24, (2090 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -12, 16, (2059 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -28, 8, (2057 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -9, 1, (2050 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 7, 1, (2052 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -26, -8, (2027 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -42, 8, (2028 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -26, 8, (2030 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -42, -8, (2025 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -21, 22, (2090 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -13, 14, (2059 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -29, 6, (2057 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -9, 0, (2050 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 7, 0, (2052 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -34, 31, (2022 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -18, 31, (2024 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -34, 47, (2044 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -18, 47, (2046 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -21, 26, (2053 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 3, 0, (2048 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 3, 32, (2084 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte 13, 2, (2048 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x00 @ flip, shape
		.2byte 21, 34, (2084 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte 11, 29, (2062 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 5, 50, (2019 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 21, 50, (2021 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 5, 66, (2014 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 21, 66, (1999 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte 21, -1, (2050 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x02 @ flip, shape
		.2byte 13, -1, (2052 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 30, 24, (2062 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 34, 44, (2016 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 50, 44, (2018 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 34, 60, (2011 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 50, 60, (2013 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte 21, -2, (2050 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x02 @ flip, shape
		.2byte 13, -2, (2052 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 32, 23, (2062 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 37, 41, (2016 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 53, 41, (2018 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 37, 57, (2011 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 53, 57, (2013 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte 21, -2, (2050 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x02 @ flip, shape
		.2byte 13, -2, (2052 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 32, 22, (2062 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 37, 39, (2016 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 53, 39, (2018 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 37, 55, (2011 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 53, 55, (2013 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte 21, -3, (2050 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x02 @ flip, shape
		.2byte 13, -3, (2052 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 31, 21, (2093 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 15, 21, (2060 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 15, 37, (2091 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 5, 33, (2240 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 5, 49, (2272 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 21, 33, (2242 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 21, 49, (2274 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 9, -1, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 33, 15, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 41, 7, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x09 @ flip, shape
		.2byte 18, 16, (2147 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 9, 13, (2107 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 25, 13, (2031 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 9, 29, (2139 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 25, 29, (2089 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 24, 16, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 4, 6, (2208 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 12, 22, (2132 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 28, 22, (2134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 24, 16, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -8, 8, (2116 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 8, 16, (2144 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 24, 8, (2146 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 24, 24, (2103 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -28, 1, (2268 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 4, 9, (2216 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 24, 17, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 11, 12, (2176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 27, 12, (2178 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -28, 1, (2268 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 4, 9, (2216 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 24, 17, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 11, 12, (2176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 27, 12, (2178 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 24, 17, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -28, 1, (2268 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 4, 9, (2216 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 11, 12, (2176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 27, 12, (2178 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 23, 17, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 2, 10, (2216 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -30, 2, (2268 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 9, 13, (2176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 25, 13, (2178 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 9, 2, (2155 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 25, 18, (2154 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -3, 19, (2147 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -20, 10, (2216 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -52, 2, (2268 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -13, 13, (2176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 3, 13, (2178 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -55, -19, (558 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, -3, (1894 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -23, 5, (749 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, 13, (583 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -39, -11, (2135 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -47, -3, (2290 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -29, 7, (2022 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -13, 7, (2024 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -29, 23, (2044 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -13, 23, (2046 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -16, 14, (2057 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 22, (2059 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, 30, (2090 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 2, 1, (2048 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 2, 33, (2084 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -41, -45, (2248 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -41, -13, (2245 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -45, -4, (2221 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -29, -4, (2223 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -45, 12, (2253 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -29, 12, (2255 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -20, 24, (2090 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -12, 16, (2059 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -28, 8, (2057 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -9, 1, (2050 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 7, 1, (2052 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -40, -47, (2248 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -40, -15, (2245 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -44, -6, (2221 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -28, -6, (2223 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -44, 10, (2253 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -28, 10, (2255 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -21, 22, (2090 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -13, 14, (2059 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -29, 6, (2057 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -9, 0, (2050 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 7, 0, (2052 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -23, -8, (268 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -7, -8, (2251 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 1, 8, (527 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 9, 16, (590 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 24, 17, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 11, 12, (2176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 27, 12, (2178 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -23, -8, (268 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -7, -8, (2251 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 1, 8, (527 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 9, 16, (590 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 24, 17, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 11, 12, (2176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 27, 12, (2178 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -23, -8, (268 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -7, -8, (2251 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 1, 8, (527 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 9, 16, (590 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 24, 17, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 11, 12, (2176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 27, 12, (2178 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 23, 17, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -25, -7, (268 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -9, -7, (2251 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -1, 9, (527 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 7, 17, (590 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 9, 13, (2176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 25, 13, (2178 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 9, 2, (2155 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 25, 18, (2154 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -3, 19, (2147 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -47, -7, (268 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -31, -7, (2251 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -23, 9, (527 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -15, 17, (590 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -13, 13, (2176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 3, 13, (2178 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -55, -20, (2278 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -39, -20, (2250 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -55, -4, (2300 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -31, -4, (519 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -23, 4, (551 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, 12, (2202 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -29, 7, (2022 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -13, 7, (2024 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -29, 23, (2044 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -13, 23, (2046 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -16, 14, (2057 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 22, (2059 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, 30, (2090 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 2, 1, (2048 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 2, 33, (2084 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -44, -40, (2275 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -28, -40, (2247 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -44, -24, (2199 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -28, -24, (2201 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -36, -16, (2277 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -45, -4, (2221 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -29, -4, (2223 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -45, 12, (2253 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -29, 12, (2255 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -20, 24, (2090 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -12, 16, (2059 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -28, 8, (2057 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -9, 1, (2050 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 7, 1, (2052 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -43, -42, (2275 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -27, -42, (2247 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -43, -26, (2199 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -27, -26, (2201 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -35, -18, (2277 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -44, -6, (2221 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -28, -6, (2223 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -44, 10, (2253 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -28, 10, (2255 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -21, 22, (2090 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -13, 14, (2059 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -29, 6, (2057 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -9, 0, (2050 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 7, 0, (2052 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 2, -1, (1805 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -14, 15, (1888 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -6, 31, (1820 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -14, 7, (1872 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 24, 17, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 11, 12, (2176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 27, 12, (2178 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 2, -1, (1805 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -14, 15, (1888 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -6, 31, (1820 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -14, 7, (1872 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 24, 17, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 11, 12, (2176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 27, 12, (2178 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -14, 15, (1888 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -6, 31, (1820 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -14, 7, (1872 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 2, -1, (1805 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 24, 17, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 11, 12, (2176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 27, 12, (2178 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 8, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 0, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 16, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 24, 16, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -13, 13, (1888 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -5, 29, (1820 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -13, 5, (1872 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 3, -3, (1805 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 12, 10, (2176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 28, 10, (2178 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, -1, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 32, 15, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 40, 7, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 25, 11, (2085 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 20, -2, (2218 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 36, -2, (2220 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 20, 14, (2302 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 36, 14, (2252 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -1, -15, (1868 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 54, -43, (1932 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 86, -35, (1931 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 86, -19, (1963 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 62, -11, (1979 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x09 @ flip, shape
		.2byte 8, -6, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x00 @ flip, shape
		.2byte 40, -6, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x01 @ flip, shape
		.2byte 32, -14, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 47, -29, (2136 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 47, -45, (2104 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 63, -45, (2106 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 63, -29, (2138 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x04 @ flip, shape
		.2byte 43, -21, (2060 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x02 @ flip, shape
		.2byte 35, -21, (2093 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x01 @ flip, shape
		.2byte 43, -29, (2091 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 55, -41, (1932 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 87, -33, (1931 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 87, -17, (1963 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 63, -9, (1979 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x09 @ flip, shape
		.2byte 9, -6, (2112 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x01 @ flip, shape
		.2byte 33, -14, (2101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x00 @ flip, shape
		.2byte 41, -6, (2100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 49, -44, (2104 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 65, -44, (2106 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 49, -28, (2136 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 65, -28, (2138 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x04 @ flip, shape
		.2byte 44, -20, (2060 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x01 @ flip, shape
		.2byte 44, -28, (2091 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x02 @ flip, shape
		.2byte 36, -20, (2093 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 30, -52, (1927 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 30, -20, (1924 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 62, -44, (1926 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 26, -49, (2104 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 42, -49, (2106 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 26, -33, (2136 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 42, -33, (2138 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x0A @ flip, shape
		.2byte 21, -37, (2062 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 8, -13, (2151 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 8, 3, (2185 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 24, -13, (2153 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, 8, (2179 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 4, 0, (2183 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -28, -5, (2125 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -12, -5, (2127 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -28, 11, (2157 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -12, 11, (2159 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -35, -21, (1864 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -27, 11, (1892 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 0, 1, (2212 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, 17, (2214 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -19, 26, (2243 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -19, 42, (2288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -35, 44, (2240 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -19, 44, (2242 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -35, 60, (2272 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -19, 60, (2274 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -55, 67, (1860 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -55, 83, (496 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -47, 91, (1908 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -47, 51, (1836 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -31, 51, (1775 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, 17, (2214 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 0, 1, (2212 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -19, 25, (2243 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -19, 41, (2288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -35, 58, (2272 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -19, 58, (2274 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -35, 42, (2240 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -19, 42, (2242 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -55, 65, (1860 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -55, 81, (496 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -47, 89, (1908 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -47, 49, (1836 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -31, 49, (1775 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, 8, (676 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (688 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -15, 40, (740 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -43, 31, (1196 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -30, 14, (1258 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 28, (1262 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 2, (1135 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -47, 48, (752 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -46, 15, (1195 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -35, 2, (1166 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (688 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (752 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, 8, (676 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -15, 40, (740 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -35, 3, (123 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -45, 16, (176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -34, 32, (177 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -18, 32, (179 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -34, 48, (209 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -23, 16, (225 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -7, 16, (240 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 3, (180 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -10, 27, (153 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (688 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (752 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, 8, (676 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -15, 40, (740 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 2, (154 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -46, 16, (181 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -33, 32, (182 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -17, 32, (184 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -33, 48, (214 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -22, 13, (220 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -6, 13, (218 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -3, 21, (211 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -3, 5, (230 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 28, (216 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (688 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (752 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, 8, (676 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -15, 40, (740 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 2, (185 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -46, 16, (187 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -33, 32, (222 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -17, 32, (227 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -33, 48, (244 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -22, 13, (452 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -6, 13, (454 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -3, 21, (248 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -3, 5, (484 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 28, (486 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (601 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -15, 16, (605 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (665 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -47, 32, (2397 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -47, 48, (2422 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -56, 45, (2311 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (601 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -15, 16, (605 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (665 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -47, 32, (2397 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -47, 48, (2422 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -54, 47, (2313 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (601 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -15, 16, (605 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (665 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -47, 32, (2397 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -47, 48, (2422 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -52, 48, (2343 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -52, 64, (2375 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (601 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -15, 16, (605 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (665 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -47, 32, (2397 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -47, 48, (2422 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -50, 43, (2315 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -58, 43, (2374 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -58, 59, (2406 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (601 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -15, 16, (605 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (665 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -47, 32, (2397 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -47, 48, (2422 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -61, 27, (2317 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -61, 59, (2381 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -45, 27, (2319 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (601 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -15, 16, (605 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (665 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -47, 32, (2397 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -47, 48, (2422 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -67, 23, (2377 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -67, 39, (2409 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -51, 47, (2391 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (601 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -15, 16, (605 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (665 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -47, 32, (2397 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -47, 48, (2422 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -57, 25, (2416 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -57, 57, (2468 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -41, 49, (2383 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (601 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -15, 16, (605 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (665 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -47, 32, (2397 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -47, 48, (2422 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -62, 47, (2418 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -46, 47, (2399 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -46, 63, (2424 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (601 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -15, 16, (605 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (665 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -47, 32, (2397 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -47, 48, (2422 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -62, 56, (2420 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -62, 72, (2452 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -54, 48, (2407 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (601 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -15, 16, (605 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (665 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -47, 32, (2397 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -47, 48, (2422 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -55, 8, (1288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 40, (750 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 40, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, 0, (658 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, -8, (642 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 40, (670 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -28, 27, (1221 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -10, 26, (1223 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 3, (1224 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -29, 14, (1189 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -55, 10, (546 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 2, (640 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -79, 56, (1792 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -47, 32, (680 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -55, 40, (1743 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 24, (1773 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -79, 56, (1796 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -47, 32, (1677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -55, 40, (1581 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 24, (1800 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -79, 64, (1769 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -87, 56, (1741 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -79, 80, (1661 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -55, 32, (1678 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -63, 56, (1645 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 24, (1646 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -79, 64, (1832 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -79, 80, (1856 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -55, 32, (1806 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -63, 56, (1804 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 24, (1802 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, 8, (676 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (688 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -15, 40, (740 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -43, 31, (1196 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -30, 14, (1258 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 28, (1262 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 2, (1135 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -47, 48, (752 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -46, 15, (1195 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -35, 2, (1166 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -47, 16, (688 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -47, 48, (752 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -39, 8, (673 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, 8, (676 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -15, 40, (740 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -35, 3, (123 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -45, 16, (176 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -34, 32, (177 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -18, 32, (179 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -34, 48, (209 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -23, 16, (225 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -7, 16, (240 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 3, (180 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -10, 27, (153 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -55, 8, (1288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 40, (750 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 40, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, 0, (658 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, -8, (642 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 40, (670 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -35, 3, (123 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, 0, (658 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -55, 8, (1288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 40, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 40, (670 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 40, (750 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -29, 27, (713 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -24, 15, (741 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -10, 29, (747 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 4, (606 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, -8, (642 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, 0, (252 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -53, 15, (1193 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -36, 3, (1257 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, 0, (251 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, 0, (658 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, -8, (642 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -55, 8, (1288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 40, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 40, (670 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 40, (750 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -31, 0, (251 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -28, 27, (1221 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -29, 14, (1189 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 3, (1224 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -10, 26, (1223 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -55, 10, (546 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 2, (640 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, 0, (658 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, -8, (642 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 40, (750 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 40, (670 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 40, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -55, 8, (1288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -28, 27, (1216 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -29, 14, (1184 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 3, (1188 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -15, 26, (1218 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -55, 10, (544 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 2, (608 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -63, 0, (1280 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -40, 2, (681 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -51, 28, (1678 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -38, 32, (1662 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -23, 8, (675 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -39, 64, (890 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -25, 17, (684 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -25, 49, (520 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 2, (683 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -59, 52, (1645 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -75, 60, (1769 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -83, 52, (1741 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -75, 76, (1661 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -23, 8, (675 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0C @ flip, shape
		.2byte -63, 0, (1280 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -39, 64, (890 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, 8, (677 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -40, 2, (681 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -25, 17, (684 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -25, 49, (520 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 2, (683 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -80, 55, (1792 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -56, 39, (1743 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -48, 31, (680 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -40, 23, (1773 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -55, 8, (1288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, 40, (750 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -47, 40, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 9, 8, (679 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, 0, (658 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -24, (614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -31, -8, (642 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -55, 40, (670 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -31, -24, (610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -10, 26, (1223 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 0, 3, (1224 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -39, 2, (640 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -50, 34, (1804 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -55, 10, (546 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -50, 21, (156 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -29, 14, (1189 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -28, 27, (1221 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
	@ Unk2
		.byte 0x00, 0x00, 0x01, 0x00
		.byte 0x01, 0x00, 0x0A, 0x00
		.byte 0x02, 0x00, 0x08, 0x00
		.byte 0x03, 0x00, 0x08, 0x00
		.byte 0x04, 0x00, 0x08, 0x00
		.byte 0x05, 0x00, 0x08, 0x00
		.byte 0x06, 0x00, 0x04, 0x00
		.byte 0x08, 0x00, 0x06, 0x00
		.byte 0x07, 0x00, 0x04, 0x00
		.byte 0x09, 0x00, 0x0A, 0x00
		.byte 0x0A, 0x00, 0x0A, 0x00
		.byte 0x0B, 0x00, 0x0A, 0x00
		.byte 0x0A, 0x00, 0x0A, 0x00
		.byte 0x0C, 0x00, 0x06, 0x00
		.byte 0x0A, 0x00, 0x06, 0x00
		.byte 0x0D, 0x00, 0x06, 0x00
		.byte 0x0A, 0x00, 0x06, 0x00
		.byte 0x0E, 0x00, 0x0A, 0x00
		.byte 0x0F, 0x00, 0x0A, 0x00
		.byte 0x11, 0x00, 0x10, 0x00
		.byte 0x10, 0x00, 0x08, 0x00
		.byte 0x11, 0x00, 0x06, 0x00
		.byte 0x12, 0x00, 0x06, 0x00
		.byte 0x11, 0x00, 0x04, 0x00
		.byte 0x12, 0x00, 0x20, 0x00
		.byte 0x14, 0x00, 0x10, 0x00
		.byte 0x13, 0x00, 0x08, 0x00
		.byte 0x16, 0x00, 0x10, 0x00
		.byte 0x15, 0x00, 0x08, 0x00
		.byte 0x16, 0x00, 0x06, 0x00
		.byte 0x17, 0x00, 0x06, 0x00
		.byte 0x16, 0x00, 0x04, 0x00
		.byte 0x17, 0x00, 0x20, 0x00
		.byte 0x14, 0x00, 0x10, 0x00
		.byte 0x18, 0x00, 0x08, 0x00
		.byte 0x14, 0x00, 0x04, 0x00
		.byte 0x19, 0x00, 0x06, 0x00
		.byte 0x1D, 0x00, 0x06, 0x00
		.byte 0x1E, 0x00, 0x06, 0x00
		.byte 0x1F, 0x00, 0x06, 0x00
		.byte 0x20, 0x00, 0x06, 0x00
		.byte 0x21, 0x00, 0x08, 0x00
		.byte 0x01, 0x00, 0x04, 0x00
		.byte 0x22, 0x00, 0x01, 0x00
		.byte 0x23, 0x00, 0x01, 0x00
		.byte 0x72, 0x00, 0x06, 0x00
		.byte 0x73, 0x00, 0x11, 0x00
		.byte 0x72, 0x00, 0x01, 0x00
		.byte 0x00, 0x00, 0x01, 0x00
		.byte 0x75, 0x00, 0x04, 0x00
		.byte 0x74, 0x00, 0x04, 0x00
		.byte 0x00, 0x00, 0x05, 0x00
		.byte 0x72, 0x00, 0x05, 0x00
		.byte 0x73, 0x00, 0x09, 0x00
		.byte 0x72, 0x00, 0x02, 0x00
		.byte 0x00, 0x00, 0x04, 0x00
		.byte 0x01, 0x00, 0x08, 0x00
		.byte 0x7F, 0x00, 0x06, 0x00
		.byte 0x76, 0x00, 0x06, 0x00
		.byte 0x77, 0x00, 0x06, 0x00
		.byte 0x78, 0x00, 0x06, 0x00
		.byte 0x79, 0x00, 0x06, 0x00
		.byte 0x7A, 0x00, 0x06, 0x00
		.byte 0x7B, 0x00, 0x06, 0x00
		.byte 0x7C, 0x00, 0x06, 0x00
		.byte 0x7D, 0x00, 0x06, 0x00
		.byte 0x7E, 0x00, 0x06, 0x00
		.byte 0x76, 0x00, 0x04, 0x00
		.byte 0x7F, 0x00, 0x06, 0x00
		.byte 0x01, 0x00, 0x06, 0x00
		.byte 0x24, 0x00, 0x01, 0x00
		.byte 0x25, 0x00, 0x01, 0x00
		.byte 0x26, 0x00, 0x01, 0x00
		.byte 0x27, 0x00, 0x01, 0x00
		.byte 0x28, 0x00, 0x07, 0x00
		.byte 0x29, 0x00, 0x07, 0x00
		.byte 0x2A, 0x00, 0x07, 0x00
		.byte 0x2B, 0x00, 0x07, 0x00
		.byte 0x2C, 0x00, 0x07, 0x00
		.byte 0x2D, 0x00, 0x07, 0x00
		.byte 0x2E, 0x00, 0x07, 0x00
		.byte 0x2F, 0x00, 0x07, 0x00
		.byte 0x30, 0x00, 0x01, 0x00
		.byte 0x31, 0x00, 0x01, 0x00
		.byte 0x32, 0x00, 0x0C, 0x00
		.byte 0x33, 0x00, 0x0C, 0x00
		.byte 0x34, 0x00, 0x0C, 0x00
		.byte 0x33, 0x00, 0x0C, 0x00
		.byte 0x35, 0x00, 0x0C, 0x00
		.byte 0x36, 0x00, 0x0C, 0x00
		.byte 0x37, 0x00, 0x0C, 0x00
		.byte 0x36, 0x00, 0x0C, 0x00
		.byte 0x38, 0x00, 0x01, 0x00
		.byte 0x39, 0x00, 0x08, 0x00
		.byte 0x3A, 0x00, 0x08, 0x00
		.byte 0x3B, 0x00, 0x08, 0x00
		.byte 0x3C, 0x00, 0x08, 0x00
		.byte 0x3D, 0x00, 0x08, 0x00
		.byte 0x3E, 0x00, 0x08, 0x00
		.byte 0x3F, 0x00, 0x08, 0x00
		.byte 0x40, 0x00, 0x08, 0x00
		.byte 0x41, 0x00, 0x01, 0x00
		.byte 0x42, 0x00, 0x01, 0x00
		.byte 0x44, 0x00, 0x08, 0x00
		.byte 0x45, 0x00, 0x08, 0x00
		.byte 0x46, 0x00, 0x08, 0x00
		.byte 0x47, 0x00, 0x08, 0x00
		.byte 0x49, 0x00, 0x04, 0x00
		.byte 0x48, 0x00, 0x27, 0x00
		.byte 0x49, 0x00, 0x05, 0x00
		.byte 0x4A, 0x00, 0x05, 0x00
		.byte 0x4B, 0x00, 0x05, 0x00
		.byte 0x4C, 0x00, 0x07, 0x00
		.byte 0x4D, 0x00, 0x24, 0x00
		.byte 0x4C, 0x00, 0x04, 0x00
		.byte 0x4E, 0x00, 0x03, 0x00
		.byte 0x4F, 0x00, 0x03, 0x00
		.byte 0x50, 0x00, 0x03, 0x00
		.byte 0x51, 0x00, 0x05, 0x00
		.byte 0x52, 0x00, 0x1B, 0x00
		.byte 0x51, 0x00, 0x05, 0x00
		.byte 0x53, 0x00, 0x0A, 0x00
		.byte 0x54, 0x00, 0x08, 0x00
		.byte 0x48, 0x00, 0x08, 0x00
		.byte 0x47, 0x00, 0x08, 0x00
		.byte 0x46, 0x00, 0x08, 0x00
		.byte 0x45, 0x00, 0x08, 0x00
		.byte 0x44, 0x00, 0x08, 0x00
		.byte 0x43, 0x00, 0x08, 0x00
		.byte 0x44, 0x00, 0x08, 0x00
		.byte 0x45, 0x00, 0x08, 0x00
		.byte 0x46, 0x00, 0x08, 0x00
		.byte 0x47, 0x00, 0x08, 0x00
		.byte 0x48, 0x00, 0x0A, 0x00
		.byte 0x55, 0x00, 0x06, 0x00
		.byte 0x56, 0x00, 0x06, 0x00
		.byte 0x57, 0x00, 0x06, 0x00
		.byte 0x58, 0x00, 0x06, 0x00
		.byte 0x59, 0x00, 0x13, 0x00
		.byte 0x5A, 0x00, 0x05, 0x00
		.byte 0x5B, 0x00, 0x05, 0x00
		.byte 0x5C, 0x00, 0x05, 0x00
		.byte 0x5D, 0x00, 0x05, 0x00
		.byte 0x5E, 0x00, 0x08, 0x00
		.byte 0x5D, 0x00, 0x1E, 0x00
		.byte 0x5E, 0x00, 0x04, 0x00
		.byte 0x4E, 0x00, 0x03, 0x00
		.byte 0x4F, 0x00, 0x03, 0x00
		.byte 0x50, 0x00, 0x03, 0x00
		.byte 0x51, 0x00, 0x05, 0x00
		.byte 0x52, 0x00, 0x1B, 0x00
		.byte 0x51, 0x00, 0x05, 0x00
		.byte 0x53, 0x00, 0x0A, 0x00
		.byte 0x54, 0x00, 0x08, 0x00
		.byte 0x48, 0x00, 0x08, 0x00
		.byte 0x47, 0x00, 0x08, 0x00
		.byte 0x46, 0x00, 0x08, 0x00
		.byte 0x45, 0x00, 0x08, 0x00
		.byte 0x44, 0x00, 0x08, 0x00
		.byte 0x43, 0x00, 0x08, 0x00
		.byte 0x44, 0x00, 0x08, 0x00
		.byte 0x45, 0x00, 0x08, 0x00
		.byte 0x46, 0x00, 0x08, 0x00
		.byte 0x47, 0x00, 0x08, 0x00
		.byte 0x48, 0x00, 0x0A, 0x00
		.byte 0x55, 0x00, 0x06, 0x00
		.byte 0x56, 0x00, 0x06, 0x00
		.byte 0x5F, 0x00, 0x06, 0x00
		.byte 0x60, 0x00, 0x06, 0x00
		.byte 0x61, 0x00, 0x13, 0x00
		.byte 0x62, 0x00, 0x05, 0x00
		.byte 0x63, 0x00, 0x05, 0x00
		.byte 0x64, 0x00, 0x05, 0x00
		.byte 0x65, 0x00, 0x05, 0x00
		.byte 0x66, 0x00, 0x08, 0x00
		.byte 0x65, 0x00, 0x1E, 0x00
		.byte 0x66, 0x00, 0x04, 0x00
		.byte 0x4E, 0x00, 0x03, 0x00
		.byte 0x4F, 0x00, 0x03, 0x00
		.byte 0x50, 0x00, 0x03, 0x00
		.byte 0x51, 0x00, 0x05, 0x00
		.byte 0x52, 0x00, 0x1B, 0x00
		.byte 0x51, 0x00, 0x05, 0x00
		.byte 0x53, 0x00, 0x0A, 0x00
		.byte 0x54, 0x00, 0x08, 0x00
		.byte 0x48, 0x00, 0x08, 0x00
		.byte 0x47, 0x00, 0x08, 0x00
		.byte 0x46, 0x00, 0x08, 0x00
		.byte 0x45, 0x00, 0x08, 0x00
		.byte 0x44, 0x00, 0x08, 0x00
		.byte 0x43, 0x00, 0x08, 0x00
		.byte 0x44, 0x00, 0x08, 0x00
		.byte 0x45, 0x00, 0x08, 0x00
		.byte 0x46, 0x00, 0x08, 0x00
		.byte 0x47, 0x00, 0x08, 0x00
		.byte 0x48, 0x00, 0x0A, 0x00
		.byte 0x55, 0x00, 0x06, 0x00
		.byte 0x56, 0x00, 0x06, 0x00
		.byte 0x67, 0x00, 0x06, 0x00
		.byte 0x68, 0x00, 0x06, 0x00
		.byte 0x69, 0x00, 0x13, 0x00
		.byte 0x6A, 0x00, 0x06, 0x00
		.byte 0x6B, 0x00, 0x06, 0x00
		.byte 0x6C, 0x00, 0x06, 0x00
		.byte 0x6D, 0x00, 0x13, 0x00
		.byte 0x6C, 0x00, 0x04, 0x00
		.byte 0x6E, 0x00, 0x03, 0x00
		.byte 0x6F, 0x00, 0x03, 0x00
		.byte 0x70, 0x00, 0x02, 0x00
		.byte 0x71, 0x00, 0x02, 0x00
		.byte 0x71, 0x00, 0x03, 0x00
		.byte 0x70, 0x00, 0x20, 0x00
		.byte 0x71, 0x00, 0x04, 0x00
		.byte 0x6F, 0x00, 0x0A, 0x00
		.byte 0x6B, 0x00, 0x0A, 0x00
		.byte 0x6A, 0x00, 0x0A, 0x00
		.byte 0x69, 0x00, 0x04, 0x00
		.byte 0x68, 0x00, 0x04, 0x00
		.byte 0x67, 0x00, 0x06, 0x00
		.byte 0x56, 0x00, 0x06, 0x00
		.byte 0x55, 0x00, 0x08, 0x00
		.byte 0x48, 0x00, 0x08, 0x00
		.byte 0x47, 0x00, 0x08, 0x00
		.byte 0x46, 0x00, 0x08, 0x00
		.byte 0x45, 0x00, 0x08, 0x00
		.byte 0x44, 0x00, 0x08, 0x00
		.byte 0x43, 0x00, 0x08, 0x00
		.byte 0x19, 0x00, 0x08, 0x00
		.byte 0x1A, 0x00, 0x08, 0x00
		.byte 0x1B, 0x00, 0x08, 0x00
		.byte 0x1C, 0x00, 0x08, 0x00
		.byte 0x80, 0x00, 0x06, 0x00
		.byte 0x01, 0x00, 0x06, 0x00
		.byte 0x81, 0x00, 0x06, 0x00
		.byte 0x82, 0x00, 0x06, 0x00
		.byte 0x83, 0x00, 0x06, 0x00
		.byte 0x84, 0x00, 0x06, 0x00
		.byte 0x44, 0x00, 0x08, 0x00
		.byte 0x45, 0x00, 0x08, 0x00
		.byte 0x46, 0x00, 0x08, 0x00
		.byte 0x47, 0x00, 0x08, 0x00
		.byte 0x48, 0x00, 0x0A, 0x00
		.byte 0x55, 0x00, 0x06, 0x00
		.byte 0x56, 0x00, 0x06, 0x00
		.byte 0x57, 0x00, 0x06, 0x00
		.byte 0x58, 0x00, 0x06, 0x00
		.byte 0x59, 0x00, 0x13, 0x00
		.byte 0x5A, 0x00, 0x05, 0x00
		.byte 0x5B, 0x00, 0x05, 0x00
		.byte 0x5C, 0x00, 0x05, 0x00
		.byte 0x5D, 0x00, 0x05, 0x00
		.byte 0x5E, 0x00, 0x08, 0x00
		.byte 0x5D, 0x00, 0x1E, 0x00
		.byte 0x55, 0x00, 0x06, 0x00
		.byte 0x56, 0x00, 0x06, 0x00
		.byte 0x5F, 0x00, 0x06, 0x00
		.byte 0x60, 0x00, 0x06, 0x00
		.byte 0x61, 0x00, 0x13, 0x00
		.byte 0x62, 0x00, 0x05, 0x00
		.byte 0x63, 0x00, 0x05, 0x00
		.byte 0x64, 0x00, 0x05, 0x00
		.byte 0x65, 0x00, 0x05, 0x00
		.byte 0x66, 0x00, 0x08, 0x00
		.byte 0x65, 0x00, 0x1E, 0x00
		.byte 0x5E, 0x00, 0x04, 0x00
		.byte 0x4E, 0x00, 0x03, 0x00
		.byte 0x4F, 0x00, 0x03, 0x00
		.byte 0x50, 0x00, 0x03, 0x00
		.byte 0x51, 0x00, 0x05, 0x00
		.byte 0x52, 0x00, 0x1B, 0x00
		.byte 0x51, 0x00, 0x05, 0x00
		.byte 0x53, 0x00, 0x0A, 0x00
		.byte 0x54, 0x00, 0x08, 0x00
		.byte 0x66, 0x00, 0x04, 0x00
		.byte 0x4E, 0x00, 0x03, 0x00
		.byte 0x4F, 0x00, 0x03, 0x00
		.byte 0x50, 0x00, 0x03, 0x00
		.byte 0x51, 0x00, 0x05, 0x00
		.byte 0x52, 0x00, 0x1B, 0x00
		.byte 0x51, 0x00, 0x05, 0x00
		.byte 0x53, 0x00, 0x0A, 0x00
		.byte 0x54, 0x00, 0x08, 0x00
		.byte 0x48, 0x00, 0x08, 0x00
		.byte 0x47, 0x00, 0x08, 0x00
		.byte 0x46, 0x00, 0x08, 0x00
		.byte 0x45, 0x00, 0x08, 0x00
		.byte 0x44, 0x00, 0x08, 0x00
		.byte 0x43, 0x00, 0x08, 0x00
		.byte 0x74, 0x00, 0x08, 0x00
		.byte 0x85, 0x00, 0x08, 0x00
		.byte 0x86, 0x00, 0x08, 0x00
		.byte 0x88, 0x00, 0x06, 0x00
		.byte 0x87, 0x00, 0x06, 0x00
		.byte 0x8D, 0x00, 0x06, 0x00
		.byte 0x8A, 0x00, 0x06, 0x00
		.byte 0x8D, 0x00, 0x06, 0x00
		.byte 0x88, 0x00, 0x06, 0x00
		.byte 0x87, 0x00, 0x06, 0x00
		.byte 0x88, 0x00, 0x03, 0x00
		.byte 0x87, 0x00, 0x03, 0x00
		.byte 0x88, 0x00, 0x0E, 0x00
		.byte 0x87, 0x00, 0x28, 0x00
		.byte 0x88, 0x00, 0x0B, 0x00
		.byte 0x87, 0x00, 0x0B, 0x00
		.byte 0x88, 0x00, 0x03, 0x00
		.byte 0x87, 0x00, 0x03, 0x00
		.byte 0x88, 0x00, 0x03, 0x00
		.byte 0x87, 0x00, 0x03, 0x00
		.byte 0x8D, 0x00, 0x06, 0x00
		.byte 0x8A, 0x00, 0x06, 0x00
		.byte 0x74, 0x00, 0x0A, 0x00
		.byte 0x72, 0x00, 0x02, 0x00
		.byte 0x73, 0x00, 0x06, 0x00
		.byte 0x72, 0x00, 0x06, 0x00
		.byte 0x73, 0x00, 0x01, 0x00
		.byte 0x72, 0x00, 0x0A, 0x00
	@ Tiles
		.incbin "data/spriteset/jormungandr.4bpp"
