SpriteSetFile28: @ 0x08C93384
	.2byte 749 @ palStart
	.2byte 37 @ metaspriteCount
	.2byte 23 @ unk1Count
	.2byte 224 @ subspriteCount
	.2byte 46 @ unk2Count
	.2byte 256 @ tileCount
	.4byte 0x00000020, 0x00000304, 0x000003BC, 0x00000ABC, 0x00000B74
	@ Metasprites
		.2byte 0xF541, 0x0006, 0x0000, 0x0000, 0xFFE8, 0xFFD0, 0x000A, 0x000A
		.4byte 0x0 @ subspriteOffset
		.2byte 0xF561, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFD0, 0x0008, 0x000A
		.4byte 0x30 @ subspriteOffset
		.2byte 0xF581, 0x0005, 0x0000, 0x0000, 0xFFE7, 0xFFD0, 0x0008, 0x000A
		.4byte 0x60 @ subspriteOffset
		.2byte 0xF5A1, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFD0, 0x0009, 0x000B
		.4byte 0x88 @ subspriteOffset
		.2byte 0xF5C1, 0x0006, 0x0000, 0x0000, 0xFFE8, 0xFFD0, 0x000A, 0x000B
		.4byte 0xB8 @ subspriteOffset
		.2byte 0xF371, 0x0005, 0x0000, 0x0000, 0xFFE7, 0xFFCF, 0x0012, 0x0000
		.4byte 0xE8 @ subspriteOffset
		.2byte 0xF372, 0x0006, 0x0000, 0x0000, 0xFFE8, 0xFFD0, 0x0011, 0x0000
		.4byte 0x110 @ subspriteOffset
		.2byte 0xF373, 0x0007, 0x0000, 0x0000, 0xFFE7, 0xFFCF, 0x0010, 0x0006
		.4byte 0x140 @ subspriteOffset
		.2byte 0xF374, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFD0, 0x0012, 0x0000
		.4byte 0x178 @ subspriteOffset
		.2byte 0xF3B1, 0x0005, 0x0000, 0x0000, 0xFFE6, 0xFFD1, 0x000B, 0x0000
		.4byte 0x1A8 @ subspriteOffset
		.2byte 0xF3B2, 0x0005, 0x0000, 0x0000, 0xFFE7, 0xFFD2, 0x000B, 0x0009
		.4byte 0x1D0 @ subspriteOffset
		.2byte 0xF3B3, 0x0007, 0x0000, 0x0000, 0xFFE7, 0xFFD1, 0x000D, 0x0000
		.4byte 0x1F8 @ subspriteOffset
		.2byte 0xF3B4, 0x0005, 0x0000, 0x0000, 0xFFE6, 0xFFD2, 0x000A, 0x0000
		.4byte 0x230 @ subspriteOffset
		.2byte 0xF501, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFD0, 0x0008, 0x000A
		.4byte 0x258 @ subspriteOffset
		.2byte 0xF502, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFCF, 0x0009, 0x000A
		.4byte 0x288 @ subspriteOffset
		.2byte 0xF503, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFCF, 0x000A, 0x000A
		.4byte 0x2B8 @ subspriteOffset
		.2byte 0xF504, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFCF, 0x000A, 0x000A
		.4byte 0x2E8 @ subspriteOffset
		.2byte 0x9CCF, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFD0, 0x0009, 0x000B
		.4byte 0x318 @ subspriteOffset
		.2byte 0xF542, 0x0007, 0x0000, 0x0000, 0xFFE7, 0xFFCE, 0x0009, 0x000B
		.4byte 0x348 @ subspriteOffset
		.2byte 0xF543, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFCE, 0x0009, 0x000B
		.4byte 0x380 @ subspriteOffset
		.2byte 0xF544, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFCE, 0x0009, 0x000B
		.4byte 0x3B0 @ subspriteOffset
		.2byte 0xF511, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFCE, 0x0009, 0x000B
		.4byte 0x3E0 @ subspriteOffset
		.2byte 0xF961, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFD0, 0x0008, 0x000A
		.4byte 0x410 @ subspriteOffset
		.2byte 0xF962, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFD0, 0x0008, 0x000A
		.4byte 0x440 @ subspriteOffset
		.2byte 0xF963, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFCF, 0x0007, 0x000A
		.4byte 0x470 @ subspriteOffset
		.2byte 0xF9A1, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFD0, 0x0009, 0x000B
		.4byte 0x4A0 @ subspriteOffset
		.2byte 0xF9A2, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFCE, 0x0009, 0x000B
		.4byte 0x4D0 @ subspriteOffset
		.2byte 0xF9A3, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFCE, 0x0009, 0x000B
		.4byte 0x500 @ subspriteOffset
		.2byte 0xECB1, 0x0007, 0x0000, 0x0000, 0xFFE7, 0xFFD0, 0x0009, 0x000B
		.4byte 0x530 @ subspriteOffset
		.2byte 0xECB2, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFCE, 0x000A, 0x000A
		.4byte 0x568 @ subspriteOffset
		.2byte 0xECB3, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFCF, 0x000A, 0x000B
		.4byte 0x598 @ subspriteOffset
		.2byte 0xECB4, 0x0007, 0x0000, 0x0000, 0xFFE7, 0xFFD0, 0x0009, 0x000B
		.4byte 0x5C8 @ subspriteOffset
		.2byte 0xEC71, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFD0, 0x0008, 0x000A
		.4byte 0x600 @ subspriteOffset
		.2byte 0xEC72, 0x0007, 0x0000, 0x0000, 0xFFE7, 0xFFCF, 0x0009, 0x0009
		.4byte 0x630 @ subspriteOffset
		.2byte 0xEC73, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFD0, 0x0009, 0x000A
		.4byte 0x668 @ subspriteOffset
		.2byte 0xEC74, 0x0006, 0x0000, 0x0000, 0xFFE7, 0xFFD0, 0x0008, 0x000A
		.4byte 0x698 @ subspriteOffset
		.2byte 0xEC75, 0x0007, 0x0000, 0x0000, 0xFFE7, 0xFFD0, 0x0008, 0x000A
		.4byte 0x6C8 @ subspriteOffset
	@ Unk1
		.byte 0x42, 0xB1, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00
		.byte 0x62, 0xB1, 0x01, 0x00, 0x04, 0x00, 0x00, 0x00
		.byte 0x82, 0xB1, 0x01, 0x00, 0x08, 0x00, 0x00, 0x00
		.byte 0xA2, 0xB1, 0x01, 0x00, 0x0C, 0x00, 0x00, 0x00
		.byte 0xC2, 0xB1, 0x01, 0x00, 0x10, 0x00, 0x00, 0x00
		.byte 0x79, 0x2F, 0x04, 0x00, 0x14, 0x00, 0x00, 0x00
		.byte 0xB9, 0x2F, 0x04, 0x00, 0x24, 0x00, 0x00, 0x00
		.byte 0x6C, 0xB5, 0x02, 0x00, 0x34, 0x00, 0x00, 0x00
		.byte 0x8C, 0xB5, 0x01, 0x00, 0x3C, 0x00, 0x00, 0x00
		.byte 0xAC, 0xB5, 0x02, 0x00, 0x40, 0x00, 0x00, 0x00
		.byte 0xCC, 0xB5, 0x01, 0x00, 0x48, 0x00, 0x00, 0x00
		.byte 0xB9, 0x30, 0x04, 0x00, 0x4C, 0x00, 0x00, 0x00
		.byte 0xD9, 0x30, 0x01, 0x00, 0x5C, 0x00, 0x00, 0x00
		.byte 0xF9, 0x30, 0x04, 0x00, 0x60, 0x00, 0x00, 0x00
		.byte 0x19, 0x31, 0x01, 0x00, 0x70, 0x00, 0x00, 0x00
		.byte 0x16, 0xB1, 0x04, 0x00, 0x74, 0x00, 0x00, 0x00
		.byte 0x36, 0xB1, 0x01, 0x00, 0x84, 0x00, 0x00, 0x00
		.byte 0x81, 0x07, 0x03, 0x00, 0x88, 0x00, 0x00, 0x00
		.byte 0xA1, 0x07, 0x01, 0x00, 0x94, 0x00, 0x00, 0x00
		.byte 0x98, 0xF8, 0x02, 0x00, 0x98, 0x00, 0x00, 0x00
		.byte 0xC1, 0x07, 0x03, 0x00, 0xA0, 0x00, 0x00, 0x00
		.byte 0xE1, 0x07, 0x01, 0x00, 0xAC, 0x00, 0x00, 0x00
		.byte 0x01, 0x08, 0x02, 0x00, 0xB0, 0x00, 0x00, 0x00
	@ Subsprites
		.byte 0x00, 0x02 @ flip, shape
		.2byte -4, -12, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -22, (10 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, -6, (42 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 2, -21, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -11, -21, (36 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (0 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -12, (65 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -9, -23, (38 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -22, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -6, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -1, -19, (33 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -4, -12, (67 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -22, (14 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -6, (46 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -4, -17, (34 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (4 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -11, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 1, -23, (39 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -21, (58 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -5, (90 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -8, -19, (35 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (6 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -4, -12, (69 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -21, (60 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, -5, (92 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 2, -21, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -11, -21, (36 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (8 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -25, (206 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -6, -11, (133 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -19, (168 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -6, -33, (100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 2, -18, (142 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -24, (206 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -4, -14, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -19, (170 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -6, -32, (102 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 1, -19, (220 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, -11, (152 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -7, -24, (206 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, -10, (135 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, -2, (151 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -20, (172 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -6, -33, (100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, -20, (105 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 8, -15, (143 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -23, (206 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -10, (137 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -19, (174 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -6, -32, (102 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 2, -19, (37 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 10, -16, (143 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 3, -22, (104 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -5, -11, (128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -10, -20, (160 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -6, -31, (96 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -7, -16, (129 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 3, -19, (155 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -7, (145 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -19, (162 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -7, -30, (98 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -6, -15, (138 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 5, -24, (207 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 0, -23, (41 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -1, -10, (131 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -9, -10, (130 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -20, (164 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -6, -31, (96 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -4, -16, (154 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -4, -12, (132 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 2, -20, (156 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -10, -19, (166 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -7, -30, (98 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -5, -15, (139 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -12, (65 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -9, -23, (38 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -22, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -6, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -1, -19, (33 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -12, (65 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -9, -23, (38 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -22, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -6, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, -18, (71 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -33, (192 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -7, -23, (40 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -12, (65 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -22, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -6, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 2, -18, (72 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -33, (192 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -12, (65 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -7, -23, (40 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -22, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -6, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 2, -18, (72 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -33, (192 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -11, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 1, -23, (39 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -21, (58 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -5, (90 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -8, -19, (35 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (6 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -11, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -21, (58 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -5, (90 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -7, -21, (70 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 1, -25, (41 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, -13, (87 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -34, (200 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -11, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -21, (58 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -5, (90 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, -20, (56 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -17, (88 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -34, (200 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -11, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -21, (58 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -5, (90 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, -20, (56 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -17, (88 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -34, (196 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -11, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -21, (58 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -5, (90 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, -20, (56 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -17, (88 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -34, (198 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -12, (65 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -9, -23, (38 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -22, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -6, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -1, -19, (33 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -12, (65 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -9, -23, (38 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -22, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -6, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -1, -19, (33 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -12, (65 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -9, -23, (38 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -22, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -6, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -1, -19, (33 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -33, (192 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -11, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 1, -23, (39 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -21, (58 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -5, (90 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -8, -19, (35 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (6 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -11, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 1, -23, (39 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -21, (58 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -5, (90 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -8, -19, (35 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -34, (194 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -11, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 1, -23, (39 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -21, (58 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -5, (90 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -8, -19, (35 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -34, (196 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -11, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -21, (58 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -5, (90 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 1, -25, (41 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -8, -21, (141 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 0, -13, (158 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (6 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -4, -11, (62 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 2, -23, (73 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -22, (58 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -6, (90 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -20, (204 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -34, (202 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -11, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -21, (58 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -5, (90 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 2, -22, (73 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -19, (204 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -33, (202 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 1, -25, (41 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -11, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -21, (58 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -5, (90 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -8, -21, (141 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -1, -14, (158 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (6 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -12, (65 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -9, -23, (38 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -22, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -6, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, -18, (66 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -9, -25, (94 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -19, (63 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -3, -3, (95 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -23, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -7, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -33, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, -22, (159 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -12, (65 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -9, -24, (94 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -22, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -6, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, -21, (159 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -9, -23, (94 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -12, (65 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -22, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -6, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, -18, (66 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -9, -23, (94 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -3, -12, (65 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -9, -22, (38 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -22, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -9, -6, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -32, (2 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, -18, (66 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
	@ Unk2
		.byte 0x00, 0x00, 0x01, 0x00
		.byte 0x01, 0x00, 0x01, 0x00
		.byte 0x02, 0x00, 0x01, 0x00
		.byte 0x03, 0x00, 0x01, 0x00
		.byte 0x04, 0x00, 0x01, 0x00
		.byte 0x05, 0x00, 0x09, 0x00
		.byte 0x06, 0x00, 0x0B, 0x00
		.byte 0x07, 0x00, 0x09, 0x00
		.byte 0x08, 0x00, 0x0B, 0x00
		.byte 0x09, 0x00, 0x09, 0x00
		.byte 0x0A, 0x00, 0x0B, 0x00
		.byte 0x0B, 0x00, 0x09, 0x00
		.byte 0x0C, 0x00, 0x0B, 0x00
		.byte 0x16, 0x00, 0x09, 0x00
		.byte 0x18, 0x00, 0x09, 0x00
		.byte 0x18, 0x00, 0x01, 0x00
		.byte 0x19, 0x00, 0x09, 0x00
		.byte 0x1B, 0x00, 0x09, 0x00
		.byte 0x1B, 0x00, 0x01, 0x00
		.byte 0x0D, 0x00, 0x0E, 0x00
		.byte 0x0E, 0x00, 0x09, 0x00
		.byte 0x0F, 0x00, 0x09, 0x00
		.byte 0x10, 0x00, 0x0E, 0x00
		.byte 0x10, 0x00, 0x01, 0x00
		.byte 0x11, 0x00, 0x0E, 0x00
		.byte 0x12, 0x00, 0x09, 0x00
		.byte 0x13, 0x00, 0x09, 0x00
		.byte 0x14, 0x00, 0x0E, 0x00
		.byte 0x14, 0x00, 0x01, 0x00
		.byte 0x11, 0x00, 0x0E, 0x00
		.byte 0x12, 0x00, 0x09, 0x00
		.byte 0x13, 0x00, 0x09, 0x00
		.byte 0x15, 0x00, 0x0E, 0x00
		.byte 0x15, 0x00, 0x01, 0x00
		.byte 0x01, 0x00, 0x04, 0x00
		.byte 0x20, 0x00, 0x04, 0x00
		.byte 0x21, 0x00, 0x04, 0x00
		.byte 0x22, 0x00, 0x18, 0x00
		.byte 0x20, 0x00, 0x06, 0x00
		.byte 0x01, 0x00, 0x06, 0x00
		.byte 0x03, 0x00, 0x04, 0x00
		.byte 0x1C, 0x00, 0x04, 0x00
		.byte 0x1D, 0x00, 0x04, 0x00
		.byte 0x1E, 0x00, 0x18, 0x00
		.byte 0x1F, 0x00, 0x06, 0x00
		.byte 0x03, 0x00, 0x06, 0x00
	@ Tiles
		.incbin "data/spriteset/rita.4bpp"
