SpriteSetFile21: @ 0x08C2B300
	.2byte 626 @ palStart
	.2byte 135 @ metaspriteCount
	.2byte 42 @ unk1Count
	.2byte 887 @ subspriteCount
	.2byte 180 @ unk2Count
	.2byte 2048 @ tileCount
	.4byte 0x00000020, 0x00000AAC, 0x00000BFC, 0x000027B4, 0x00002A84
	@ Metasprites
		.2byte 0x373A, 0x0009, 0x0000, 0x0000, 0xFFB1, 0xFFA8, 0x002F, 0x0000
		.4byte 0x0 @ subspriteOffset
		.2byte 0x373B, 0x0007, 0x0000, 0x0000, 0xFFB8, 0xFF9D, 0x0027, 0x000B
		.4byte 0x48 @ subspriteOffset
		.2byte 0x373C, 0x0007, 0x0000, 0x0000, 0xFFCF, 0xFF93, 0x0010, 0x0015
		.4byte 0x80 @ subspriteOffset
		.2byte 0x373D, 0x0007, 0x0000, 0x0000, 0xFFB9, 0xFF9C, 0x0027, 0x000C
		.4byte 0xB8 @ subspriteOffset
		.2byte 0x373E, 0x0009, 0x0000, 0x0000, 0xFFB1, 0xFFB0, 0x002F, 0x0000
		.4byte 0xF0 @ subspriteOffset
		.2byte 0x373F, 0x0007, 0x0000, 0x0000, 0xFFB8, 0xFF9D, 0x0027, 0x000B
		.4byte 0x138 @ subspriteOffset
		.2byte 0x3740, 0x0007, 0x0000, 0x0000, 0xFFD0, 0xFF93, 0x0011, 0x0015
		.4byte 0x170 @ subspriteOffset
		.2byte 0x3741, 0x0007, 0x0000, 0x0000, 0xFFB9, 0xFF9C, 0x0027, 0x000B
		.4byte 0x1A8 @ subspriteOffset
		.2byte 0x7A92, 0x0009, 0x0000, 0x0000, 0xFFC1, 0xFFA8, 0x0020, 0x0000
		.4byte 0x1E0 @ subspriteOffset
		.2byte 0x7A93, 0x0005, 0x0000, 0x0000, 0xFFD0, 0xFFA8, 0x0018, 0x0008
		.4byte 0x228 @ subspriteOffset
		.2byte 0x7A94, 0x0007, 0x0000, 0x0000, 0xFFD0, 0xFFB0, 0x0010, 0x0008
		.4byte 0x250 @ subspriteOffset
		.2byte 0x7A95, 0x0006, 0x0000, 0x0000, 0xFFC8, 0xFFB0, 0x0018, 0x0008
		.4byte 0x288 @ subspriteOffset
		.2byte 0x7A96, 0x0007, 0x0000, 0x0000, 0xFFC0, 0xFFB0, 0x0021, 0x0000
		.4byte 0x2B8 @ subspriteOffset
		.2byte 0x7A97, 0x0006, 0x0000, 0x0000, 0xFFC8, 0xFFB0, 0x0018, 0x0008
		.4byte 0x2F0 @ subspriteOffset
		.2byte 0x7A98, 0x0007, 0x0000, 0x0000, 0xFFD0, 0xFFB0, 0x0010, 0x0008
		.4byte 0x320 @ subspriteOffset
		.2byte 0x7A99, 0x0005, 0x0000, 0x0000, 0xFFD0, 0xFFA8, 0x0018, 0x0008
		.4byte 0x358 @ subspriteOffset
		.2byte 0xCB99, 0x0006, 0x0000, 0x0000, 0xFFD0, 0xFFB1, 0x0022, 0x0000
		.4byte 0x380 @ subspriteOffset
		.2byte 0xCB9A, 0x0007, 0x0000, 0x0000, 0xFFD0, 0xFFA4, 0x0027, 0x0010
		.4byte 0x3B0 @ subspriteOffset
		.2byte 0xCB9B, 0x0007, 0x0000, 0x0000, 0xFFD4, 0xFFAC, 0x001A, 0x0010
		.4byte 0x3E8 @ subspriteOffset
		.2byte 0xCB9C, 0x0008, 0x0000, 0x0000, 0xFFD4, 0xFFB1, 0x0019, 0x0008
		.4byte 0x420 @ subspriteOffset
		.2byte 0xCB9D, 0x0008, 0x0000, 0x0000, 0xFFD4, 0xFFB1, 0x0019, 0x0008
		.4byte 0x460 @ subspriteOffset
		.2byte 0xCB9E, 0x0006, 0x0000, 0x0000, 0xFFD4, 0xFFAB, 0x001C, 0x0008
		.4byte 0x4A0 @ subspriteOffset
		.2byte 0xCB9F, 0x0007, 0x0000, 0x0000, 0xFFD0, 0xFFA4, 0x0027, 0x0010
		.4byte 0x4D0 @ subspriteOffset
		.2byte 0xCBA0, 0x0006, 0x0000, 0x0000, 0xFFD0, 0xFFB1, 0x0023, 0x0010
		.4byte 0x508 @ subspriteOffset
		.2byte 0xC399, 0x0009, 0x0000, 0x0000, 0xFFCE, 0xFFB3, 0x0019, 0x0008
		.4byte 0x538 @ subspriteOffset
		.2byte 0xC39A, 0x0008, 0x0000, 0x0000, 0xFFD3, 0xFFB1, 0x0025, 0x0008
		.4byte 0x580 @ subspriteOffset
		.2byte 0xC39B, 0x0006, 0x0000, 0x0000, 0xFFD0, 0xFFAB, 0x0022, 0x0008
		.4byte 0x5C0 @ subspriteOffset
		.2byte 0xC39C, 0x0008, 0x0000, 0x0000, 0xFFD0, 0xFFB3, 0x001F, 0x0008
		.4byte 0x5F0 @ subspriteOffset
		.2byte 0xC39D, 0x0007, 0x0000, 0x0000, 0xFFD0, 0xFFB3, 0x001F, 0x0008
		.4byte 0x630 @ subspriteOffset
		.2byte 0xC39E, 0x0007, 0x0000, 0x0000, 0xFFD3, 0xFFB3, 0x0021, 0x0000
		.4byte 0x668 @ subspriteOffset
		.2byte 0xC39F, 0x0007, 0x0000, 0x0000, 0xFFD3, 0xFFAB, 0x0025, 0x0018
		.4byte 0x6A0 @ subspriteOffset
		.2byte 0xC3A0, 0x000A, 0x0000, 0x0000, 0xFFCE, 0xFFB3, 0x0019, 0x0008
		.4byte 0x6D8 @ subspriteOffset
		.2byte 0x0EF2, 0x0004, 0x0000, 0x0000, 0xFFD0, 0xFFB1, 0x0014, 0x0000
		.4byte 0x728 @ subspriteOffset
		.2byte 0x0EF3, 0x0005, 0x0000, 0x0000, 0xFFD0, 0xFFB1, 0x0018, 0x0010
		.4byte 0x748 @ subspriteOffset
		.2byte 0x0EF4, 0x0005, 0x0000, 0x0000, 0xFFD4, 0xFFB1, 0x0018, 0x0010
		.4byte 0x770 @ subspriteOffset
		.2byte 0x0EF5, 0x0006, 0x0000, 0x0000, 0xFFD4, 0xFFB1, 0x0018, 0x0008
		.4byte 0x798 @ subspriteOffset
		.2byte 0x0EF6, 0x0006, 0x0000, 0x0000, 0xFFD4, 0xFFB1, 0x0018, 0x0008
		.4byte 0x7C8 @ subspriteOffset
		.2byte 0x0EF7, 0x0004, 0x0000, 0x0000, 0xFFD4, 0xFFB1, 0x0018, 0x0008
		.4byte 0x7F8 @ subspriteOffset
		.2byte 0x0EF8, 0x0005, 0x0000, 0x0000, 0xFFD0, 0xFFB1, 0x0018, 0x0010
		.4byte 0x818 @ subspriteOffset
		.2byte 0x0EF9, 0x0004, 0x0000, 0x0000, 0xFFD0, 0xFFB1, 0x0014, 0x0010
		.4byte 0x840 @ subspriteOffset
		.2byte 0x06F2, 0x0006, 0x0000, 0x0000, 0xFFD0, 0xFFB3, 0x0018, 0x0008
		.4byte 0x860 @ subspriteOffset
		.2byte 0x06F3, 0x0005, 0x0000, 0x0000, 0xFFD3, 0xFFB3, 0x0018, 0x0008
		.4byte 0x890 @ subspriteOffset
		.2byte 0x06F4, 0x0003, 0x0000, 0x0000, 0xFFD0, 0xFFAB, 0x0013, 0x0008
		.4byte 0x8B8 @ subspriteOffset
		.2byte 0x06F5, 0x0005, 0x0000, 0x0000, 0xFFD0, 0xFFB3, 0x0013, 0x0008
		.4byte 0x8D0 @ subspriteOffset
		.2byte 0x06F6, 0x0004, 0x0000, 0x0000, 0xFFD0, 0xFFB3, 0x0013, 0x0008
		.4byte 0x8F8 @ subspriteOffset
		.2byte 0x06F7, 0x0004, 0x0000, 0x0000, 0xFFD3, 0xFFB3, 0x0018, 0x0000
		.4byte 0x918 @ subspriteOffset
		.2byte 0x06F8, 0x0004, 0x0000, 0x0000, 0xFFD3, 0xFFAB, 0x0018, 0x0018
		.4byte 0x938 @ subspriteOffset
		.2byte 0x06F9, 0x0007, 0x0000, 0x0000, 0xFFD0, 0xFFB3, 0x0018, 0x0008
		.4byte 0x958 @ subspriteOffset
		.2byte 0x9E5C, 0x0006, 0x0000, 0x0000, 0xFFD0, 0xFFC0, 0x0016, 0x0008
		.4byte 0x990 @ subspriteOffset
		.2byte 0x9E5D, 0x0006, 0x0000, 0x0000, 0xFFD0, 0xFFB0, 0x0019, 0x0010
		.4byte 0x9C0 @ subspriteOffset
		.2byte 0x9E5E, 0x0006, 0x0000, 0x0000, 0xFFE8, 0xFFC0, 0x0014, 0x0010
		.4byte 0x9F0 @ subspriteOffset
		.2byte 0x9E5F, 0x0006, 0x0000, 0x0000, 0xFFD8, 0xFFC0, 0x0018, 0x0020
		.4byte 0xA20 @ subspriteOffset
		.2byte 0x9E60, 0x0006, 0x0000, 0x0000, 0xFFD0, 0xFFC0, 0x0015, 0x0008
		.4byte 0xA50 @ subspriteOffset
		.2byte 0xE1B4, 0x0004, 0x0000, 0x0000, 0xFFD0, 0xFFC0, 0x0010, 0x0008
		.4byte 0xA80 @ subspriteOffset
		.2byte 0xE1B5, 0x0004, 0x0000, 0x0000, 0xFFD0, 0xFFB0, 0x0010, 0x0010
		.4byte 0xAA0 @ subspriteOffset
		.2byte 0xE1B6, 0x0004, 0x0000, 0x0000, 0xFFE8, 0xFFC0, 0x0010, 0x0010
		.4byte 0xAC0 @ subspriteOffset
		.2byte 0xE1B7, 0x0004, 0x0000, 0x0000, 0xFFD8, 0xFFC0, 0x0018, 0x0020
		.4byte 0xAE0 @ subspriteOffset
		.2byte 0xE1B8, 0x0004, 0x0000, 0x0000, 0xFFD0, 0xFFC0, 0x0010, 0x0008
		.4byte 0xB00 @ subspriteOffset
		.2byte 0x5A89, 0x0008, 0x0000, 0x0000, 0xFFD8, 0xFFB8, 0x0018, 0x0008
		.4byte 0xB20 @ subspriteOffset
		.2byte 0x5A8A, 0x000A, 0x0000, 0x0000, 0xFFC1, 0xFFA6, 0x0010, 0x0008
		.4byte 0xB60 @ subspriteOffset
		.2byte 0x5A8B, 0x000B, 0x0000, 0x0000, 0xFFB7, 0xFFA8, 0x0010, 0x0010
		.4byte 0xBB0 @ subspriteOffset
		.2byte 0x5A8C, 0x000A, 0x0000, 0x0000, 0xFFBE, 0xFFB1, 0x0018, 0x0010
		.4byte 0xC08 @ subspriteOffset
		.2byte 0x5A8D, 0x0007, 0x0000, 0x0000, 0xFFD0, 0xFFB9, 0x0020, 0x0008
		.4byte 0xC58 @ subspriteOffset
		.2byte 0x5A8E, 0x0005, 0x0000, 0x0000, 0xFFD1, 0xFFB8, 0x0018, 0x0010
		.4byte 0xC90 @ subspriteOffset
		.2byte 0x51FB, 0x0005, 0x0000, 0x0000, 0xFFD1, 0xFFBD, 0x0018, 0x0010
		.4byte 0xCB8 @ subspriteOffset
		.2byte 0x51FC, 0x0005, 0x0000, 0x0000, 0xFFD3, 0xFFC0, 0x0018, 0x0010
		.4byte 0xCE0 @ subspriteOffset
		.2byte 0x51FD, 0x0005, 0x0000, 0x0000, 0xFFD4, 0xFFBD, 0x0018, 0x0010
		.4byte 0xD08 @ subspriteOffset
		.2byte 0x51FE, 0x0004, 0x0000, 0x0000, 0xFFD8, 0xFFC0, 0x0018, 0x0010
		.4byte 0xD30 @ subspriteOffset
		.2byte 0x5A8F, 0x0006, 0x0000, 0x0000, 0xFFD8, 0xFFB8, 0x0018, 0x0008
		.4byte 0xD50 @ subspriteOffset
		.2byte 0x4914, 0x0008, 0x0000, 0x0000, 0xFFD8, 0xFFB8, 0x0018, 0x0008
		.4byte 0xD80 @ subspriteOffset
		.2byte 0x4915, 0x000A, 0x0000, 0x0000, 0xFFC1, 0xFFA6, 0x0010, 0x0008
		.4byte 0xDC0 @ subspriteOffset
		.2byte 0x4917, 0x000A, 0x0000, 0x0000, 0xFFC3, 0xFFA5, 0x0018, 0x0010
		.4byte 0xE10 @ subspriteOffset
		.2byte 0x4918, 0x000C, 0x0000, 0x0000, 0xFFAD, 0xFF8A, 0x0031, 0x001A
		.4byte 0xE60 @ subspriteOffset
		.2byte 0x4919, 0x0009, 0x0000, 0x0000, 0xFFD4, 0xFFC0, 0x0032, 0x0014
		.4byte 0xEC0 @ subspriteOffset
		.2byte 0x491A, 0x0008, 0x0000, 0x0000, 0xFFD8, 0xFFC0, 0x0032, 0x0014
		.4byte 0xF08 @ subspriteOffset
		.2byte 0x491B, 0x0008, 0x0000, 0x0000, 0xFFD8, 0xFFC0, 0x0032, 0x0014
		.4byte 0xF48 @ subspriteOffset
		.2byte 0x628F, 0x0006, 0x0000, 0x0000, 0xFFD8, 0xFFB8, 0x0018, 0x0018
		.4byte 0xF88 @ subspriteOffset
		.2byte 0x6290, 0x0009, 0x0000, 0x0000, 0xFFC9, 0xFFAC, 0x0018, 0x0010
		.4byte 0xFB8 @ subspriteOffset
		.2byte 0x6291, 0x000A, 0x0000, 0x0000, 0xFFB8, 0xFFA8, 0x0010, 0x0008
		.4byte 0x1000 @ subspriteOffset
		.2byte 0x6292, 0x0009, 0x0000, 0x0000, 0xFFCC, 0xFF9D, 0x002D, 0x0010
		.4byte 0x1050 @ subspriteOffset
		.2byte 0x6293, 0x0006, 0x0000, 0x0000, 0xFFD8, 0xFFB0, 0x0020, 0x0010
		.4byte 0x1098 @ subspriteOffset
		.2byte 0x6294, 0x0007, 0x0000, 0x0000, 0xFFD3, 0xFFB5, 0x0018, 0x0008
		.4byte 0x10C8 @ subspriteOffset
		.2byte 0x52BC, 0x0007, 0x0000, 0x0000, 0xFFD8, 0xFFB8, 0x0018, 0x0008
		.4byte 0x1100 @ subspriteOffset
		.2byte 0x52BD, 0x0007, 0x0000, 0x0000, 0xFFD8, 0xFFB8, 0x0018, 0x0008
		.4byte 0x1138 @ subspriteOffset
		.2byte 0x52BE, 0x0007, 0x0000, 0x0000, 0xFFD8, 0xFFB8, 0x0018, 0x0008
		.4byte 0x1170 @ subspriteOffset
		.2byte 0x52BF, 0x0007, 0x0000, 0x0000, 0xFFD8, 0xFFB8, 0x0018, 0x0008
		.4byte 0x11A8 @ subspriteOffset
		.2byte 0x6295, 0x0004, 0x0000, 0x0000, 0xFFD8, 0xFFB8, 0x0018, 0x0018
		.4byte 0x11E0 @ subspriteOffset
		.2byte 0x5114, 0x0006, 0x0000, 0x0000, 0xFFD8, 0xFFB8, 0x0018, 0x0018
		.4byte 0x1200 @ subspriteOffset
		.2byte 0x5115, 0x0009, 0x0000, 0x0000, 0xFFC9, 0xFFAC, 0x0018, 0x0010
		.4byte 0x1230 @ subspriteOffset
		.2byte 0x5117, 0x0009, 0x0000, 0x0000, 0xFFD8, 0xFFAF, 0x0020, 0x0010
		.4byte 0x1278 @ subspriteOffset
		.2byte 0x5118, 0x000B, 0x0000, 0x0000, 0xFFD8, 0xFF9A, 0x0032, 0x0010
		.4byte 0x12C0 @ subspriteOffset
		.2byte 0x5119, 0x0009, 0x0000, 0x0000, 0xFFD6, 0xFF99, 0x0033, 0x0010
		.4byte 0x1318 @ subspriteOffset
		.2byte 0x511A, 0x0009, 0x0000, 0x0000, 0xFFD7, 0xFF99, 0x0033, 0x0010
		.4byte 0x1360 @ subspriteOffset
		.2byte 0x511B, 0x0009, 0x0000, 0x0000, 0xFFD8, 0xFF99, 0x0033, 0x0010
		.4byte 0x13A8 @ subspriteOffset
		.2byte 0x2996, 0x0004, 0x0000, 0x0000, 0xFFD0, 0xFFB0, 0x0010, 0x0008
		.4byte 0x13F0 @ subspriteOffset
		.2byte 0x2997, 0x0004, 0x0000, 0x0000, 0xFFD0, 0xFFB0, 0x0025, 0x0018
		.4byte 0x1410 @ subspriteOffset
		.2byte 0x2196, 0x0003, 0x0000, 0x0000, 0xFFD0, 0xFFB0, 0x0010, 0x0010
		.4byte 0x1430 @ subspriteOffset
		.2byte 0x2197, 0x0004, 0x0000, 0x0000, 0xFFD0, 0xFFB0, 0x001B, 0x0010
		.4byte 0x1448 @ subspriteOffset
		.2byte 0x1985, 0x0006, 0x0000, 0x0000, 0xFFD0, 0xFFC0, 0x0010, 0x001D
		.4byte 0x1468 @ subspriteOffset
		.2byte 0x1986, 0x0006, 0x0000, 0x0000, 0xFFD0, 0xFFC0, 0x0010, 0x001D
		.4byte 0x1498 @ subspriteOffset
		.2byte 0x1987, 0x0007, 0x0000, 0x0000, 0xFFD0, 0xFFBE, 0x0010, 0x001D
		.4byte 0x14C8 @ subspriteOffset
		.2byte 0x1988, 0x0007, 0x0000, 0x0000, 0xFFD0, 0xFFBE, 0x0010, 0x001D
		.4byte 0x1500 @ subspriteOffset
		.2byte 0xF230, 0x0006, 0x0000, 0x0000, 0xFFCE, 0xFFB4, 0x0016, 0x0004
		.4byte 0x1538 @ subspriteOffset
		.2byte 0xF22E, 0x0005, 0x0000, 0x0000, 0xFFD0, 0xFFB0, 0x0020, 0x0010
		.4byte 0x1568 @ subspriteOffset
		.2byte 0x5D39, 0x0006, 0x0000, 0x0000, 0xFFCE, 0xFFB4, 0x0016, 0x0004
		.4byte 0x1590 @ subspriteOffset
		.2byte 0x5D37, 0x0003, 0x0000, 0x0000, 0xFFD0, 0xFFB0, 0x0018, 0x0010
		.4byte 0x15C0 @ subspriteOffset
		.2byte 0x705B, 0x0002, 0x0000, 0x0000, 0xFFD0, 0xFFB8, 0x0010, 0x0018
		.4byte 0x15D8 @ subspriteOffset
		.2byte 0x705C, 0x0004, 0x0000, 0x0000, 0xFFD8, 0xFFB0, 0x0018, 0x0008
		.4byte 0x15E8 @ subspriteOffset
		.2byte 0x705D, 0x0005, 0x0000, 0x0000, 0xFFD8, 0xFFB0, 0x0018, 0x0010
		.4byte 0x1608 @ subspriteOffset
		.2byte 0x705E, 0x0006, 0x0000, 0x0000, 0xFFD8, 0xFFB0, 0x0018, 0x0010
		.4byte 0x1630 @ subspriteOffset
		.2byte 0x705F, 0x0003, 0x0000, 0x0000, 0xFFD0, 0xFFA8, 0x0010, 0x0018
		.4byte 0x1660 @ subspriteOffset
		.2byte 0xB06D, 0x0006, 0x0000, 0x0000, 0xFFCE, 0xFFB4, 0x0016, 0x0004
		.4byte 0x1678 @ subspriteOffset
		.2byte 0xB06E, 0x0003, 0x0000, 0x0000, 0xFFD3, 0xFFB3, 0x0013, 0x0000
		.4byte 0x16A8 @ subspriteOffset
		.2byte 0xB06F, 0x0005, 0x0000, 0x0000, 0xFFEB, 0xFFC7, 0x0014, 0x0000
		.4byte 0x16C0 @ subspriteOffset
		.2byte 0xB070, 0x0005, 0x0000, 0x0000, 0xFFEB, 0xFFC8, 0x0014, 0x0000
		.4byte 0x16E8 @ subspriteOffset
		.2byte 0xA86D, 0x0003, 0x0000, 0x0000, 0xFFD0, 0xFFB0, 0x0018, 0x0010
		.4byte 0x1710 @ subspriteOffset
		.2byte 0xA86E, 0x0003, 0x0000, 0x0000, 0xFFD5, 0xFFB5, 0x0016, 0x001D
		.4byte 0x1728 @ subspriteOffset
		.2byte 0xA86F, 0x0003, 0x0000, 0x0000, 0xFFD4, 0xFFC0, 0x0016, 0x001D
		.4byte 0x1740 @ subspriteOffset
		.2byte 0xA870, 0x0004, 0x0000, 0x0000, 0xFFD5, 0xFFBE, 0x0016, 0x001D
		.4byte 0x1758 @ subspriteOffset
		.2byte 0xA871, 0x0009, 0x0000, 0x0000, 0xFFD5, 0xFFC1, 0x0016, 0x001D
		.4byte 0x1778 @ subspriteOffset
		.2byte 0xA872, 0x0007, 0x0000, 0x0000, 0xFFD9, 0xFFBC, 0x0019, 0x000C
		.4byte 0x17C0 @ subspriteOffset
		.2byte 0x59E2, 0x0009, 0x0000, 0x0000, 0xFFCF, 0xFF9E, 0x0023, 0x0006
		.4byte 0x17F8 @ subspriteOffset
		.2byte 0x5DE2, 0x0008, 0x0000, 0x0000, 0xFFCF, 0xFF9F, 0x0024, 0x0006
		.4byte 0x1840 @ subspriteOffset
		.2byte 0x61E2, 0x0008, 0x0000, 0x0000, 0xFFCF, 0xFFA0, 0x0025, 0x0006
		.4byte 0x1880 @ subspriteOffset
		.2byte 0x59E0, 0x0008, 0x0000, 0x0000, 0xFFD1, 0xFFB3, 0x0016, 0x0005
		.4byte 0x18C0 @ subspriteOffset
		.2byte 0x5DE0, 0x0007, 0x0000, 0x0000, 0xFFD1, 0xFFB3, 0x0018, 0x0005
		.4byte 0x1900 @ subspriteOffset
		.2byte 0x61E0, 0x0007, 0x0000, 0x0000, 0xFFD1, 0xFFB3, 0x001A, 0x0005
		.4byte 0x1938 @ subspriteOffset
		.2byte 0x129D, 0x0009, 0x0000, 0x0000, 0xFFCF, 0xFFBC, 0x0018, 0x0006
		.4byte 0x1970 @ subspriteOffset
		.2byte 0x169D, 0x0008, 0x0000, 0x0000, 0xFFCF, 0xFFBC, 0x0018, 0x0006
		.4byte 0x19B8 @ subspriteOffset
		.2byte 0x1A9D, 0x0009, 0x0000, 0x0000, 0xFFCF, 0xFFBC, 0x0018, 0x0006
		.4byte 0x19F8 @ subspriteOffset
		.2byte 0x1E9D, 0x0008, 0x0000, 0x0000, 0xFFCF, 0xFFBC, 0x0018, 0x0006
		.4byte 0x1A40 @ subspriteOffset
		.2byte 0x129B, 0x0009, 0x0000, 0x0000, 0xFFD1, 0xFFBD, 0x0019, 0x0005
		.4byte 0x1A80 @ subspriteOffset
		.2byte 0x169B, 0x000A, 0x0000, 0x0000, 0xFFD1, 0xFFBD, 0x0019, 0x0005
		.4byte 0x1AC8 @ subspriteOffset
		.2byte 0x1A9B, 0x000A, 0x0000, 0x0000, 0xFFD1, 0xFFBD, 0x0019, 0x0005
		.4byte 0x1B18 @ subspriteOffset
		.2byte 0x1E9B, 0x000A, 0x0000, 0x0000, 0xFFD1, 0xFFBD, 0x0019, 0x0005
		.4byte 0x1B68 @ subspriteOffset
	@ Unk1
		.byte 0x8A, 0xCA, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00
		.byte 0x9B, 0xA0, 0x08, 0x00, 0x20, 0x00, 0x00, 0x00
		.byte 0x5C, 0x9E, 0x01, 0x00, 0x40, 0x00, 0x00, 0x00
		.byte 0x5D, 0x9E, 0x01, 0x00, 0x44, 0x00, 0x00, 0x00
		.byte 0x5E, 0x9E, 0x01, 0x00, 0x48, 0x00, 0x00, 0x00
		.byte 0x5F, 0x9E, 0x01, 0x00, 0x4C, 0x00, 0x00, 0x00
		.byte 0x60, 0x9E, 0x01, 0x00, 0x50, 0x00, 0x00, 0x00
		.byte 0xB4, 0xE1, 0x01, 0x00, 0x54, 0x00, 0x00, 0x00
		.byte 0xB5, 0xE1, 0x01, 0x00, 0x58, 0x00, 0x00, 0x00
		.byte 0xB6, 0xE1, 0x01, 0x00, 0x5C, 0x00, 0x00, 0x00
		.byte 0xB7, 0xE1, 0x01, 0x00, 0x60, 0x00, 0x00, 0x00
		.byte 0xB8, 0xE1, 0x01, 0x00, 0x64, 0x00, 0x00, 0x00
		.byte 0x6F, 0xE2, 0x08, 0x00, 0x68, 0x00, 0x00, 0x00
		.byte 0x6D, 0xE2, 0x08, 0x00, 0x88, 0x00, 0x00, 0x00
		.byte 0x80, 0xB8, 0x08, 0x00, 0xA8, 0x00, 0x00, 0x00
		.byte 0x7E, 0xB8, 0x08, 0x00, 0xC8, 0x00, 0x00, 0x00
		.byte 0xD5, 0x9F, 0x0C, 0x00, 0xE8, 0x00, 0x00, 0x00
		.byte 0xD3, 0x9F, 0x0C, 0x00, 0x18, 0x01, 0x00, 0x00
		.byte 0x11, 0x41, 0x08, 0x00, 0x48, 0x01, 0x00, 0x00
		.byte 0x0F, 0x41, 0x08, 0x00, 0x68, 0x01, 0x00, 0x00
		.byte 0x87, 0x61, 0x03, 0x00, 0x88, 0x01, 0x00, 0x00
		.byte 0x85, 0x61, 0x03, 0x00, 0x94, 0x01, 0x00, 0x00
		.byte 0x85, 0x19, 0x02, 0x00, 0xA0, 0x01, 0x00, 0x00
		.byte 0x86, 0x19, 0x02, 0x00, 0xA8, 0x01, 0x00, 0x00
		.byte 0x87, 0x19, 0x01, 0x00, 0xB0, 0x01, 0x00, 0x00
		.byte 0x30, 0xF2, 0x01, 0x00, 0xB4, 0x01, 0x00, 0x00
		.byte 0x2E, 0xF2, 0x01, 0x00, 0xB8, 0x01, 0x00, 0x00
		.byte 0x39, 0x5D, 0x01, 0x00, 0xBC, 0x01, 0x00, 0x00
		.byte 0x37, 0x5D, 0x01, 0x00, 0xC0, 0x01, 0x00, 0x00
		.byte 0x5B, 0x70, 0x01, 0x00, 0xC4, 0x01, 0x00, 0x00
		.byte 0x5C, 0x70, 0x01, 0x00, 0xC8, 0x01, 0x00, 0x00
		.byte 0x5D, 0x70, 0x01, 0x00, 0xCC, 0x01, 0x00, 0x00
		.byte 0x5E, 0x70, 0x01, 0x00, 0xD0, 0x01, 0x00, 0x00
		.byte 0x5F, 0x70, 0x01, 0x00, 0xD4, 0x01, 0x00, 0x00
		.byte 0x69, 0x17, 0x14, 0x00, 0xD8, 0x01, 0x00, 0x00
		.byte 0x67, 0x17, 0x14, 0x00, 0x28, 0x02, 0x00, 0x00
		.byte 0x98, 0x63, 0x04, 0x00, 0x78, 0x02, 0x00, 0x00
		.byte 0x96, 0x63, 0x04, 0x00, 0x88, 0x02, 0x00, 0x00
		.byte 0x46, 0x92, 0x06, 0x00, 0x98, 0x02, 0x00, 0x00
		.byte 0x44, 0x92, 0x06, 0x00, 0xB0, 0x02, 0x00, 0x00
		.byte 0x99, 0x16, 0x01, 0x00, 0xC8, 0x02, 0x00, 0x00
		.byte 0x9A, 0x16, 0x01, 0x00, 0xCC, 0x02, 0x00, 0x00
	@ Subsprites
		.byte 0x04, 0x09 @ flip, shape
		.2byte -47, -36, (996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x09 @ flip, shape
		.2byte 15, -37, (996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x05 @ flip, shape
		.2byte -31, -32, (20 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 0, -32, (20 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, -40, (82 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -56, (452 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -24, (72 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -8, (971 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -16, (260 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -40, -21, (264 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x08 @ flip, shape
		.2byte 7, -67, (264 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -24, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -24, -16, (1548 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -40, (36 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 8, -48, (98 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -56, (1536 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -17, -11, (323 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x08 @ flip, shape
		.2byte -16, -77, (323 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -56, (192 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -24, (194 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -24, (903 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -40, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, -48, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -39, -68, (1184 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x08 @ flip, shape
		.2byte 7, -20, (1184 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -24, (196 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -24, -40, (164 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -24, -48, (1748 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 8, -32, (235 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -48, (76 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -16, (292 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -24, (74 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -8, (987 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x09 @ flip, shape
		.2byte -47, -36, (996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x09 @ flip, shape
		.2byte 15, -37, (996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -32, -32, (4 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, -40, (152 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x05 @ flip, shape
		.2byte 1, -32, (4 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -48, (140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -40, -21, (264 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x08 @ flip, shape
		.2byte 7, -67, (264 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte -24, -24, (196 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x09 @ flip, shape
		.2byte -8, -40, (164 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x01 @ flip, shape
		.2byte 8, -48, (1748 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x00 @ flip, shape
		.2byte -16, -32, (235 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -48, (204 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -11, (323 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x08 @ flip, shape
		.2byte -15, -77, (323 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte -8, -56, (192 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte -8, -24, (194 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x02 @ flip, shape
		.2byte -16, -24, (903 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -40, (160 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, -48, (688 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -39, -68, (1184 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x08 @ flip, shape
		.2byte 7, -21, (1184 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte -16, -24, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x00 @ flip, shape
		.2byte 16, -16, (1548 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x09 @ flip, shape
		.2byte -16, -40, (36 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x01 @ flip, shape
		.2byte -24, -48, (98 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -56, (256 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x05 @ flip, shape
		.2byte -31, -32, (20 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 0, -32, (20 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, -40, (82 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -56, (452 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -32, -28, (124 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 18, -28, (124 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -24, (72 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -16, (260 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -8, (971 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -24, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -24, -16, (1548 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -40, (36 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 8, -48, (98 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -56, (1536 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -56, (192 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -24, (194 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -24, (903 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (34 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, -56, (80 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -40, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, -48, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -24, (196 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -24, -40, (164 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -24, -48, (1748 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 8, -32, (235 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -48, (76 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 8, -16, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -16, (292 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -24, (74 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -8, (987 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x05 @ flip, shape
		.2byte 1, -32, (4 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, -40, (152 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -32, -32, (4 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -48, (140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte -24, -24, (196 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x09 @ flip, shape
		.2byte -8, -40, (164 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x01 @ flip, shape
		.2byte 8, -48, (1748 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x00 @ flip, shape
		.2byte -16, -32, (235 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -48, (204 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x01 @ flip, shape
		.2byte -24, -16, (134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte -8, -56, (192 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte -8, -24, (194 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x02 @ flip, shape
		.2byte -16, -24, (903 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x04 @ flip, shape
		.2byte -8, -8, (34 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x01 @ flip, shape
		.2byte -8, -56, (80 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -40, (160 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, -48, (688 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte -16, -24, (68 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x00 @ flip, shape
		.2byte 16, -16, (1548 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x09 @ flip, shape
		.2byte -16, -40, (36 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x01 @ flip, shape
		.2byte -24, -48, (98 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -56, (256 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -63, (832 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 2, -33, (1188 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -32, (512 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 8, -40, (576 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (268 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (315 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -60, (1604 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 7, -46, (1484 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -32, (516 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (592 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 16, -24, (580 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (168 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (299 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte -9, -52, (1184 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 10, -53, (782 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -32, (520 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 8, -32, (522 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (578 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (137 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -11, -31, (996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 9, -56, (832 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (524 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -32, (577 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (800 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (784 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (581 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -8, (1091 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -32, (996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 9, -57, (832 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (608 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, 0, (595 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -32, (594 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 8, -40, (585 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (268 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (315 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte -9, -53, (1184 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 12, -52, (776 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (612 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, 0, (674 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (168 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (299 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -60, (1604 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 7, -46, (1484 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (616 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -16, (588 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -16, 0, (601 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (137 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -62, (832 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 3, -32, (1188 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -32, (620 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -16, 0, (672 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (800 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (784 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 9, -57, (834 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (704 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (682 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 16, -40, (587 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -13, -37, (420 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -13, -45, (404 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -18, -29, (320 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -13, -24, (1600 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, -29, (959 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 5, -47, (1184 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (708 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, -8, (1124 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -24, (684 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -11, -24, (996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -5, -20, (1616 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -13, -37, (424 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -13, -45, (388 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 2, -33, (996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (712 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -16, -8, (692 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -13, -53, (396 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -7, -41, (826 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -2, -22, (1550 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -1, -35, (1028 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (716 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, -8, (1126 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -13, -37, (392 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -13, -45, (59 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -1, -50, (834 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 4, -27, (1549 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, -28, (943 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -1, -36, (1028 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (904 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, -8, (676 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -13, -37, (420 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -13, -45, (404 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -51, (834 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 5, -27, (1549 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 1, -32, (996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (327 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 0, -8, (680 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -13, -37, (424 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -13, -45, (388 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -7, -40, (826 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -2, -21, (1550 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 5, -48, (1184 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (972 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -24, (696 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -8, -8, (145 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -13, -53, (396 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -11, -25, (996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -5, -21, (1616 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 9, -56, (834 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 0, -8, (686 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, -8, (685 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (384 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 16, -40, (681 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -13, -37, (392 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -13, -45, (59 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -18, -28, (320 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -13, -23, (1600 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -9, -30, (927 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -32, (512 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 8, -40, (576 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (268 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (315 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -32, (516 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (592 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 16, -24, (580 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (168 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (299 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -32, (520 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 8, -32, (522 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (578 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (137 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (524 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -32, (577 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (800 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (784 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (581 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -8, (1091 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (608 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, 0, (595 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -32, (594 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 8, -40, (585 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (268 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (315 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (612 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, 0, (674 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (168 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (299 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (616 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -16, (588 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -16, 0, (601 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (137 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -32, (620 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -16, 0, (672 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -39, (800 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -12, -47, (784 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (704 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (682 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 16, -40, (587 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -13, -37, (420 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -13, -45, (404 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, -29, (959 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (708 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, -8, (1124 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -24, (684 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -13, -37, (424 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -13, -45, (388 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (712 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -16, -8, (692 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -13, -53, (396 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (716 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, -8, (1126 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -13, -37, (392 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -13, -45, (59 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, -28, (943 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (904 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, -8, (676 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -13, -37, (420 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -13, -45, (404 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (327 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 0, -8, (680 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -13, -37, (424 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -13, -45, (388 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (972 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -24, (696 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -8, -8, (145 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -13, -53, (396 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (384 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 16, -40, (681 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -13, -37, (392 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -13, -45, (59 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -9, -30, (927 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 0, -8, (686 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, -8, (685 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -32, (772 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -48, (868 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -21, -40, (908 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte 6, -40, (908 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 4, 0, (63 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -9, 0, (63 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -32, (899 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -48, (967 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (836 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 9, -36, (1002 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -2, -28, (1002 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -21, (684 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 4, -38, (838 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -48, (1634 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -48, (840 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -16, (870 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (852 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 3, -28, (838 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -2, -42, (778 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 8, -48, (910 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -48, (846 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -8, -16, (964 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -8, 0, (890 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 8, -32, (778 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -32, (960 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -48, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -20, -33, (780 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte 5, -33, (780 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 3, 0, (63 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, 0, (63 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -48, (868 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -32, (772 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -9, 0, (63 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 4, 0, (63 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -32, (899 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (836 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -48, (967 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -21, (684 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -48, (840 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -16, (870 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -48, (1634 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (852 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -48, (846 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 8, -48, (910 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -8, -16, (964 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -8, 0, (890 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -32, (960 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -48, (1000 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, 0, (63 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 3, 0, (63 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (896 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -6, -49, (1351 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 6, -51, (834 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -43, (834 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -3, -20, (1164 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (1088 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 8, -8, (1090 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 16, -27, (276 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -12, -40, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x08 @ flip, shape
		.2byte -31, -45, (1188 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (1031 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, -48, (1092 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (1094 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 2, -35, (1035 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x08 @ flip, shape
		.2byte -19, -58, (1188 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -45, (1960 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -9, -35, (1165 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -3, -32, (1035 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x08 @ flip, shape
		.2byte -41, -43, (1184 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x08 @ flip, shape
		.2byte -25, -56, (1184 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -16, -39, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -48, (1196 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -24, -40, (1100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, -56, (1108 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -16, (1096 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (1260 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 2, -39, (1134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -10, -47, (1262 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -6, -34, (1035 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -19, -39, (1128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 4, -63, (1194 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -34, -27, (1160 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (1036 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -16, -24, (1101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 8, -48, (1102 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (1276 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 8, -27, (1035 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -1, -39, (1142 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 0, -26, (1051 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x09 @ flip, shape
		.2byte -16, -37, (1128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x0A @ flip, shape
		.2byte -4, -55, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (1480 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, 0, (1135 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 24, -24, (1067 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -36, (1142 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 3, -22, (1035 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -4, -41, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -15, -40, (1128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (448 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (1150 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -42, (1351 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -4, -40, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x09 @ flip, shape
		.2byte -15, -35, (1128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (448 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (1150 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -42, (1351 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -4, -39, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x09 @ flip, shape
		.2byte -13, -32, (1128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (448 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (1150 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -42, (1351 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -4, -38, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -35, (1128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (448 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (1150 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -42, (1351 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -4, -38, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (448 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (1150 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -42, (1351 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (896 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -6, -49, (1351 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (1088 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 8, -8, (1090 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -12, -31, (124 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 16, -27, (276 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (896 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -6, -49, (1351 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 6, -51, (834 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -43, (834 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -3, -20, (1164 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (1088 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 8, -8, (1090 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 16, -27, (276 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -12, -40, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x08 @ flip, shape
		.2byte -31, -45, (1188 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (1094 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, -48, (1092 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (1031 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x08 @ flip, shape
		.2byte -19, -58, (1188 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 2, -35, (1035 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -45, (1960 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -9, -35, (1165 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -3, -32, (1035 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -19, -39, (1128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -11, -59, (330 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -29, -42, (330 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (1036 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -16, -24, (1101 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 8, -48, (1102 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (1276 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 8, -27, (1035 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -1, -39, (1142 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 0, -26, (1051 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -13, -32, (1128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 17, -20, (1028 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 10, -13, (320 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (1480 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, 0, (1135 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 24, -24, (1067 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -36, (1142 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 5, -24, (1134 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0D @ flip, shape
		.2byte -19, -54, (1920 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 13, -22, (1984 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 5, -22, (1732 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 21, 10, (1990 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -5, -35, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -12, -31, (1128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 18, -19, (1028 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 11, -12, (320 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, 0, (1135 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (1480 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 24, -24, (1067 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -36, (1142 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 3, -23, (1035 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -4, -36, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 18, -19, (1028 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 11, -12, (320 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, 0, (1135 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (1480 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 24, -24, (1067 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -36, (1142 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x00 @ flip, shape
		.2byte 4, -22, (1051 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 18, -19, (1028 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 11, -12, (320 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -4, -35, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, 0, (1135 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (1480 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 24, -24, (1067 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -36, (1142 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x00 @ flip, shape
		.2byte 4, -22, (1051 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -5, -56, (832 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 7, -48, (832 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (1280 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -8, -8, (1376 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -39, (1254 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -6, -46, (1250 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -48, (1284 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, 0, (1422 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x09 @ flip, shape
		.2byte -23, -52, (996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -39, (1254 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -7, -46, (1252 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x09 @ flip, shape
		.2byte -13, -43, (996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 5, -39, (1256 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -16, (1385 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -16, (1359 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x08 @ flip, shape
		.2byte -40, -52, (826 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (1288 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -24, -56, (1344 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -24, -40, (303 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -15, -41, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -11, -47, (1252 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x08 @ flip, shape
		.2byte -29, -36, (826 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -35, (1258 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 0, -8, (1354 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -8, -8, (1353 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x08 @ flip, shape
		.2byte -20, -67, (264 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -48, (1292 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, 0, (1420 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 24, -40, (1391 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 13, -35, (1180 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -7, -39, (168 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -7, -47, (299 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -16, (1356 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -16, (1358 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (1408 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 0, -48, (1448 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 24, -32, (319 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, 0, (1166 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -6, -37, (137 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -6, -45, (128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (1412 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -13, -43, (1128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -4, -41, (1632 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 2, -46, (1248 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 6, -33, (124 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (1389 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -8, (1635 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (1412 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -5, -41, (1632 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -3, -44, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 2, -46, (1248 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 6, -33, (124 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -8, (1635 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (1389 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (1412 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -5, -39, (1632 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -2, -43, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 2, -46, (1248 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 6, -33, (124 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -8, (1635 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (1389 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (1412 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -1, -44, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -3, -39, (1632 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 2, -46, (1248 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 6, -33, (124 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -8, (1635 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (1389 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (1412 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x04 @ flip, shape
		.2byte -3, -37, (1254 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -1, -45, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 2, -46, (1248 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 6, -33, (124 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -8, (1635 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (1389 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -8, -8, (1376 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (1280 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -39, (1254 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -6, -46, (1250 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 7, -48, (832 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -5, -56, (832 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -8, -8, (1376 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (1280 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -39, (1254 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -6, -46, (1250 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -48, (1284 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, 0, (1422 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x09 @ flip, shape
		.2byte -23, -52, (996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -39, (1254 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -7, -46, (1252 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x09 @ flip, shape
		.2byte -13, -43, (996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 5, -39, (1256 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -16, (1359 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -16, (1385 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -48, (1292 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, 0, (1420 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 24, -40, (1391 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -9, -65, (1136 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -7, -39, (168 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -7, -47, (299 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 8, -55, (1136 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -16, (1358 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -16, (1356 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 10, -70, (1604 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 18, -64, (1484 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 0, -48, (1448 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 24, -32, (319 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (1408 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, 0, (1166 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -6, -37, (137 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -6, -45, (128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -5, -69, (1860 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 27, -69, (1988 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 11, -53, (2006 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 11, -71, (1604 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 19, -65, (1484 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 0, -48, (1448 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 24, -32, (319 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (1408 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, 0, (1166 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -10, -40, (1128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 0, -38, (1632 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 4, -45, (1250 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 11, -71, (1604 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 19, -65, (1484 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 0, -48, (1448 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 24, -32, (319 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (1408 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, 0, (1166 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -9, -39, (1128 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 1, -39, (1632 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 4, -45, (1250 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 19, -65, (1484 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 11, -71, (1604 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 0, -48, (1448 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 24, -32, (319 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -32, (1408 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, 0, (1166 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -3, -38, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 1, -37, (1254 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 4, -45, (1250 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (1024 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, -48, (231 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 0, -8, (202 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -8, -8, (201 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 5, -16, (1601 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (1544 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, -48, (247 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -8, -8, (1376 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -32, (1472 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -48, (1347 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (836 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte -5, -35, (264 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -32, (1476 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -48, (1379 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (1540 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -35, (1610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -8, -35, (1609 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -11, (1551 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, -3, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -13, -32, (1580 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -48, (1556 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -35, (1610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -8, -35, (1609 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -11, (1551 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, -3, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -13, -32, (1582 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -48, (1556 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -35, (1610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -8, -35, (1609 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -11, (1551 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, -3, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -15, -50, (1612 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -8, -49, (1436 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, -50, (1612 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -35, (1610 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -8, -35, (1609 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -16, -11, (1551 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, -3, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -15, -50, (1614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, -49, (1438 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -15, -50, (1614 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -10, -52, (1542 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -2, -48, (1674 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 6, -44, (1672 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -18, -44, (1668 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -2, -12, (1734 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -10, -12, (1733 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 16, -42, (1029 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -48, (1664 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -16, (1728 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 8, -40, (1764 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -8, -32, (1760 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -10, -52, (1542 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -18, -44, (1668 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -2, -52, (1706 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 6, -28, (1676 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -2, -12, (1734 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -10, -12, (1733 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -48, (1664 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -16, (1728 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 8, -40, (1766 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -40, (1736 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -8, (1708 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -40, (1740 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -8, -48, (148 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -8, (1387 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 8, -8, (251 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -48, (456 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -16, (1678 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, 0, (114 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 8, -56, (1120 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 1, -18, (684 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -48, (460 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -16, (583 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -16, (200 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, 0, (700 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 0, -56, (132 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 10, -49, (124 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -56, (1792 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -24, (0 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -16, -8, (768 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -10, -52, (1542 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -18, -44, (1668 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -2, -52, (1706 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 6, -28, (1676 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -2, -12, (1734 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -10, -12, (1733 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -5, -28, (1192 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 11, -28, (1608 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -13, -45, (1856 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -5, -28, (1192 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 11, -28, (1608 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -4, -41, (1930 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 12, -41, (1932 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 12, -9, (675 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -5, -28, (1192 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 11, -28, (1608 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -4, -40, (1933 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 12, -40, (1935 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 12, -8, (144 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -48, (1664 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -16, -16, (1728 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 8, -40, (1766 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -10, -19, (1416 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -10, -3, (1564 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -11, -43, (1796 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -10, -3, (1564 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -10, -19, (1416 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -12, -32, (1800 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -10, -3, (1564 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -10, -19, (1416 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -11, -34, (1804 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -3, -2, (1369 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -7, -37, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte -10, -3, (1564 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -10, -19, (1416 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -11, -31, (8 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 4, -30, (935 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -4, -36, (1960 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x00 @ flip, shape
		.2byte 0, -22, (1035 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x00 @ flip, shape
		.2byte 2, -26, (1144 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x00 @ flip, shape
		.2byte -4, -28, (1144 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -7, -36, (1993 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -7, -4, (554 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x00 @ flip, shape
		.2byte 2, -32, (1144 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x00 @ flip, shape
		.2byte -4, -34, (1144 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -4, -42, (1960 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x00 @ flip, shape
		.2byte 0, -28, (1035 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -10, -30, (350 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -16, -66, (330 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 3, -30, (1188 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -17, -26, (1996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 4, -47, (1864 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -12, -36, (1894 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -7, -45, (1892 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 3, -35, (136 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, -30, (334 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -8, -31, (334 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -14, -65, (330 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 4, -30, (1188 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -17, -26, (1996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 6, -46, (1864 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -11, -36, (1894 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -5, -45, (1892 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -7, -31, (334 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 4, -35, (136 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -12, -64, (330 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 5, -30, (1188 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -17, -26, (1996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 8, -45, (1864 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -10, -36, (1894 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -3, -45, (1892 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte -6, -32, (334 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 5, -34, (136 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, -27, (1868 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte -10, -30, (1188 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -11, -35, (261 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -13, -31, (350 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -10, -45, (1865 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -13, -30, (189 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte 1, -61, (1194 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 4, -41, (2022 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, -27, (1868 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte -9, -30, (1188 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -10, -35, (261 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -12, -31, (350 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -8, -45, (1865 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte 3, -60, (1194 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 6, -40, (2022 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, -27, (1868 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte -8, -30, (1188 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -9, -35, (261 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -11, -31, (350 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -6, -45, (1865 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x0A @ flip, shape
		.2byte 5, -59, (1194 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 8, -39, (2022 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -2, -42, (778 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -8, -36, (1992 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -17, -26, (1996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -11, -36, (293 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -7, -38, (1254 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -34, (1558 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -5, -46, (1132 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 8, -34, (778 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte -11, -37, (189 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -2, -42, (778 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -8, -36, (1992 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -17, -26, (1996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -11, -36, (293 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -39, (1254 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -32, (1558 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -6, -46, (1250 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 8, -32, (778 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -2, -44, (778 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -8, -38, (1992 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -17, -26, (1996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -11, -36, (293 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -9, -39, (1254 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -32, (1558 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -46, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 8, -32, (778 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 2, -35, (136 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -2, -44, (778 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte -8, -38, (1992 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -17, -26, (1996 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -11, -36, (293 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -8, -40, (1254 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 1, -34, (1558 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -5, -46, (1250 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 8, -34, (778 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, -27, (1868 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -38, (1138 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -10, -35, (261 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 2, -41, (935 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -12, -33, (350 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -6, -45, (96 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -2, -35, (935 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 9, -36, (1002 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -2, -30, (1002 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -7, -35, (1254 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, -27, (1868 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -38, (1138 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -10, -35, (261 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 3, -40, (935 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -12, -31, (350 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -6, -45, (678 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -2, -36, (935 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 9, -36, (1002 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -2, -28, (1002 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x04 @ flip, shape
		.2byte -8, -39, (1140 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, -27, (1868 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -40, (1138 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -10, -35, (261 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 3, -39, (935 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -12, -31, (350 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -4, -45, (1106 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -2, -37, (935 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 9, -38, (1002 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -2, -28, (1002 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -7, -35, (1254 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte -15, -27, (1868 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 0, -40, (1138 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte -10, -35, (261 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 3, -40, (935 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte -12, -33, (350 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -5, -45, (678 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte -1, -36, (935 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 9, -38, (1002 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte -2, -30, (1002 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
	@ Unk2
		.byte 0x00, 0x00, 0x04, 0x00
		.byte 0x01, 0x00, 0x04, 0x00
		.byte 0x02, 0x00, 0x04, 0x00
		.byte 0x03, 0x00, 0x04, 0x00
		.byte 0x04, 0x00, 0x04, 0x00
		.byte 0x05, 0x00, 0x04, 0x00
		.byte 0x06, 0x00, 0x04, 0x00
		.byte 0x07, 0x00, 0x04, 0x00
		.byte 0x08, 0x00, 0x04, 0x00
		.byte 0x09, 0x00, 0x04, 0x00
		.byte 0x0A, 0x00, 0x04, 0x00
		.byte 0x0B, 0x00, 0x04, 0x00
		.byte 0x0C, 0x00, 0x04, 0x00
		.byte 0x0D, 0x00, 0x04, 0x00
		.byte 0x0E, 0x00, 0x04, 0x00
		.byte 0x0F, 0x00, 0x04, 0x00
		.byte 0x34, 0x00, 0x01, 0x00
		.byte 0x33, 0x00, 0x01, 0x00
		.byte 0x32, 0x00, 0x01, 0x00
		.byte 0x31, 0x00, 0x01, 0x00
		.byte 0x30, 0x00, 0x01, 0x00
		.byte 0x39, 0x00, 0x01, 0x00
		.byte 0x38, 0x00, 0x01, 0x00
		.byte 0x37, 0x00, 0x01, 0x00
		.byte 0x36, 0x00, 0x01, 0x00
		.byte 0x35, 0x00, 0x01, 0x00
		.byte 0x10, 0x00, 0x06, 0x00
		.byte 0x11, 0x00, 0x06, 0x00
		.byte 0x12, 0x00, 0x06, 0x00
		.byte 0x13, 0x00, 0x06, 0x00
		.byte 0x14, 0x00, 0x06, 0x00
		.byte 0x15, 0x00, 0x06, 0x00
		.byte 0x16, 0x00, 0x06, 0x00
		.byte 0x17, 0x00, 0x06, 0x00
		.byte 0x18, 0x00, 0x06, 0x00
		.byte 0x19, 0x00, 0x06, 0x00
		.byte 0x1A, 0x00, 0x06, 0x00
		.byte 0x1B, 0x00, 0x06, 0x00
		.byte 0x1C, 0x00, 0x06, 0x00
		.byte 0x1D, 0x00, 0x06, 0x00
		.byte 0x1E, 0x00, 0x06, 0x00
		.byte 0x1F, 0x00, 0x06, 0x00
		.byte 0x20, 0x00, 0x06, 0x00
		.byte 0x21, 0x00, 0x06, 0x00
		.byte 0x22, 0x00, 0x06, 0x00
		.byte 0x23, 0x00, 0x06, 0x00
		.byte 0x24, 0x00, 0x06, 0x00
		.byte 0x25, 0x00, 0x06, 0x00
		.byte 0x26, 0x00, 0x06, 0x00
		.byte 0x27, 0x00, 0x06, 0x00
		.byte 0x28, 0x00, 0x06, 0x00
		.byte 0x29, 0x00, 0x06, 0x00
		.byte 0x2A, 0x00, 0x06, 0x00
		.byte 0x2B, 0x00, 0x06, 0x00
		.byte 0x2C, 0x00, 0x06, 0x00
		.byte 0x2D, 0x00, 0x06, 0x00
		.byte 0x2E, 0x00, 0x06, 0x00
		.byte 0x2F, 0x00, 0x06, 0x00
		.byte 0x4C, 0x00, 0x05, 0x00
		.byte 0x4D, 0x00, 0x05, 0x00
		.byte 0x4E, 0x00, 0x10, 0x00
		.byte 0x4F, 0x00, 0x05, 0x00
		.byte 0x50, 0x00, 0x05, 0x00
		.byte 0x51, 0x00, 0x04, 0x00
		.byte 0x52, 0x00, 0x02, 0x00
		.byte 0x53, 0x00, 0x01, 0x00
		.byte 0x54, 0x00, 0x01, 0x00
		.byte 0x55, 0x00, 0x0A, 0x00
		.byte 0x56, 0x00, 0x05, 0x00
		.byte 0x38, 0x00, 0x25, 0x00
		.byte 0x3A, 0x00, 0x05, 0x00
		.byte 0x3B, 0x00, 0x05, 0x00
		.byte 0x3C, 0x00, 0x10, 0x00
		.byte 0x3D, 0x00, 0x05, 0x00
		.byte 0x3E, 0x00, 0x05, 0x00
		.byte 0x3F, 0x00, 0x04, 0x00
		.byte 0x40, 0x00, 0x02, 0x00
		.byte 0x41, 0x00, 0x01, 0x00
		.byte 0x42, 0x00, 0x01, 0x00
		.byte 0x43, 0x00, 0x0A, 0x00
		.byte 0x44, 0x00, 0x05, 0x00
		.byte 0x36, 0x00, 0x25, 0x00
		.byte 0x57, 0x00, 0x05, 0x00
		.byte 0x58, 0x00, 0x06, 0x00
		.byte 0x59, 0x00, 0x05, 0x00
		.byte 0x5A, 0x00, 0x02, 0x00
		.byte 0x5B, 0x00, 0x02, 0x00
		.byte 0x5C, 0x00, 0x02, 0x00
		.byte 0x5D, 0x00, 0x06, 0x00
		.byte 0x57, 0x00, 0x08, 0x00
		.byte 0x45, 0x00, 0x05, 0x00
		.byte 0x46, 0x00, 0x06, 0x00
		.byte 0x47, 0x00, 0x05, 0x00
		.byte 0x48, 0x00, 0x02, 0x00
		.byte 0x49, 0x00, 0x02, 0x00
		.byte 0x4A, 0x00, 0x02, 0x00
		.byte 0x4B, 0x00, 0x06, 0x00
		.byte 0x45, 0x00, 0x08, 0x00
		.byte 0x5E, 0x00, 0x0F, 0x00
		.byte 0x5F, 0x00, 0x07, 0x00
		.byte 0x4C, 0x00, 0x07, 0x00
		.byte 0x60, 0x00, 0x0F, 0x00
		.byte 0x61, 0x00, 0x07, 0x00
		.byte 0x3A, 0x00, 0x07, 0x00
		.byte 0x62, 0x00, 0x08, 0x00
		.byte 0x63, 0x00, 0x08, 0x00
		.byte 0x64, 0x00, 0x04, 0x00
		.byte 0x65, 0x00, 0x10, 0x00
		.byte 0x65, 0x00, 0x01, 0x00
		.byte 0x66, 0x00, 0x01, 0x00
		.byte 0x67, 0x00, 0x01, 0x00
		.byte 0x68, 0x00, 0x01, 0x00
		.byte 0x69, 0x00, 0x01, 0x00
		.byte 0x6E, 0x00, 0x01, 0x00
		.byte 0x6D, 0x00, 0x01, 0x00
		.byte 0x6C, 0x00, 0x01, 0x00
		.byte 0x6B, 0x00, 0x01, 0x00
		.byte 0x6A, 0x00, 0x01, 0x00
		.byte 0x6F, 0x00, 0x08, 0x00
		.byte 0x70, 0x00, 0x0C, 0x00
		.byte 0x72, 0x00, 0x25, 0x00
		.byte 0x71, 0x00, 0x1A, 0x00
		.byte 0x72, 0x00, 0x25, 0x00
		.byte 0x71, 0x00, 0x1A, 0x00
		.byte 0x72, 0x00, 0x25, 0x00
		.byte 0x71, 0x00, 0x1A, 0x00
		.byte 0x72, 0x00, 0x25, 0x00
		.byte 0x71, 0x00, 0x1A, 0x00
		.byte 0x72, 0x00, 0x25, 0x00
		.byte 0x71, 0x00, 0x1A, 0x00
		.byte 0x72, 0x00, 0x25, 0x00
		.byte 0x71, 0x00, 0x1A, 0x00
		.byte 0x72, 0x00, 0x25, 0x00
		.byte 0x71, 0x00, 0x1A, 0x00
		.byte 0x72, 0x00, 0x25, 0x00
		.byte 0x71, 0x00, 0x1A, 0x00
		.byte 0x72, 0x00, 0x25, 0x00
		.byte 0x71, 0x00, 0x1A, 0x00
		.byte 0x73, 0x00, 0x08, 0x00
		.byte 0x74, 0x00, 0x0C, 0x00
		.byte 0x75, 0x00, 0x25, 0x00
		.byte 0x76, 0x00, 0x1A, 0x00
		.byte 0x75, 0x00, 0x25, 0x00
		.byte 0x76, 0x00, 0x1A, 0x00
		.byte 0x75, 0x00, 0x25, 0x00
		.byte 0x76, 0x00, 0x1A, 0x00
		.byte 0x75, 0x00, 0x25, 0x00
		.byte 0x76, 0x00, 0x1A, 0x00
		.byte 0x75, 0x00, 0x25, 0x00
		.byte 0x76, 0x00, 0x1A, 0x00
		.byte 0x75, 0x00, 0x25, 0x00
		.byte 0x76, 0x00, 0x1A, 0x00
		.byte 0x75, 0x00, 0x25, 0x00
		.byte 0x76, 0x00, 0x1A, 0x00
		.byte 0x75, 0x00, 0x25, 0x00
		.byte 0x76, 0x00, 0x1A, 0x00
		.byte 0x75, 0x00, 0x25, 0x00
		.byte 0x76, 0x00, 0x1A, 0x00
		.byte 0x7A, 0x00, 0x09, 0x00
		.byte 0x7B, 0x00, 0x19, 0x00
		.byte 0x7A, 0x00, 0x09, 0x00
		.byte 0x79, 0x00, 0x19, 0x00
		.byte 0x7D, 0x00, 0x09, 0x00
		.byte 0x7E, 0x00, 0x19, 0x00
		.byte 0x7D, 0x00, 0x09, 0x00
		.byte 0x7C, 0x00, 0x19, 0x00
		.byte 0x80, 0x00, 0x0D, 0x00
		.byte 0x81, 0x00, 0x0E, 0x00
		.byte 0x80, 0x00, 0x0D, 0x00
		.byte 0x7F, 0x00, 0x0E, 0x00
		.byte 0x80, 0x00, 0x0D, 0x00
		.byte 0x82, 0x00, 0x14, 0x00
		.byte 0x84, 0x00, 0x0D, 0x00
		.byte 0x85, 0x00, 0x0E, 0x00
		.byte 0x84, 0x00, 0x0D, 0x00
		.byte 0x83, 0x00, 0x0E, 0x00
		.byte 0x84, 0x00, 0x0D, 0x00
		.byte 0x86, 0x00, 0x14, 0x00
		.byte 0x77, 0x00, 0x01, 0x00
		.byte 0x78, 0x00, 0x01, 0x00
	@ Tiles
		.incbin "data/spriteset/shaian.4bpp"
