SpriteSetFile24: @ 0x08C53994
	.2byte 659 @ palStart
	.2byte 76 @ metaspriteCount
	.2byte 1 @ unk1Count
	.2byte 266 @ subspriteCount
	.2byte 4 @ unk2Count
	.2byte 768 @ tileCount
	.4byte 0x00000020, 0x00000610, 0x00000618, 0x00000E68, 0x00000E78
	@ Metasprites
		.2byte 0xE907, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x0 @ subspriteOffset
		.2byte 0xE908, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x8 @ subspriteOffset
		.2byte 0xE909, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x10 @ subspriteOffset
		.2byte 0xE90A, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x18 @ subspriteOffset
		.2byte 0xE90B, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x20 @ subspriteOffset
		.2byte 0xE90C, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x28 @ subspriteOffset
		.2byte 0xE90D, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x30 @ subspriteOffset
		.2byte 0xE90E, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x38 @ subspriteOffset
		.2byte 0xE90F, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x40 @ subspriteOffset
		.2byte 0xE910, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x48 @ subspriteOffset
		.2byte 0x400B, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x50 @ subspriteOffset
		.2byte 0xE8A7, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x58 @ subspriteOffset
		.2byte 0xE8A8, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x60 @ subspriteOffset
		.2byte 0xE8A9, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x68 @ subspriteOffset
		.2byte 0xE8AA, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x70 @ subspriteOffset
		.2byte 0xE8AB, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x78 @ subspriteOffset
		.2byte 0xE8AC, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x80 @ subspriteOffset
		.2byte 0xE8AD, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x88 @ subspriteOffset
		.2byte 0xE8AE, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x90 @ subspriteOffset
		.2byte 0xE8AF, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0x98 @ subspriteOffset
		.2byte 0xE8B0, 0x0001, 0x0000, 0x0000, 0xFFF8, 0xFFF8, 0x0008, 0x0008
		.4byte 0xA0 @ subspriteOffset
		.2byte 0x0762, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00F0, 0x00A9
		.4byte 0xA8 @ subspriteOffset
		.2byte 0xBF8F, 0x0006, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B0, 0x0088
		.4byte 0xB8 @ subspriteOffset
		.2byte 0x956F, 0x0006, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B0, 0x0088
		.4byte 0xE8 @ subspriteOffset
		.2byte 0xACE9, 0x0004, 0x0000, 0x0000, 0x0000, 0x0000, 0x0068, 0x0090
		.4byte 0x118 @ subspriteOffset
		.2byte 0xACEA, 0x0003, 0x0000, 0x0000, 0x0000, 0x0000, 0x004C, 0x0080
		.4byte 0x138 @ subspriteOffset
		.2byte 0xBC2B, 0x0006, 0x0000, 0x0000, 0x0000, 0x0000, 0x00D0, 0x0048
		.4byte 0x150 @ subspriteOffset
		.2byte 0xBC23, 0x0006, 0x0000, 0x0000, 0x0000, 0x0000, 0x00D0, 0x0048
		.4byte 0x180 @ subspriteOffset
		.2byte 0xBC34, 0x0006, 0x0000, 0x0000, 0x0000, 0x0000, 0x00D0, 0x0068
		.4byte 0x1B0 @ subspriteOffset
		.2byte 0xBC2C, 0x0006, 0x0000, 0x0000, 0x0000, 0x0000, 0x00D0, 0x0068
		.4byte 0x1E0 @ subspriteOffset
		.2byte 0xBC36, 0x0007, 0x0000, 0x0000, 0x0000, 0x0000, 0x00D0, 0x0088
		.4byte 0x210 @ subspriteOffset
		.2byte 0xBC2E, 0x0007, 0x0000, 0x0000, 0x0000, 0x0000, 0x00D0, 0x0088
		.4byte 0x248 @ subspriteOffset
		.2byte 0xE821, 0x0006, 0x0000, 0x0000, 0x0000, 0x0000, 0x0098, 0x0070
		.4byte 0x280 @ subspriteOffset
		.2byte 0xE822, 0x0007, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A0, 0x0070
		.4byte 0x2B0 @ subspriteOffset
		.2byte 0xE823, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A8, 0x0070
		.4byte 0x2E8 @ subspriteOffset
		.2byte 0xE824, 0x0009, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B0, 0x0070
		.4byte 0x328 @ subspriteOffset
		.2byte 0x9F94, 0x0007, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A6, 0x0070
		.4byte 0x370 @ subspriteOffset
		.2byte 0xA069, 0x0006, 0x0000, 0x0000, 0x0000, 0x0000, 0x00AB, 0x0070
		.4byte 0x3A8 @ subspriteOffset
		.2byte 0x2AFB, 0x0006, 0x0000, 0x0000, 0x0000, 0x0000, 0x008C, 0x0070
		.4byte 0x3D8 @ subspriteOffset
		.2byte 0x3A02, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A4, 0x0060
		.4byte 0x408 @ subspriteOffset
		.2byte 0x3A03, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A4, 0x0058
		.4byte 0x418 @ subspriteOffset
		.2byte 0x3A04, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A4, 0x0060
		.4byte 0x428 @ subspriteOffset
		.2byte 0x3A05, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A4, 0x0060
		.4byte 0x438 @ subspriteOffset
		.2byte 0x3A06, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A4, 0x0058
		.4byte 0x448 @ subspriteOffset
		.2byte 0x3A07, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A4, 0x0060
		.4byte 0x458 @ subspriteOffset
		.2byte 0x3A08, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A4, 0x0060
		.4byte 0x468 @ subspriteOffset
		.2byte 0x3A09, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A4, 0x0060
		.4byte 0x478 @ subspriteOffset
		.2byte 0x3A0A, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A4, 0x0060
		.4byte 0x488 @ subspriteOffset
		.2byte 0x3A0B, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00A4, 0x0058
		.4byte 0x498 @ subspriteOffset
		.2byte 0xAC89, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B8, 0x0070
		.4byte 0x4A8 @ subspriteOffset
		.2byte 0x9013, 0x0004, 0x0000, 0x0000, 0x0000, 0x0000, 0x0087, 0x0058
		.4byte 0x4E8 @ subspriteOffset
		.2byte 0x2D76, 0x0008, 0x0000, 0x0000, 0xFFE3, 0xFFF8, 0x00ED, 0x0038
		.4byte 0x508 @ subspriteOffset
		.2byte 0x2C33, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x0090, 0x0028
		.4byte 0x548 @ subspriteOffset
		.2byte 0x2C39, 0x0001, 0x0000, 0x0000, 0x0000, 0x0000, 0x00E8, 0x0028
		.4byte 0x550 @ subspriteOffset
		.2byte 0x4AD7, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x005C, 0x0044
		.4byte 0x558 @ subspriteOffset
		.2byte 0x4AF7, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C0, 0x0044
		.4byte 0x568 @ subspriteOffset
		.2byte 0x4B17, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x005C, 0x0074
		.4byte 0x578 @ subspriteOffset
		.2byte 0x4B37, 0x0002, 0x0000, 0x0000, 0x0000, 0x0000, 0x00C0, 0x0074
		.4byte 0x588 @ subspriteOffset
		.2byte 0x54E5, 0x0007, 0x0000, 0x0000, 0xFFE0, 0xFFFE, 0x0060, 0x004E
		.4byte 0x598 @ subspriteOffset
		.2byte 0x5505, 0x0007, 0x0000, 0x0000, 0x0000, 0xFFFE, 0x00F0, 0x0046
		.4byte 0x5D0 @ subspriteOffset
		.2byte 0x5525, 0x0007, 0x0000, 0x0000, 0xFFE0, 0x0000, 0x0060, 0x007E
		.4byte 0x608 @ subspriteOffset
		.2byte 0x5545, 0x0007, 0x0000, 0x0000, 0x0000, 0x0000, 0x00F0, 0x0076
		.4byte 0x640 @ subspriteOffset
		.2byte 0xE8D1, 0x0001, 0x0000, 0x0000, 0xFFF0, 0xFFF0, 0x0010, 0x0010
		.4byte 0x678 @ subspriteOffset
		.2byte 0xE889, 0x0001, 0x0000, 0x0000, 0xFFF0, 0xFFF0, 0x0010, 0x0010
		.4byte 0x680 @ subspriteOffset
		.2byte 0xE88A, 0x0001, 0x0000, 0x0000, 0xFFF0, 0xFFF0, 0x0010, 0x0010
		.4byte 0x688 @ subspriteOffset
		.2byte 0xE88B, 0x0001, 0x0000, 0x0000, 0xFFF0, 0xFFF0, 0x0010, 0x0010
		.4byte 0x690 @ subspriteOffset
		.2byte 0xE88C, 0x0001, 0x0000, 0x0000, 0xFFF0, 0xFFF0, 0x0010, 0x0010
		.4byte 0x698 @ subspriteOffset
		.2byte 0x583E, 0x0009, 0x0000, 0x0000, 0x0000, 0x0000, 0x00BF, 0x0050
		.4byte 0x6A0 @ subspriteOffset
		.2byte 0xA1F9, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B3, 0x0050
		.4byte 0x6E8 @ subspriteOffset
		.2byte 0x07C2, 0x0007, 0x0000, 0x0000, 0x0000, 0x0000, 0x00AA, 0x0050
		.4byte 0x728 @ subspriteOffset
		.2byte 0xCEC3, 0x0007, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B2, 0x0070
		.4byte 0x760 @ subspriteOffset
		.2byte 0xCEBB, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x00B9, 0x0070
		.4byte 0x798 @ subspriteOffset
		.2byte 0x713F, 0x0002, 0x0000, 0x0000, 0xFFE9, 0x0000, 0x0049, 0x005D
		.4byte 0x7D8 @ subspriteOffset
		.2byte 0xC0ED, 0x0002, 0x0000, 0x0000, 0xFFE8, 0x0000, 0x0048, 0x005D
		.4byte 0x7E8 @ subspriteOffset
		.2byte 0xCABB, 0x0003, 0x0000, 0x0000, 0xFFE7, 0x0000, 0x004F, 0x005D
		.4byte 0x7F8 @ subspriteOffset
		.2byte 0x52B9, 0x0008, 0x0000, 0x0000, 0x0000, 0x0000, 0x00BC, 0x0070
		.4byte 0x810 @ subspriteOffset
	@ Unk1
		.byte 0x3F, 0x8F, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00
	@ Subsprites
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (704 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (705 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (706 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (707 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (708 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (709 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (710 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (711 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (712 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (713 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (714 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (704 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (705 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (706 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (707 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (708 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (709 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (710 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (711 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (712 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 0, 0, (713 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 176, 137, (248 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 208, 137, (252 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 72, 104, (100 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 136, 104, (104 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 64, 104, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x02 @ flip, shape
		.2byte 104, 104, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 128, 104, (64 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x02 @ flip, shape
		.2byte 168, 104, (64 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 72, 104, (100 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 136, 104, (104 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 64, 104, (64 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x02 @ flip, shape
		.2byte 104, 104, (64 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 128, 104, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x02 @ flip, shape
		.2byte 168, 104, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 56, 96, (256 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x09 @ flip, shape
		.2byte 56, 112, (256 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x04 @ flip, shape
		.2byte 88, 96, (256 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x0C, 0x04 @ flip, shape
		.2byte 88, 112, (256 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 60, 104, (98 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 64, 96, (143 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x00 @ flip, shape
		.2byte 64, 120, (143 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 32, 40, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 56, 40, (65 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 88, 40, (0 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 120, 40, (8 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 152, 40, (65 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x09 @ flip, shape
		.2byte 176, 40, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 32, 40, (64 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 56, 40, (65 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 88, 40, (0 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 120, 40, (8 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 152, 40, (65 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x09 @ flip, shape
		.2byte 176, 40, (64 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 32, 72, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x09 @ flip, shape
		.2byte 176, 72, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 64, 72, (44 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 96, 72, (69 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 128, 72, (73 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 160, 72, (40 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 32, 72, (64 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x09 @ flip, shape
		.2byte 176, 72, (64 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 64, 72, (44 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 96, 72, (69 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 128, 72, (73 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 160, 72, (40 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 40, 104, (12 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 72, 104, (32 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 104, 104, (36 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 136, 104, (36 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 168, 104, (40 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 32, 104, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x02 @ flip, shape
		.2byte 200, 104, (64 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 40, 104, (12 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 72, 104, (32 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 104, 104, (36 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 136, 104, (36 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 168, 104, (40 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 32, 104, (64 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x02 @ flip, shape
		.2byte 200, 104, (64 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 72, 64, (370 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 104, 64, (374 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 136, 64, (378 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 72, 80, (402 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 104, 80, (406 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 136, 80, (410 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 72, 64, (370 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 104, 64, (374 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 72, 80, (402 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 104, 80, (406 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 136, 64, (378 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 136, 80, (410 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 152, 80, (303 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 72, 64, (370 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 104, 64, (374 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 72, 80, (402 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 104, 80, (406 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 136, 64, (378 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 136, 80, (410 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 152, 80, (303 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 160, 80, (303 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 72, 64, (370 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 104, 64, (374 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 72, 80, (402 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 104, 80, (406 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 136, 64, (378 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 136, 80, (410 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 152, 80, (303 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 160, 80, (303 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 168, 80, (303 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 78, 64, (261 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 110, 64, (265 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 142, 64, (269 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 78, 80, (293 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 110, 80, (297 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 142, 80, (301 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 158, 64, (271 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 75, 64, (320 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 107, 64, (324 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 139, 64, (328 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 75, 80, (352 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 107, 80, (356 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 139, 80, (360 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 108, 64, (380 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 108, 80, (412 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 76, 64, (332 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 76, 80, (364 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 60, 64, (370 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 60, 80, (402 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 148, 64, (368 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x01 @ flip, shape
		.2byte 148, 80, (368 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 148, 64, (400 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 153, 80, (453 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 148, 64, (418 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 148, 80, (450 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 148, 64, (432 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 148, 80, (454 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 148, 64, (420 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 156, 80, (453 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 148, 64, (422 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 148, 80, (454 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 148, 64, (424 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x08, 0x01 @ flip, shape
		.2byte 148, 80, (368 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 148, 64, (426 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 148, 80, (458 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 148, 64, (428 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 148, 80, (460 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 148, 72, (430 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x01 @ flip, shape
		.2byte 148, 64, (368 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 56, 64, (464 | 4 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 56, 80, (496 | 4 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 88, 64, (468 | 4 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 88, 80, (500 | 4 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 120, 64, (472 | 4 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 152, 64, (476 | 4 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 152, 80, (508 | 4 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 120, 80, (504 | 4 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 110, 64, (110 | 4 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 110, 80, (142 | 4 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 119, 64, (110 | 4 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x00 @ flip, shape
		.2byte 119, 80, (142 | 4 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 3, 24, (256 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 35, 24, (257 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 67, 24, (257 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 99, 24, (257 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 131, 24, (257 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 163, 24, (257 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x08 @ flip, shape
		.2byte 205, 24, (256 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 192, 24, (259 | 0 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 136, 32, (96 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 224, 32, (97 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 44, 36, (171 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 76, 36, (108 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 144, 36, (171 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 176, 36, (108 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 44, 84, (171 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 76, 84, (108 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 144, 84, (171 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 176, 84, (108 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 88, 46, (170 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 72, 46, (168 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x09 @ flip, shape
		.2byte 64, 30, (128 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 40, 46, (164 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 8, 46, (160 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x09 @ flip, shape
		.2byte 0, 30, (136 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x09 @ flip, shape
		.2byte 32, 30, (132 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 144, 30, (128 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 144, 38, (144 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 176, 38, (148 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 176, 30, (132 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 208, 38, (152 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 208, 30, (136 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 224, 38, (154 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 88, 94, (170 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 72, 94, (168 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x09 @ flip, shape
		.2byte 64, 78, (128 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 40, 94, (164 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 8, 94, (160 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x09 @ flip, shape
		.2byte 0, 78, (136 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x04, 0x09 @ flip, shape
		.2byte 32, 78, (132 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 144, 78, (128 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 144, 86, (144 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x08 @ flip, shape
		.2byte 176, 86, (148 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 176, 78, (132 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x0A @ flip, shape
		.2byte 208, 86, (152 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x05 @ flip, shape
		.2byte 208, 78, (136 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x06 @ flip, shape
		.2byte 224, 86, (154 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 0, 0, (622 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 0, 0, (224 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 0, 0, (226 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 0, 0, (228 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 0, 0, (230 | 1 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 116, 64, (554 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 130, 64, (556 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 145, 64, (512 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 161, 64, (552 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 175, 64, (556 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 48, 64, (550 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 64, 64, (558 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 78, 64, (554 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 92, 64, (522 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 118, 64, (552 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 133, 64, (576 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 148, 64, (512 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 163, 64, (544 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 59, 64, (524 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 72, 64, (546 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 87, 64, (556 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 102, 64, (518 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 117, 64, (556 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 74, 64, (578 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 90, 64, (512 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 104, 64, (524 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 142, 64, (580 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 130, 64, (580 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 154, 64, (580 | 5 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 162, 96, (546 | 7 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 123, 96, (526 | 7 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 147, 96, (548 | 7 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 62, 96, (514 | 7 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 77, 96, (544 | 7 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 93, 96, (548 | 7 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 108, 96, (516 | 7 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 140, 96, (548 | 6 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 155, 96, (520 | 6 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 169, 96, (520 | 6 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 55, 96, (514 | 6 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 70, 96, (544 | 6 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 86, 96, (548 | 6 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 101, 96, (516 | 6 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 116, 96, (526 | 6 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 9, 61, (608 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 41, 61, (612 | 2 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 8, 61, (640 | 4 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 40, 61, (644 | 4 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 7, 61, (672 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x09 @ flip, shape
		.2byte 39, 61, (676 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x02 @ flip, shape
		.2byte 71, 61, (680 | 3 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 58, 96, (584 | 7 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 75, 96, (512 | 7 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 90, 96, (586 | 7 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 114, 96, (584 | 7 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 130, 96, (548 | 7 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 145, 96, (588 | 7 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 159, 96, (518 | 7 << 12) @ x, y, (tileIdx | (palID << 12))
		.byte 0x00, 0x04 @ flip, shape
		.2byte 172, 96, (590 | 7 << 12) @ x, y, (tileIdx | (palID << 12))
	@ Unk2
		.byte 0x20, 0x00, 0x40, 0x00
		.byte 0x21, 0x00, 0x40, 0x00
		.byte 0x22, 0x00, 0x40, 0x00
		.byte 0x23, 0x00, 0x40, 0x00
	@ Tiles
		.incbin "data/spriteset/ui_link.4bpp"
