#ifndef GUARD_ZOKTAI_MAGIC_H
#define GUARD_ZOKTAI_MAGIC_H

enum MagicCategory {
  MC_LUNA,  // 月光魔法(MAGIC_SOL, MAGIC_DARK, MAGIC_FLAME, MAGIC_FROST, MAGIC_CLOUD, MAGIC_EARTH, MAGIC_TRANSFORM, MAGIC_RISING_SUN)
  MC_SOL,   // 太陽魔法(MAGIC_FREEZE, MAGIC_DASH, MAGIC_HEALING, MAGIC_DYNAMITE)
  MC_DARK,  // 暗黒魔法(MAGIC_COFFIN, MAGIC_BAT, MAGIC_RAT, MAGIC_WOLF)
};

#endif  // GUARD_ZOKTAI_MAGIC_H
