@ Generated by tools/dumper/collisionmap.ts
@ Do not edit this file manually.

.include "asm/macros.inc"

.balign 4, 0
.section .rodata

.global gCollisionMapsDirectory
gCollisionMapsDirectory: @ 0x087B260C
  .4byte 246 @ entry count
  .4byte 0x10, 0x1FC, 0x5D4

@ FileIDs
  .2byte 0x050F, 0x051F, 0x052F, 0x053F, 0x054F, 0x072C, 0x082E, 0x08AE, 0x092E, 0x09AE, 0x0A2E, 0x0AAE, 0x0BAE, 0x0C2E, 0x0CAE, 0x0F0C
  .2byte 0x0F63, 0x11B6, 0x11C6, 0x11D6, 0x11E6, 0x11F6, 0x1206, 0x1313, 0x164C, 0x17CE, 0x17D2, 0x17D6, 0x182E, 0x1A97, 0x2EF8, 0x2F08
  .2byte 0x2F18, 0x2F28, 0x2F38, 0x2F48, 0x2F58, 0x2F63, 0x2F68, 0x3313, 0x33C2, 0x33D2, 0x33E2, 0x33F2, 0x3402, 0x3412, 0x3422, 0x3432
  .2byte 0x3442, 0x3452, 0x35C2, 0x35D2, 0x35E2, 0x37CE, 0x37D2, 0x37D6, 0x3A97, 0x3D33, 0x3DB3, 0x3E33, 0x3EB3, 0x3F33, 0x3FB3, 0x4033
  .2byte 0x40B3, 0x4133, 0x41B3, 0x43B7, 0x4D33, 0x4DB3, 0x4E33, 0x4EB3, 0x4F33, 0x5313, 0x57CE, 0x57D2, 0x57D6, 0x5A97, 0x5F34, 0x677F
  .2byte 0x6A7F, 0x6AB0, 0x77CE, 0x77D2, 0x77D6, 0x78F6, 0x7976, 0x79F6, 0x79FB, 0x7A0B, 0x7A13, 0x7A1B, 0x7A23, 0x7A2B, 0x7A33, 0x7A3B
  .2byte 0x7A43, 0x7A4B, 0x7A53, 0x7A63, 0x7A76, 0x7A97, 0x7AF6, 0x7B76, 0x7BBA, 0x7BF6, 0x7C76, 0x7CF6, 0x7D2E, 0x7D76, 0x7E9E, 0x7F34
  .2byte 0x7FC6, 0x88F6, 0x8976, 0x89F6, 0x8A76, 0x8AF6, 0x8B76, 0x8BF6, 0x8C76, 0x8CF6, 0x8F62, 0x97CD, 0x97CE, 0x97D1, 0x97D2, 0x97D5
  .2byte 0x97D6, 0x97D9, 0x9A97, 0x9F34, 0xA21B, 0xAF62, 0xB088, 0xB26B, 0xB381, 0xB391, 0xB3A1, 0xB3B1, 0xB3C1, 0xB3D1, 0xB4F1, 0xB66F
  .2byte 0xB673, 0xB677, 0xB67B, 0xB67F, 0xB683, 0xB687, 0xB7CD, 0xB7CE, 0xB7D1, 0xB7D2, 0xB7D5, 0xB7D6, 0xB889, 0xB909, 0xB989, 0xBA09
  .2byte 0xBA89, 0xBA97, 0xBB09, 0xBB2F, 0xBB89, 0xBC09, 0xBC89, 0xBD09, 0xBFB9, 0xC039, 0xC12F, 0xC4C4, 0xC4C8, 0xC4CC, 0xC4D0, 0xC4D4
  .2byte 0xC4D8, 0xC4DC, 0xC4E0, 0xC4E4, 0xC889, 0xC909, 0xC989, 0xCA09, 0xCA89, 0xCB09, 0xCB89, 0xCD05, 0xCD09, 0xCD0D, 0xCD11, 0xCD15
  .2byte 0xCD19, 0xCD1D, 0xCD21, 0xCD25, 0xCD29, 0xCD85, 0xCD89, 0xCD8D, 0xCD91, 0xCD95, 0xCD99, 0xCD9D, 0xCDA1, 0xCDA5, 0xCDA9, 0xCE05
  .2byte 0xCE09, 0xCE0D, 0xCE11, 0xCE15, 0xCE19, 0xCE1D, 0xCF62, 0xD312, 0xD461, 0xD7CD, 0xD7D1, 0xD7D5, 0xD909, 0xD9EF, 0xD9FF, 0xDA0F
  .2byte 0xDA1F, 0xDA2F, 0xDA3F, 0xDA97, 0xEAC3, 0xF312, 0xF38C, 0xF7CD, 0xF7D1, 0xF7D5, 0xF82D, 0xF8AD, 0xF92D, 0xF9AD, 0xFA2D, 0xFA96
  .2byte 0xFA97, 0xFAAD, 0xFB2D, 0xFBAD, 0xFC2D, 0xFCAD

@ FileOffsets
  .4byte 0x000005D4, 0x00000A10, 0x00001470, 0x00001548, 0x00001D80, 0x00001F88, 0x00002188, 0x00002C3C
  .4byte 0x000033C8, 0x00003750, 0x00004000, 0x00004144, 0x00004480, 0x00004C54, 0x00005118, 0x00005664
  .4byte 0x00005A14, 0x00005BF0, 0x00006C24, 0x000077D8, 0x000080D0, 0x00008B8C, 0x00009E1C, 0x0000B0A0
  .4byte 0x0000B254, 0x0000B5C8, 0x0000B820, 0x0000B9A8, 0x0000BF5C, 0x0000C2A0, 0x0000C860, 0x0000C9CC
  .4byte 0x0000D2DC, 0x0000D710, 0x0000DA8C, 0x0000DE78, 0x0000E440, 0x0000E5EC, 0x0000EAAC, 0x0000EB38
  .4byte 0x0000EDF8, 0x0000F14C, 0x0000F364, 0x0000F728, 0x0000FA0C, 0x0000FCB0, 0x0000FFE0, 0x000102FC
  .4byte 0x0001074C, 0x00010AA4, 0x00010D98, 0x000111A4, 0x00011384, 0x00011734, 0x000118D0, 0x00011D80
  .4byte 0x000123F8, 0x00012C08, 0x00012E54, 0x000130F8, 0x00013338, 0x000135CC, 0x00013890, 0x00013BB4
  .4byte 0x00013DE4, 0x00014074, 0x0001448C, 0x00014710, 0x00014A68, 0x00014EE0, 0x000154D8, 0x000159D4
  .4byte 0x00015DB0, 0x00015F90, 0x000164F4, 0x000167C0, 0x00016A8C, 0x00016E3C, 0x000173B4, 0x000180A0
  .4byte 0x000182A0, 0x00018478, 0x00018638, 0x000187EC, 0x00018BEC, 0x000190F8, 0x0001952C, 0x00019BFC
  .4byte 0x00019FB0, 0x0001A358, 0x0001A9A4, 0x0001B34C, 0x0001BA80, 0x0001C858, 0x0001CBEC, 0x0001D1BC
  .4byte 0x0001D748, 0x0001DAE0, 0x0001DF40, 0x0001E488, 0x0001E620, 0x0001F750, 0x0001FE1C, 0x000206F4
  .4byte 0x00020F88, 0x00021084, 0x000217C4, 0x00022014, 0x0002254C, 0x00022614, 0x00022C7C, 0x00022D88
  .4byte 0x00023B48, 0x00024020, 0x00024654, 0x00024E5C, 0x00025494, 0x00025960, 0x00025FF8, 0x00026388
  .4byte 0x000264A4, 0x00026724, 0x00026890, 0x00027954, 0x00027A64, 0x00027D98, 0x00028414, 0x00028888
  .4byte 0x00028B88, 0x0002907C, 0x00029698, 0x00029C9C, 0x0002A5DC, 0x0002A748, 0x0002A93C, 0x0002AA70
  .4byte 0x0002AEF0, 0x0002B448, 0x0002BAE8, 0x0002BBE4, 0x0002C2A8, 0x0002C8D8, 0x0002CC64, 0x0002CE1C
  .4byte 0x0002D660, 0x0002E258, 0x0002E7B0, 0x0002EBC4, 0x0002EF80, 0x0002F334, 0x0002FA64, 0x0002FD74
  .4byte 0x00030310, 0x00030908, 0x00030AF4, 0x00030CC4, 0x00030FF0, 0x0003121C, 0x000314DC, 0x00031658
  .4byte 0x000318A8, 0x000319B4, 0x00031D80, 0x00031E88, 0x0003204C, 0x000321F8, 0x000325B8, 0x00032968
  .4byte 0x00032BC4, 0x00032D60, 0x00032F2C, 0x00033154, 0x000334C4, 0x000338A8, 0x00033E24, 0x00034684
  .4byte 0x00034860, 0x00034E10, 0x0003535C, 0x000359D4, 0x00036158, 0x00036280, 0x00036418, 0x00036688
  .4byte 0x0003696C, 0x00036A74, 0x00036B6C, 0x00036CE8, 0x000370C0, 0x00037670, 0x00037C7C, 0x00037DC4
  .4byte 0x00038850, 0x00038A38, 0x00039114, 0x0003986C, 0x000399FC, 0x00039DE8, 0x0003A5EC, 0x0003A978
  .4byte 0x0003B20C, 0x0003B374, 0x0003B93C, 0x0003BD0C, 0x0003BE9C, 0x0003C548, 0x0003C6EC, 0x0003CF04
  .4byte 0x0003D134, 0x0003D888, 0x0003DB58, 0x0003E070, 0x0003E454, 0x0003E500, 0x0003E8B8, 0x0003EAB0
  .4byte 0x0003F138, 0x0003F1E4, 0x0003F4A0, 0x0003F980, 0x0003FB10, 0x0003FC3C, 0x0003FF70, 0x000403A0
  .4byte 0x00040A9C, 0x00040C64, 0x00041628, 0x000416C0, 0x00041A0C, 0x00041F60, 0x000427C0, 0x0004292C
  .4byte 0x00042C14, 0x000430AC, 0x00043730, 0x000439DC, 0x00043EE4, 0x00044E48, 0x00045084, 0x000455B4
  .4byte 0x000459E4, 0x00046530, 0x000468AC, 0x00046EC8, 0x00047280, 0x0004771C

@ Files
CollisionMap_050F: @ 0x087B2BE0, index: 0
  .incbin "data/collision_map/050F.bin.lz"
CollisionMap_051F: @ 0x087B301C, index: 1
  .incbin "data/collision_map/051F.bin.lz"
CollisionMap_052F: @ 0x087B3A7C, index: 2
  .incbin "data/collision_map/052F.bin.lz"
CollisionMap_053F: @ 0x087B3B54, index: 3
  .incbin "data/collision_map/053F.bin.lz"
CollisionMap_054F: @ 0x087B438C, index: 4
  .incbin "data/collision_map/054F.bin.lz"
CollisionMap_072C: @ 0x087B4594, index: 5
  .incbin "data/collision_map/072C.bin.lz"
CollisionMap_082E: @ 0x087B4794, index: 6
  .incbin "data/collision_map/082E.bin.lz"
CollisionMap_08AE: @ 0x087B5248, index: 7
  .incbin "data/collision_map/08AE.bin.lz"
CollisionMap_092E: @ 0x087B59D4, index: 8
  .incbin "data/collision_map/092E.bin.lz"
CollisionMap_09AE: @ 0x087B5D5C, index: 9
  .incbin "data/collision_map/09AE.bin.lz"
CollisionMap_0A2E: @ 0x087B660C, index: 10
  .incbin "data/collision_map/0A2E.bin.lz"
CollisionMap_0AAE: @ 0x087B6750, index: 11
  .incbin "data/collision_map/0AAE.bin.lz"
CollisionMap_0BAE: @ 0x087B6A8C, index: 12
  .incbin "data/collision_map/0BAE.bin.lz"
CollisionMap_0C2E: @ 0x087B7260, index: 13
  .incbin "data/collision_map/0C2E.bin.lz"
CollisionMap_0CAE: @ 0x087B7724, index: 14
  .incbin "data/collision_map/0CAE.bin.lz"
CollisionMap_0F0C: @ 0x087B7C70, index: 15
  .incbin "data/collision_map/0F0C.bin.lz"
CollisionMap_0F63: @ 0x087B8020, index: 16
  .incbin "data/collision_map/0F63.bin.lz"
CollisionMap_11B6: @ 0x087B81FC, index: 17
  .incbin "data/collision_map/11B6.bin.lz"
CollisionMap_11C6: @ 0x087B9230, index: 18
  .incbin "data/collision_map/11C6.bin.lz"
CollisionMap_11D6: @ 0x087B9DE4, index: 19
  .incbin "data/collision_map/11D6.bin.lz"
CollisionMap_11E6: @ 0x087BA6DC, index: 20
  .incbin "data/collision_map/11E6.bin.lz"
CollisionMap_11F6: @ 0x087BB198, index: 21
  .incbin "data/collision_map/11F6.bin.lz"
CollisionMap_1206: @ 0x087BC428, index: 22
  .incbin "data/collision_map/1206.bin.lz"
CollisionMap_1313: @ 0x087BD6AC, index: 23
  .incbin "data/collision_map/1313.bin.lz"
CollisionMap_164C: @ 0x087BD860, index: 24
  .incbin "data/collision_map/164C.bin.lz"
CollisionMap_17CE: @ 0x087BDBD4, index: 25
  .incbin "data/collision_map/17CE.bin.lz"
CollisionMap_17D2: @ 0x087BDE2C, index: 26
  .incbin "data/collision_map/17D2.bin.lz"
CollisionMap_17D6: @ 0x087BDFB4, index: 27
  .incbin "data/collision_map/17D6.bin.lz"
CollisionMap_182E: @ 0x087BE568, index: 28
  .incbin "data/collision_map/182E.bin.lz"
CollisionMap_1A97: @ 0x087BE8AC, index: 29
  .incbin "data/collision_map/1A97.bin.lz"
CollisionMap_2EF8: @ 0x087BEE6C, index: 30
  .incbin "data/collision_map/2EF8.bin.lz"
CollisionMap_2F08: @ 0x087BEFD8, index: 31
  .incbin "data/collision_map/2F08.bin.lz"
CollisionMap_2F18: @ 0x087BF8E8, index: 32
  .incbin "data/collision_map/2F18.bin.lz"
CollisionMap_2F28: @ 0x087BFD1C, index: 33
  .incbin "data/collision_map/2F28.bin.lz"
CollisionMap_2F38: @ 0x087C0098, index: 34
  .incbin "data/collision_map/2F38.bin.lz"
CollisionMap_2F48: @ 0x087C0484, index: 35
  .incbin "data/collision_map/2F48.bin.lz"
CollisionMap_2F58: @ 0x087C0A4C, index: 36
  .incbin "data/collision_map/2F58.bin.lz"
CollisionMap_2F63: @ 0x087C0BF8, index: 37
  .incbin "data/collision_map/2F63.bin.lz"
CollisionMap_2F68: @ 0x087C10B8, index: 38
  .incbin "data/collision_map/2F68.bin.lz"
CollisionMap_3313: @ 0x087C1144, index: 39
  .incbin "data/collision_map/3313.bin.lz"
CollisionMap_33C2: @ 0x087C1404, index: 40
  .incbin "data/collision_map/33C2.bin.lz"
CollisionMap_33D2: @ 0x087C1758, index: 41
  .incbin "data/collision_map/33D2.bin.lz"
CollisionMap_33E2: @ 0x087C1970, index: 42
  .incbin "data/collision_map/33E2.bin.lz"
CollisionMap_33F2: @ 0x087C1D34, index: 43
  .incbin "data/collision_map/33F2.bin.lz"
CollisionMap_3402: @ 0x087C2018, index: 44
  .incbin "data/collision_map/3402.bin.lz"
CollisionMap_3412: @ 0x087C22BC, index: 45
  .incbin "data/collision_map/3412.bin.lz"
CollisionMap_3422: @ 0x087C25EC, index: 46
  .incbin "data/collision_map/3422.bin.lz"
CollisionMap_3432: @ 0x087C2908, index: 47
  .incbin "data/collision_map/3432.bin.lz"
CollisionMap_3442: @ 0x087C2D58, index: 48
  .incbin "data/collision_map/3442.bin.lz"
CollisionMap_3452: @ 0x087C30B0, index: 49
  .incbin "data/collision_map/3452.bin.lz"
CollisionMap_35C2: @ 0x087C33A4, index: 50
  .incbin "data/collision_map/35C2.bin.lz"
CollisionMap_35D2: @ 0x087C37B0, index: 51
  .incbin "data/collision_map/35D2.bin.lz"
CollisionMap_35E2: @ 0x087C3990, index: 52
  .incbin "data/collision_map/35E2.bin.lz"
CollisionMap_37CE: @ 0x087C3D40, index: 53
  .incbin "data/collision_map/37CE.bin.lz"
CollisionMap_37D2: @ 0x087C3EDC, index: 54
  .incbin "data/collision_map/37D2.bin.lz"
CollisionMap_37D6: @ 0x087C438C, index: 55
  .incbin "data/collision_map/37D6.bin.lz"
CollisionMap_3A97: @ 0x087C4A04, index: 56
  .incbin "data/collision_map/3A97.bin.lz"
CollisionMap_3D33: @ 0x087C5214, index: 57
  .incbin "data/collision_map/3D33.bin.lz"
CollisionMap_3DB3: @ 0x087C5460, index: 58
  .incbin "data/collision_map/3DB3.bin.lz"
CollisionMap_3E33: @ 0x087C5704, index: 59
  .incbin "data/collision_map/3E33.bin.lz"
CollisionMap_3EB3: @ 0x087C5944, index: 60
  .incbin "data/collision_map/3EB3.bin.lz"
CollisionMap_3F33: @ 0x087C5BD8, index: 61
  .incbin "data/collision_map/3F33.bin.lz"
CollisionMap_3FB3: @ 0x087C5E9C, index: 62
  .incbin "data/collision_map/3FB3.bin.lz"
CollisionMap_4033: @ 0x087C61C0, index: 63
  .incbin "data/collision_map/4033.bin.lz"
CollisionMap_40B3: @ 0x087C63F0, index: 64
  .incbin "data/collision_map/40B3.bin.lz"
CollisionMap_4133: @ 0x087C6680, index: 65
  .incbin "data/collision_map/4133.bin.lz"
CollisionMap_41B3: @ 0x087C6A98, index: 66
  .incbin "data/collision_map/41B3.bin.lz"
CollisionMap_43B7: @ 0x087C6D1C, index: 67
  .incbin "data/collision_map/43B7.bin.lz"
CollisionMap_4D33: @ 0x087C7074, index: 68
  .incbin "data/collision_map/4D33.bin.lz"
CollisionMap_4DB3: @ 0x087C74EC, index: 69
  .incbin "data/collision_map/4DB3.bin.lz"
CollisionMap_4E33: @ 0x087C7AE4, index: 70
  .incbin "data/collision_map/4E33.bin.lz"
CollisionMap_4EB3: @ 0x087C7FE0, index: 71
  .incbin "data/collision_map/4EB3.bin.lz"
CollisionMap_4F33: @ 0x087C83BC, index: 72
  .incbin "data/collision_map/4F33.bin.lz"
CollisionMap_5313: @ 0x087C859C, index: 73
  .incbin "data/collision_map/5313.bin.lz"
CollisionMap_57CE: @ 0x087C8B00, index: 74
  .incbin "data/collision_map/57CE.bin.lz"
CollisionMap_57D2: @ 0x087C8DCC, index: 75
  .incbin "data/collision_map/57D2.bin.lz"
CollisionMap_57D6: @ 0x087C9098, index: 76
  .incbin "data/collision_map/57D6.bin.lz"
CollisionMap_5A97: @ 0x087C9448, index: 77
  .incbin "data/collision_map/5A97.bin.lz"
CollisionMap_5F34: @ 0x087C99C0, index: 78
  .incbin "data/collision_map/5F34.bin.lz"
CollisionMap_677F: @ 0x087CA6AC, index: 79
  .incbin "data/collision_map/677F.bin.lz"
CollisionMap_6A7F: @ 0x087CA8AC, index: 80
  .incbin "data/collision_map/6A7F.bin.lz"
CollisionMap_6AB0: @ 0x087CAA84, index: 81
  .incbin "data/collision_map/6AB0.bin.lz"
CollisionMap_77CE: @ 0x087CAC44, index: 82
  .incbin "data/collision_map/77CE.bin.lz"
CollisionMap_77D2: @ 0x087CADF8, index: 83
  .incbin "data/collision_map/77D2.bin.lz"
CollisionMap_77D6: @ 0x087CB1F8, index: 84
  .incbin "data/collision_map/77D6.bin.lz"
CollisionMap_78F6: @ 0x087CB704, index: 85
  .incbin "data/collision_map/78F6.bin.lz"
CollisionMap_7976: @ 0x087CBB38, index: 86
  .incbin "data/collision_map/7976.bin.lz"
CollisionMap_79F6: @ 0x087CC208, index: 87
  .incbin "data/collision_map/79F6.bin.lz"
CollisionMap_79FB: @ 0x087CC5BC, index: 88
  .incbin "data/collision_map/79FB.bin.lz"
CollisionMap_7A0B: @ 0x087CC964, index: 89
  .incbin "data/collision_map/7A0B.bin.lz"
CollisionMap_7A13: @ 0x087CCFB0, index: 90
  .incbin "data/collision_map/7A13.bin.lz"
CollisionMap_7A1B: @ 0x087CD958, index: 91
  .incbin "data/collision_map/7A1B.bin.lz"
CollisionMap_7A23: @ 0x087CE08C, index: 92
  .incbin "data/collision_map/7A23.bin.lz"
CollisionMap_7A2B: @ 0x087CEE64, index: 93
  .incbin "data/collision_map/7A2B.bin.lz"
CollisionMap_7A33: @ 0x087CF1F8, index: 94
  .incbin "data/collision_map/7A33.bin.lz"
CollisionMap_7A3B: @ 0x087CF7C8, index: 95
  .incbin "data/collision_map/7A3B.bin.lz"
CollisionMap_7A43: @ 0x087CFD54, index: 96
  .incbin "data/collision_map/7A43.bin.lz"
CollisionMap_7A4B: @ 0x087D00EC, index: 97
  .incbin "data/collision_map/7A4B.bin.lz"
CollisionMap_7A53: @ 0x087D054C, index: 98
  .incbin "data/collision_map/7A53.bin.lz"
CollisionMap_7A63: @ 0x087D0A94, index: 99
  .incbin "data/collision_map/7A63.bin.lz"
CollisionMap_7A76: @ 0x087D0C2C, index: 100
  .incbin "data/collision_map/7A76.bin.lz"
CollisionMap_7A97: @ 0x087D1D5C, index: 101
  .incbin "data/collision_map/7A97.bin.lz"
CollisionMap_7AF6: @ 0x087D2428, index: 102
  .incbin "data/collision_map/7AF6.bin.lz"
CollisionMap_7B76: @ 0x087D2D00, index: 103
  .incbin "data/collision_map/7B76.bin.lz"
CollisionMap_7BBA: @ 0x087D3594, index: 104
  .incbin "data/collision_map/7BBA.bin.lz"
CollisionMap_7BF6: @ 0x087D3690, index: 105
  .incbin "data/collision_map/7BF6.bin.lz"
CollisionMap_7C76: @ 0x087D3DD0, index: 106
  .incbin "data/collision_map/7C76.bin.lz"
CollisionMap_7CF6: @ 0x087D4620, index: 107
  .incbin "data/collision_map/7CF6.bin.lz"
CollisionMap_7D2E: @ 0x087D4B58, index: 108
  .incbin "data/collision_map/7D2E.bin.lz"
CollisionMap_7D76: @ 0x087D4C20, index: 109
  .incbin "data/collision_map/7D76.bin.lz"
CollisionMap_7E9E: @ 0x087D5288, index: 110
  .incbin "data/collision_map/7E9E.bin.lz"
CollisionMap_7F34: @ 0x087D5394, index: 111
  .incbin "data/collision_map/7F34.bin.lz"
CollisionMap_7FC6: @ 0x087D6154, index: 112
  .incbin "data/collision_map/7FC6.bin.lz"
CollisionMap_88F6: @ 0x087D662C, index: 113
  .incbin "data/collision_map/88F6.bin.lz"
CollisionMap_8976: @ 0x087D6C60, index: 114
  .incbin "data/collision_map/8976.bin.lz"
CollisionMap_89F6: @ 0x087D7468, index: 115
  .incbin "data/collision_map/89F6.bin.lz"
CollisionMap_8A76: @ 0x087D7AA0, index: 116
  .incbin "data/collision_map/8A76.bin.lz"
CollisionMap_8AF6: @ 0x087D7F6C, index: 117
  .incbin "data/collision_map/8AF6.bin.lz"
CollisionMap_8B76: @ 0x087D8604, index: 118
  .incbin "data/collision_map/8B76.bin.lz"
CollisionMap_8BF6: @ 0x087D8994, index: 119
  .incbin "data/collision_map/8BF6.bin.lz"
CollisionMap_8C76: @ 0x087D8AB0, index: 120
  .incbin "data/collision_map/8C76.bin.lz"
CollisionMap_8CF6: @ 0x087D8D30, index: 121
  .incbin "data/collision_map/8CF6.bin.lz"
CollisionMap_8F62: @ 0x087D8E9C, index: 122
  .incbin "data/collision_map/8F62.bin.lz"
CollisionMap_97CD: @ 0x087D9F60, index: 123
  .incbin "data/collision_map/97CD.bin.lz"
CollisionMap_97CE: @ 0x087DA070, index: 124
  .incbin "data/collision_map/97CE.bin.lz"
CollisionMap_97D1: @ 0x087DA3A4, index: 125
  .incbin "data/collision_map/97D1.bin.lz"
CollisionMap_97D2: @ 0x087DAA20, index: 126
  .incbin "data/collision_map/97D2.bin.lz"
CollisionMap_97D5: @ 0x087DAE94, index: 127
  .incbin "data/collision_map/97D5.bin.lz"
CollisionMap_97D6: @ 0x087DB194, index: 128
  .incbin "data/collision_map/97D6.bin.lz"
CollisionMap_97D9: @ 0x087DB688, index: 129
  .incbin "data/collision_map/97D9.bin.lz"
CollisionMap_9A97: @ 0x087DBCA4, index: 130
  .incbin "data/collision_map/9A97.bin.lz"
CollisionMap_9F34: @ 0x087DC2A8, index: 131
  .incbin "data/collision_map/9F34.bin.lz"
CollisionMap_A21B: @ 0x087DCBE8, index: 132
  .incbin "data/collision_map/A21B.bin.lz"
CollisionMap_AF62: @ 0x087DCD54, index: 133
  .incbin "data/collision_map/AF62.bin.lz"
CollisionMap_B088: @ 0x087DCF48, index: 134
  .incbin "data/collision_map/B088.bin.lz"
CollisionMap_B26B: @ 0x087DD07C, index: 135
  .incbin "data/collision_map/B26B.bin.lz"
CollisionMap_B381: @ 0x087DD4FC, index: 136
  .incbin "data/collision_map/B381.bin.lz"
CollisionMap_B391: @ 0x087DDA54, index: 137
  .incbin "data/collision_map/B391.bin.lz"
CollisionMap_B3A1: @ 0x087DE0F4, index: 138
  .incbin "data/collision_map/B3A1.bin.lz"
CollisionMap_B3B1: @ 0x087DE1F0, index: 139
  .incbin "data/collision_map/B3B1.bin.lz"
CollisionMap_B3C1: @ 0x087DE8B4, index: 140
  .incbin "data/collision_map/B3C1.bin.lz"
CollisionMap_B3D1: @ 0x087DEEE4, index: 141
  .incbin "data/collision_map/B3D1.bin.lz"
CollisionMap_B4F1: @ 0x087DF270, index: 142
  .incbin "data/collision_map/B4F1.bin.lz"
CollisionMap_B66F: @ 0x087DF428, index: 143
  .incbin "data/collision_map/B66F.bin.lz"
CollisionMap_B673: @ 0x087DFC6C, index: 144
  .incbin "data/collision_map/B673.bin.lz"
CollisionMap_B677: @ 0x087E0864, index: 145
  .incbin "data/collision_map/B677.bin.lz"
CollisionMap_B67B: @ 0x087E0DBC, index: 146
  .incbin "data/collision_map/B67B.bin.lz"
CollisionMap_B67F: @ 0x087E11D0, index: 147
  .incbin "data/collision_map/B67F.bin.lz"
CollisionMap_B683: @ 0x087E158C, index: 148
  .incbin "data/collision_map/B683.bin.lz"
CollisionMap_B687: @ 0x087E1940, index: 149
  .incbin "data/collision_map/B687.bin.lz"
CollisionMap_B7CD: @ 0x087E2070, index: 150
  .incbin "data/collision_map/B7CD.bin.lz"
CollisionMap_B7CE: @ 0x087E2380, index: 151
  .incbin "data/collision_map/B7CE.bin.lz"
CollisionMap_B7D1: @ 0x087E291C, index: 152
  .incbin "data/collision_map/B7D1.bin.lz"
CollisionMap_B7D2: @ 0x087E2F14, index: 153
  .incbin "data/collision_map/B7D2.bin.lz"
CollisionMap_B7D5: @ 0x087E3100, index: 154
  .incbin "data/collision_map/B7D5.bin.lz"
CollisionMap_B7D6: @ 0x087E32D0, index: 155
  .incbin "data/collision_map/B7D6.bin.lz"
CollisionMap_B889: @ 0x087E35FC, index: 156
  .incbin "data/collision_map/B889.bin.lz"
CollisionMap_B909: @ 0x087E3828, index: 157
  .incbin "data/collision_map/B909.bin.lz"
CollisionMap_B989: @ 0x087E3AE8, index: 158
  .incbin "data/collision_map/B989.bin.lz"
CollisionMap_BA09: @ 0x087E3C64, index: 159
  .incbin "data/collision_map/BA09.bin.lz"
CollisionMap_BA89: @ 0x087E3EB4, index: 160
  .incbin "data/collision_map/BA89.bin.lz"
CollisionMap_BA97: @ 0x087E3FC0, index: 161
  .incbin "data/collision_map/BA97.bin.lz"
CollisionMap_BB09: @ 0x087E438C, index: 162
  .incbin "data/collision_map/BB09.bin.lz"
CollisionMap_BB2F: @ 0x087E4494, index: 163
  .incbin "data/collision_map/BB2F.bin.lz"
CollisionMap_BB89: @ 0x087E4658, index: 164
  .incbin "data/collision_map/BB89.bin.lz"
CollisionMap_BC09: @ 0x087E4804, index: 165
  .incbin "data/collision_map/BC09.bin.lz"
CollisionMap_BC89: @ 0x087E4BC4, index: 166
  .incbin "data/collision_map/BC89.bin.lz"
CollisionMap_BD09: @ 0x087E4F74, index: 167
  .incbin "data/collision_map/BD09.bin.lz"
CollisionMap_BFB9: @ 0x087E51D0, index: 168
  .incbin "data/collision_map/BFB9.bin.lz"
CollisionMap_C039: @ 0x087E536C, index: 169
  .incbin "data/collision_map/C039.bin.lz"
CollisionMap_C12F: @ 0x087E5538, index: 170
  .incbin "data/collision_map/C12F.bin.lz"
CollisionMap_C4C4: @ 0x087E5760, index: 171
  .incbin "data/collision_map/C4C4.bin.lz"
CollisionMap_C4C8: @ 0x087E5AD0, index: 172
  .incbin "data/collision_map/C4C8.bin.lz"
CollisionMap_C4CC: @ 0x087E5EB4, index: 173
  .incbin "data/collision_map/C4CC.bin.lz"
CollisionMap_C4D0: @ 0x087E6430, index: 174
  .incbin "data/collision_map/C4D0.bin.lz"
CollisionMap_C4D4: @ 0x087E6C90, index: 175
  .incbin "data/collision_map/C4D4.bin.lz"
CollisionMap_C4D8: @ 0x087E6E6C, index: 176
  .incbin "data/collision_map/C4D8.bin.lz"
CollisionMap_C4DC: @ 0x087E741C, index: 177
  .incbin "data/collision_map/C4DC.bin.lz"
CollisionMap_C4E0: @ 0x087E7968, index: 178
  .incbin "data/collision_map/C4E0.bin.lz"
CollisionMap_C4E4: @ 0x087E7FE0, index: 179
  .incbin "data/collision_map/C4E4.bin.lz"
CollisionMap_C889: @ 0x087E8764, index: 180
  .incbin "data/collision_map/C889.bin.lz"
CollisionMap_C909: @ 0x087E888C, index: 181
  .incbin "data/collision_map/C909.bin.lz"
CollisionMap_C989: @ 0x087E8A24, index: 182
  .incbin "data/collision_map/C989.bin.lz"
CollisionMap_CA09: @ 0x087E8C94, index: 183
  .incbin "data/collision_map/CA09.bin.lz"
CollisionMap_CA89: @ 0x087E8F78, index: 184
  .incbin "data/collision_map/CA89.bin.lz"
CollisionMap_CB09: @ 0x087E9080, index: 185
  .incbin "data/collision_map/CB09.bin.lz"
CollisionMap_CB89: @ 0x087E9178, index: 186
  .incbin "data/collision_map/CB89.bin.lz"
CollisionMap_CD05: @ 0x087E92F4, index: 187
  .incbin "data/collision_map/CD05.bin.lz"
CollisionMap_CD09: @ 0x087E96CC, index: 188
  .incbin "data/collision_map/CD09.bin.lz"
CollisionMap_CD0D: @ 0x087E9C7C, index: 189
  .incbin "data/collision_map/CD0D.bin.lz"
CollisionMap_CD11: @ 0x087EA288, index: 190
  .incbin "data/collision_map/CD11.bin.lz"
CollisionMap_CD15: @ 0x087EA3D0, index: 191
  .incbin "data/collision_map/CD15.bin.lz"
CollisionMap_CD19: @ 0x087EAE5C, index: 192
  .incbin "data/collision_map/CD19.bin.lz"
CollisionMap_CD1D: @ 0x087EB044, index: 193
  .incbin "data/collision_map/CD1D.bin.lz"
CollisionMap_CD21: @ 0x087EB720, index: 194
  .incbin "data/collision_map/CD21.bin.lz"
CollisionMap_CD25: @ 0x087EBE78, index: 195
  .incbin "data/collision_map/CD25.bin.lz"
CollisionMap_CD29: @ 0x087EC008, index: 196
  .incbin "data/collision_map/CD29.bin.lz"
CollisionMap_CD85: @ 0x087EC3F4, index: 197
  .incbin "data/collision_map/CD85.bin.lz"
CollisionMap_CD89: @ 0x087ECBF8, index: 198
  .incbin "data/collision_map/CD89.bin.lz"
CollisionMap_CD8D: @ 0x087ECF84, index: 199
  .incbin "data/collision_map/CD8D.bin.lz"
CollisionMap_CD91: @ 0x087ED818, index: 200
  .incbin "data/collision_map/CD91.bin.lz"
CollisionMap_CD95: @ 0x087ED980, index: 201
  .incbin "data/collision_map/CD95.bin.lz"
CollisionMap_CD99: @ 0x087EDF48, index: 202
  .incbin "data/collision_map/CD99.bin.lz"
CollisionMap_CD9D: @ 0x087EE318, index: 203
  .incbin "data/collision_map/CD9D.bin.lz"
CollisionMap_CDA1: @ 0x087EE4A8, index: 204
  .incbin "data/collision_map/CDA1.bin.lz"
CollisionMap_CDA5: @ 0x087EEB54, index: 205
  .incbin "data/collision_map/CDA5.bin.lz"
CollisionMap_CDA9: @ 0x087EECF8, index: 206
  .incbin "data/collision_map/CDA9.bin.lz"
CollisionMap_CE05: @ 0x087EF510, index: 207
  .incbin "data/collision_map/CE05.bin.lz"
CollisionMap_CE09: @ 0x087EF740, index: 208
  .incbin "data/collision_map/CE09.bin.lz"
CollisionMap_CE0D: @ 0x087EFE94, index: 209
  .incbin "data/collision_map/CE0D.bin.lz"
CollisionMap_CE11: @ 0x087F0164, index: 210
  .incbin "data/collision_map/CE11.bin.lz"
CollisionMap_CE15: @ 0x087F067C, index: 211
  .incbin "data/collision_map/CE15.bin.lz"
CollisionMap_CE19: @ 0x087F0A60, index: 212
  .incbin "data/collision_map/CE19.bin.lz"
CollisionMap_CE1D: @ 0x087F0B0C, index: 213
  .incbin "data/collision_map/CE1D.bin.lz"
CollisionMap_CF62: @ 0x087F0EC4, index: 214
  .incbin "data/collision_map/CF62.bin.lz"
CollisionMap_D312: @ 0x087F10BC, index: 215
  .incbin "data/collision_map/D312.bin.lz"
CollisionMap_D461: @ 0x087F1744, index: 216
  .incbin "data/collision_map/D461.bin.lz"
CollisionMap_D7CD: @ 0x087F17F0, index: 217
  .incbin "data/collision_map/D7CD.bin.lz"
CollisionMap_D7D1: @ 0x087F1AAC, index: 218
  .incbin "data/collision_map/D7D1.bin.lz"
CollisionMap_D7D5: @ 0x087F1F8C, index: 219
  .incbin "data/collision_map/D7D5.bin.lz"
CollisionMap_D909: @ 0x087F211C, index: 220
  .incbin "data/collision_map/D909.bin.lz"
CollisionMap_D9EF: @ 0x087F2248, index: 221
  .incbin "data/collision_map/D9EF.bin.lz"
CollisionMap_D9FF: @ 0x087F257C, index: 222
  .incbin "data/collision_map/D9FF.bin.lz"
CollisionMap_DA0F: @ 0x087F29AC, index: 223
  .incbin "data/collision_map/DA0F.bin.lz"
CollisionMap_DA1F: @ 0x087F30A8, index: 224
  .incbin "data/collision_map/DA1F.bin.lz"
CollisionMap_DA2F: @ 0x087F3270, index: 225
  .incbin "data/collision_map/DA2F.bin.lz"
CollisionMap_DA3F: @ 0x087F3C34, index: 226
  .incbin "data/collision_map/DA3F.bin.lz"
CollisionMap_DA97: @ 0x087F3CCC, index: 227
  .incbin "data/collision_map/DA97.bin.lz"
CollisionMap_EAC3: @ 0x087F4018, index: 228
  .incbin "data/collision_map/EAC3.bin.lz"
CollisionMap_F312: @ 0x087F456C, index: 229
  .incbin "data/collision_map/F312.bin.lz"
CollisionMap_F38C: @ 0x087F4DCC, index: 230
  .incbin "data/collision_map/F38C.bin.lz"
CollisionMap_F7CD: @ 0x087F4F38, index: 231
  .incbin "data/collision_map/F7CD.bin.lz"
CollisionMap_F7D1: @ 0x087F5220, index: 232
  .incbin "data/collision_map/F7D1.bin.lz"
CollisionMap_F7D5: @ 0x087F56B8, index: 233
  .incbin "data/collision_map/F7D5.bin.lz"
CollisionMap_F82D: @ 0x087F5D3C, index: 234
  .incbin "data/collision_map/F82D.bin.lz"
CollisionMap_F8AD: @ 0x087F5FE8, index: 235
  .incbin "data/collision_map/F8AD.bin.lz"
CollisionMap_F92D: @ 0x087F64F0, index: 236
  .incbin "data/collision_map/F92D.bin.lz"
CollisionMap_F9AD: @ 0x087F7454, index: 237
  .incbin "data/collision_map/F9AD.bin.lz"
CollisionMap_FA2D: @ 0x087F7690, index: 238
  .incbin "data/collision_map/FA2D.bin.lz"
CollisionMap_FA96: @ 0x087F7BC0, index: 239
  .incbin "data/collision_map/FA96.bin.lz"
CollisionMap_FA97: @ 0x087F7FF0, index: 240
  .incbin "data/collision_map/FA97.bin.lz"
CollisionMap_FAAD: @ 0x087F8B3C, index: 241
  .incbin "data/collision_map/FAAD.bin.lz"
CollisionMap_FB2D: @ 0x087F8EB8, index: 242
  .incbin "data/collision_map/FB2D.bin.lz"
CollisionMap_FBAD: @ 0x087F94D4, index: 243
  .incbin "data/collision_map/FBAD.bin.lz"
CollisionMap_FC2D: @ 0x087F988C, index: 244
  .incbin "data/collision_map/FC2D.bin.lz"
CollisionMap_FCAD: @ 0x087F9D28, index: 245
  .incbin "data/collision_map/FCAD.bin.lz"
