@ Generated by tools/dumper/animation.ts
@ Do not edit this file manually.

.include "asm/macros.inc"
.include "asm/animation.inc"

.balign 4, 0
.section .rodata

.global gAnimDirectory
gAnimDirectory: @ 0x085B0DF0
  .4byte 51 @ entry count
  .4byte 0x10, 0x78, 0x148

@ FileIDs
  .2byte 0x0837, 0x0AE9, 0x1003, 0x121B, 0x13F9, 0x1752, 0x1C9B, 0x1DC3, 0x1DF8, 0x1E38, 0x1FB8, 0x27A4, 0x29FB, 0x31F4, 0x3449, 0x38E2
  .2byte 0x3D95, 0x3DC2, 0x3F72, 0x4EC0, 0x5BB7, 0x5C4D, 0x62C7, 0x6830, 0x74C9, 0x78E1, 0x7B03, 0x871C, 0x87EF, 0x8DC7, 0x931E, 0x95D9
  .2byte 0x9607, 0x99DD, 0x9AF2, 0xA4B2, 0xA929, 0xAF44, 0xB6EE, 0xB952, 0xC102, 0xC160, 0xC6A0, 0xD1B8, 0xD41F, 0xD6C8, 0xDA5E, 0xDCEB
  .2byte 0xE677, 0xF62B, 0xF6E7, 0x0000

@ FileOffsets
  .4byte 0x00000148, 0x00000178, 0x0000018C, 0x000001B4, 0x00000238, 0x0000025C, 0x00000278, 0x0000028C
  .4byte 0x000003A4, 0x000004B8, 0x0000057C, 0x000005CC, 0x000005E0, 0x0000063C, 0x000006D8, 0x00000768
  .4byte 0x00000844, 0x000009B8, 0x000009D4, 0x000009F4, 0x00000A58, 0x00000AA0, 0x00000AB8, 0x00000B1C
  .4byte 0x00000B4C, 0x00000B64, 0x00000BB8, 0x00000C74, 0x00000CA0, 0x00000CCC, 0x00000CE0, 0x00000D30
  .4byte 0x00000D6C, 0x00000DE4, 0x00000E74, 0x00000EC0, 0x00000F78, 0x00001010, 0x0000105C, 0x000010C4
  .4byte 0x000010E0, 0x0000121C, 0x00001234, 0x00001338, 0x000013F4, 0x00001440, 0x0000149C, 0x0000168C
  .4byte 0x00001700, 0x0000171C, 0x00001764, 0x00000000

@ Files
.balign 4, 0
Animation_0837: @ 0x085B0F38, index: 0
  .set ANIM_COUNT, 3
  .2byte ANIM_COUNT, 14 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 48, 0, 2
    animation 48, 6, 2
    animation 16, 12, 2
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 4
      animcmd 1, 4
      animcmd 2, 4
      animcmd 3, 4
      animcmd 4, 4
      animcmd 5, 4
    @ cmd_idx 6
      animcmd 6, 4
      animcmd 7, 4
      animcmd 8, 4
      animcmd 9, 4
      animcmd 10, 4
      animcmd 11, 4
    @ cmd_idx 12
      animcmd 12, 4
      animcmd 13, 4
  .4byte 0 @ terminator?

.balign 4, 0
Animation_0AE9: @ 0x085B0F68, index: 1
  .set ANIM_COUNT, 1
  .2byte ANIM_COUNT, 4 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 32, 0, 2
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 6
      animcmd 1, 6
      animcmd 2, 6
      animcmd 3, 6
  .4byte 0 @ terminator?

.balign 4, 0
Animation_1003: @ 0x085B0F7C, index: 2
  .set ANIM_COUNT, 2
  .2byte ANIM_COUNT, 11 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 7
    animation 16, 7, 4
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 15
      animcmd 1, 15
      animcmd 2, 15
      animcmd 3, 15
      animcmd 2, 15
      animcmd 1, 15
      animcmd 0, 15
    @ cmd_idx 7
      animcmd 4, 15
      animcmd 5, 15
      animcmd 6, 15
      animcmd 7, 15
  .4byte 0 @ terminator?

.balign 4, 0
Animation_121B: @ 0x085B0FA4, index: 3
  .set ANIM_COUNT, 9
  .2byte ANIM_COUNT, 43 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 8
    animation 32, 8, 5
    animation 16, 18, 4
    animation 16, 22, 1
    animation 16, 23, 4
    animation 16, 27, 1
    animation 16, 28, 6
    animation 16, 34, 6
    animation 16, 40, 3
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 5
      animcmd 1, 5
      animcmd 2, 5
      animcmd 3, 5
      animcmd 4, 5
      animcmd 5, 5
      animcmd 6, 5
      animcmd 7, 5
    @ cmd_idx 8
      animcmd 12, 5
      animcmd 11, 5
      animcmd 10, 5
      animcmd 9, 5
      animcmd 8, 5
      animcmd 8, 5
      animcmd 9, 5
      animcmd 10, 5
      animcmd 11, 5
      animcmd 12, 5
    @ cmd_idx 18
      animcmd 13, 7
      animcmd 14, 7
      animcmd 15, 7
      animcmd 14, 7
    @ cmd_idx 22
      animcmd 16, 10
    @ cmd_idx 23
      animcmd 26, 6
      animcmd 27, 6
      animcmd 28, 6
      animcmd 27, 6
    @ cmd_idx 27
      animcmd 29, 3
    @ cmd_idx 28
      animcmd 39, 6
      animcmd 40, 6
      animcmd 41, 8
      animcmd 42, 8
      animcmd 43, 8
      animcmd 44, 8
    @ cmd_idx 34
      animcmd 17, 4
      animcmd 18, 4
      animcmd 19, 4
      animcmd 20, 4
      animcmd 21, 4
      animcmd 22, 4
    @ cmd_idx 40
      animcmd 23, 4
      animcmd 24, 4
      animcmd 25, 4
  .4byte 0 @ terminator?

.balign 4, 0
Animation_13F9: @ 0x085B1028, index: 4
  .set ANIM_COUNT, 3
  .2byte ANIM_COUNT, 8 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 64, 0, 1
    animation 16, 4, 1
    animation 48, 5, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 1
      animcmd 2, 1
      animcmd 3, 1
      animcmd 5, 1
    @ cmd_idx 4
      animcmd 1, 1
    @ cmd_idx 5
      animcmd 2, 1
      animcmd 4, 1
      animcmd 5, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_1752: @ 0x085B104C, index: 5
  .set ANIM_COUNT, 2
  .2byte ANIM_COUNT, 5 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 1
    animation 16, 1, 4
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 1
    @ cmd_idx 1
      animcmd 1, 8
      animcmd 2, 8
      animcmd 3, 8
      animcmd 4, 8
  .4byte 0 @ terminator?

.balign 4, 0
Animation_1C9B: @ 0x085B1068, index: 6
  .set ANIM_COUNT, 1
  .2byte ANIM_COUNT, 3 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 0, 0, 3
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 5
      animcmd 1, 5
      animcmd 2, 5
  .4byte 0 @ terminator?

.balign 4, 0
Animation_1DC3: @ 0x085B107C, index: 7
  .set ANIM_COUNT, 25
  .2byte ANIM_COUNT, 86 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 1
    animation 16, 1, 1
    animation 16, 2, 1
    animation 16, 3, 1
    animation 16, 4, 1
    animation 16, 5, 1
    animation 16, 6, 1
    animation 16, 7, 1
    animation 16, 8, 1
    animation 16, 9, 1
    animation 16, 10, 1
    animation 16, 11, 1
    animation 16, 12, 7
    animation 16, 19, 6
    animation 16, 25, 5
    animation 16, 30, 4
    animation 16, 34, 10
    animation 16, 44, 14
    animation 32, 58, 3
    animation 32, 64, 2
    animation 16, 68, 4
    animation 16, 72, 4
    animation 16, 76, 4
    animation 16, 80, 3
    animation 16, 83, 3
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 1
    @ cmd_idx 1
      animcmd 1, 1
    @ cmd_idx 2
      animcmd 2, 1
    @ cmd_idx 3
      animcmd 3, 1
    @ cmd_idx 4
      animcmd 4, 1
    @ cmd_idx 5
      animcmd 5, 1
    @ cmd_idx 6
      animcmd 6, 1
    @ cmd_idx 7
      animcmd 7, 1
    @ cmd_idx 8
      animcmd 8, 1
    @ cmd_idx 9
      animcmd 9, 1
    @ cmd_idx 10
      animcmd 10, 1
    @ cmd_idx 11
      animcmd 11, 1
    @ cmd_idx 12
      animcmd 12, 3
      animcmd 13, 3
      animcmd 14, 3
      animcmd 15, 3
      animcmd 16, 3
      animcmd 17, 3
      animcmd 18, 3
    @ cmd_idx 19
      animcmd 19, 3
      animcmd 20, 3
      animcmd 21, 3
      animcmd 22, 3
      animcmd 23, 3
      animcmd 24, 3
    @ cmd_idx 25
      animcmd 25, 5
      animcmd 26, 5
      animcmd 27, 5
      animcmd 28, 5
      animcmd 29, 5
    @ cmd_idx 30
      animcmd 44, 4
      animcmd 45, 4
      animcmd 46, 4
      animcmd 47, 4
    @ cmd_idx 34
      animcmd 54, 3
      animcmd 55, 3
      animcmd 56, 3
      animcmd 57, 3
      animcmd 58, 3
      animcmd 59, 3
      animcmd 60, 3
      animcmd 61, 3
      animcmd 62, 3
      animcmd 63, 3
    @ cmd_idx 44
      animcmd 30, 5
      animcmd 31, 5
      animcmd 32, 5
      animcmd 33, 5
      animcmd 34, 5
      animcmd 35, 5
      animcmd 36, 5
      animcmd 37, 5
      animcmd 38, 5
      animcmd 39, 5
      animcmd 40, 5
      animcmd 41, 5
      animcmd 42, 5
      animcmd 43, 5
    @ cmd_idx 58
      animcmd 48, 2
      animcmd 49, 2
      animcmd 50, 2
      animcmd 51, 2
      animcmd 52, 2
      animcmd 53, 2
    @ cmd_idx 64
      animcmd 76, 4
      animcmd 77, 4
      animcmd 78, 4
      animcmd 79, 4
    @ cmd_idx 68
      animcmd 64, 2
      animcmd 65, 2
      animcmd 66, 2
      animcmd 67, 2
    @ cmd_idx 72
      animcmd 68, 2
      animcmd 69, 2
      animcmd 70, 2
      animcmd 71, 2
    @ cmd_idx 76
      animcmd 72, 2
      animcmd 73, 2
      animcmd 74, 2
      animcmd 75, 2
    @ cmd_idx 80
      animcmd 82, 6
      animcmd 81, 6
      animcmd 80, 6
    @ cmd_idx 83
      animcmd 83, 3
      animcmd 84, 3
      animcmd 85, 3
  .4byte 0 @ terminator?

.balign 4, 0
Animation_1DF8: @ 0x085B1194, index: 8
  .set ANIM_COUNT, 11
  .2byte ANIM_COUNT, 112 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 32, 0, 3
    animation 32, 6, 3
    animation 32, 12, 1
    animation 32, 14, 1
    animation 32, 16, 4
    animation 32, 24, 3
    animation 32, 30, 7
    animation 32, 44, 1
    animation 32, 46, 20
    animation 48, 86, 4
    animation 32, 98, 7
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 3
      animcmd 1, 15
      animcmd 1, 15
      animcmd 2, 3
      animcmd 3, 15
      animcmd 3, 15
    @ cmd_idx 6
      animcmd 0, 3
      animcmd 1, 15
      animcmd 1, 15
      animcmd 2, 3
      animcmd 3, 15
      animcmd 3, 15
    @ cmd_idx 12
      animcmd 12, 4
      animcmd 17, 4
    @ cmd_idx 14
      animcmd 13, 4
      animcmd 18, 4
    @ cmd_idx 16
      animcmd 12, 2
      animcmd 14, 6
      animcmd 15, 6
      animcmd 16, 10
      animcmd 17, 2
      animcmd 19, 6
      animcmd 20, 6
      animcmd 21, 10
    @ cmd_idx 24
      animcmd 14, 5
      animcmd 15, 5
      animcmd 16, 10
      animcmd 19, 5
      animcmd 20, 5
      animcmd 21, 10
    @ cmd_idx 30
      animcmd 16, 5
      animcmd 15, 5
      animcmd 14, 10
      animcmd 22, 15
      animcmd 22, 15
      animcmd 22, 15
      animcmd 22, 15
      animcmd 21, 5
      animcmd 20, 5
      animcmd 19, 10
      animcmd 23, 15
      animcmd 23, 15
      animcmd 23, 15
      animcmd 23, 15
    @ cmd_idx 44
      animcmd 22, 1
      animcmd 23, 1
    @ cmd_idx 46
      animcmd 24, 6
      animcmd 25, 6
      animcmd 25, 6
      animcmd 26, 6
      animcmd 27, 6
      animcmd 27, 6
      animcmd 27, 6
      animcmd 27, 6
      animcmd 27, 6
      animcmd 27, 6
      animcmd 28, 6
      animcmd 29, 6
      animcmd 29, 6
      animcmd 30, 6
      animcmd 31, 6
      animcmd 31, 6
      animcmd 31, 6
      animcmd 31, 6
      animcmd 31, 6
      animcmd 31, 6
      animcmd 32, 6
      animcmd 33, 6
      animcmd 33, 6
      animcmd 34, 6
      animcmd 35, 6
      animcmd 35, 6
      animcmd 35, 6
      animcmd 35, 6
      animcmd 35, 6
      animcmd 35, 6
      animcmd 36, 6
      animcmd 37, 6
      animcmd 37, 6
      animcmd 38, 6
      animcmd 39, 6
      animcmd 39, 6
      animcmd 39, 6
      animcmd 39, 6
      animcmd 39, 6
      animcmd 39, 6
    @ cmd_idx 86
      animcmd 40, 10, xflip=1
      animcmd 41, 8
      animcmd 41, 8
      animcmd 42, 10
      animcmd 42, 10
      animcmd 43, 8
      animcmd 43, 8
      animcmd 44, 10
      animcmd 45, 10
      animcmd 46, 8
      animcmd 46, 8
      animcmd 45, 10, xflip=1
    @ cmd_idx 98
      animcmd 0, 3
      animcmd 1, 15
      animcmd 4, 4
      animcmd 5, 14
      animcmd 5, 2
      animcmd 6, 8
      animcmd 7, 4
      animcmd 2, 3
      animcmd 3, 15
      animcmd 8, 4
      animcmd 9, 14
      animcmd 9, 2
      animcmd 10, 8
      animcmd 11, 4
  .4byte 0 @ terminator?

.balign 4, 0
Animation_1E38: @ 0x085B12A8, index: 9
  .set ANIM_COUNT, 10
  .2byte ANIM_COUNT, 73 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 32, 0, 1
    animation 32, 2, 8
    animation 48, 18, 3
    animation 32, 27, 2
    animation 32, 31, 4
    animation 32, 39, 3
    animation 32, 45, 4
    animation 32, 53, 3
    animation 32, 59, 6
    animation 32, 71, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 1
      animcmd 1, 1
    @ cmd_idx 2
      animcmd 2, 9
      animcmd 3, 15
      animcmd 4, 9
      animcmd 5, 9
      animcmd 6, 9
      animcmd 7, 15
      animcmd 8, 9
      animcmd 9, 9
      animcmd 10, 9
      animcmd 11, 15
      animcmd 12, 9
      animcmd 13, 9
      animcmd 14, 9
      animcmd 15, 15
      animcmd 16, 9
      animcmd 17, 9
    @ cmd_idx 18
      animcmd 40, 10, xflip=1
      animcmd 41, 15
      animcmd 40, 10
      animcmd 42, 10
      animcmd 43, 15
      animcmd 44, 10
      animcmd 45, 10
      animcmd 46, 15
      animcmd 45, 10, xflip=1
    @ cmd_idx 27
      animcmd 18, 4
      animcmd 19, 4
      animcmd 22, 4
      animcmd 23, 4
    @ cmd_idx 31
      animcmd 18, 4
      animcmd 21, 4
      animcmd 20, 2
      animcmd 21, 4
      animcmd 22, 4
      animcmd 25, 4
      animcmd 24, 2
      animcmd 25, 4
    @ cmd_idx 39
      animcmd 21, 6
      animcmd 20, 6
      animcmd 19, 6
      animcmd 25, 6
      animcmd 24, 6
      animcmd 23, 6
    @ cmd_idx 45
      animcmd 18, 4
      animcmd 21, 4
      animcmd 20, 2
      animcmd 21, 10
      animcmd 23, 4
      animcmd 25, 4
      animcmd 24, 2
      animcmd 25, 10
    @ cmd_idx 53
      animcmd 0, 1
      animcmd 26, 6
      animcmd 28, 6
      animcmd 1, 1
      animcmd 27, 6
      animcmd 34, 6
    @ cmd_idx 59
      animcmd 28, 8
      animcmd 29, 8
      animcmd 30, 8
      animcmd 31, 8
      animcmd 32, 8
      animcmd 33, 8
      animcmd 34, 8
      animcmd 35, 8
      animcmd 36, 8
      animcmd 37, 8
      animcmd 38, 8
      animcmd 39, 8
    @ cmd_idx 71
      animcmd 21, 1
      animcmd 25, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_1FB8: @ 0x085B136C, index: 10
  .set ANIM_COUNT, 6
  .2byte ANIM_COUNT, 24 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 4
    animation 16, 4, 4
    animation 16, 8, 4
    animation 16, 12, 4
    animation 16, 16, 4
    animation 16, 20, 4
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 15, 8
      animcmd 16, 8
      animcmd 17, 8
      animcmd 16, 8
    @ cmd_idx 4
      animcmd 12, 8
      animcmd 13, 8
      animcmd 14, 8
      animcmd 13, 8
    @ cmd_idx 8
      animcmd 9, 8
      animcmd 10, 8
      animcmd 11, 8
      animcmd 10, 8
    @ cmd_idx 12
      animcmd 6, 8
      animcmd 7, 8
      animcmd 8, 8
      animcmd 7, 8
    @ cmd_idx 16
      animcmd 3, 8
      animcmd 4, 8
      animcmd 5, 8
      animcmd 4, 8
    @ cmd_idx 20
      animcmd 0, 8
      animcmd 1, 8
      animcmd 2, 8
      animcmd 1, 8
  .4byte 0 @ terminator?

.balign 4, 0
Animation_27A4: @ 0x085B13BC, index: 11
  .set ANIM_COUNT, 1
  .2byte ANIM_COUNT, 4 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 0, 0, 4
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 4
      animcmd 1, 4
      animcmd 2, 4
      animcmd 3, 4
  .4byte 0 @ terminator?

.balign 4, 0
Animation_29FB: @ 0x085B13D0, index: 12
  .set ANIM_COUNT, 4
  .2byte ANIM_COUNT, 34 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 80, 0, 4
    animation 32, 20, 5
    animation 32, 30, 1
    animation 32, 32, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 12, 12
      animcmd 13, 12
      animcmd 14, 12
      animcmd 13, 12
      animcmd 9, 12
      animcmd 10, 12
      animcmd 11, 12
      animcmd 10, 12
      animcmd 6, 12
      animcmd 7, 12
      animcmd 8, 12
      animcmd 7, 12
      animcmd 3, 12
      animcmd 4, 12
      animcmd 5, 12
      animcmd 4, 12
      animcmd 0, 12
      animcmd 1, 12
      animcmd 2, 12
      animcmd 1, 12
    @ cmd_idx 20
      animcmd 19, 8
      animcmd 20, 8
      animcmd 21, 8
      animcmd 22, 8
      animcmd 23, 8
      animcmd 24, 8
      animcmd 25, 8
      animcmd 26, 8
      animcmd 27, 8
      animcmd 28, 8
    @ cmd_idx 30
      animcmd 15, 1
      animcmd 16, 1
    @ cmd_idx 32
      animcmd 17, 1
      animcmd 18, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_31F4: @ 0x085B142C, index: 13
  .set ANIM_COUNT, 9
  .2byte ANIM_COUNT, 55 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 32, 0, 1
    animation 32, 2, 4
    animation 0, 10, 8
    animation 0, 18, 7
    animation 0, 25, 4
    animation 0, 29, 4
    animation 0, 33, 9
    animation 0, 42, 4
    animation 0, 46, 9
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 16, 15
      animcmd 17, 15
    @ cmd_idx 2
      animcmd 0, 8
      animcmd 1, 8
      animcmd 2, 8
      animcmd 3, 8
      animcmd 4, 8
      animcmd 5, 8
      animcmd 6, 8
      animcmd 7, 8
    @ cmd_idx 10
      animcmd 8, 4
      animcmd 9, 4
      animcmd 10, 4
      animcmd 11, 4
      animcmd 12, 4
      animcmd 13, 4
      animcmd 14, 4
      animcmd 15, 4
    @ cmd_idx 18
      animcmd 18, 6
      animcmd 19, 6
      animcmd 20, 6
      animcmd 21, 6
      animcmd 22, 6
      animcmd 23, 6
      animcmd 24, 6
    @ cmd_idx 25
      animcmd 25, 6
      animcmd 26, 6
      animcmd 27, 6
      animcmd 26, 6
    @ cmd_idx 29
      animcmd 28, 8
      animcmd 29, 8
      animcmd 30, 8
      animcmd 31, 8
    @ cmd_idx 33
      animcmd 32, 5
      animcmd 33, 5
      animcmd 34, 5
      animcmd 35, 5
      animcmd 36, 5
      animcmd 37, 5
      animcmd 38, 5
      animcmd 39, 5
      animcmd 40, 5
    @ cmd_idx 42
      animcmd 41, 4
      animcmd 42, 4
      animcmd 43, 4
      animcmd 44, 4
    @ cmd_idx 46
      animcmd 45, 6
      animcmd 46, 6
      animcmd 47, 6
      animcmd 48, 6
      animcmd 49, 6
      animcmd 50, 6
      animcmd 51, 6
      animcmd 52, 6
      animcmd 53, 6
  .4byte 0 @ terminator?

.balign 4, 0
Animation_3449: @ 0x085B14C8, index: 14
  .set ANIM_COUNT, 5
  .2byte ANIM_COUNT, 58 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 32, 0, 9
    animation 32, 18, 1
    animation 32, 20, 9
    animation 32, 38, 1
    animation 32, 40, 9
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 3
      animcmd 1, 6
      animcmd 2, 6
      animcmd 3, 6
      animcmd 5, 3
      animcmd 4, 3
      animcmd 5, 3
      animcmd 4, 3
      animcmd 5, 1
      animcmd 0, 3
      animcmd 9, 6
      animcmd 10, 6
      animcmd 11, 6
      animcmd 13, 3
      animcmd 12, 3
      animcmd 13, 3
      animcmd 12, 3
      animcmd 13, 1
    @ cmd_idx 18
      animcmd 5, 10
      animcmd 13, 10
    @ cmd_idx 20
      animcmd 5, 1
      animcmd 6, 8
      animcmd 7, 3
      animcmd 8, 3
      animcmd 7, 3
      animcmd 8, 3
      animcmd 7, 3
      animcmd 8, 3
      animcmd 7, 1
      animcmd 13, 1
      animcmd 14, 8
      animcmd 15, 3
      animcmd 16, 3
      animcmd 15, 3
      animcmd 16, 3
      animcmd 15, 3
      animcmd 16, 3
      animcmd 15, 1
    @ cmd_idx 38
      animcmd 7, 10
      animcmd 15, 10
    @ cmd_idx 40
      animcmd 7, 1
      animcmd 6, 8
      animcmd 5, 3
      animcmd 4, 3
      animcmd 5, 3
      animcmd 4, 3
      animcmd 5, 3
      animcmd 4, 3
      animcmd 5, 1
      animcmd 15, 1
      animcmd 14, 8
      animcmd 13, 3
      animcmd 12, 3
      animcmd 13, 3
      animcmd 12, 3
      animcmd 13, 3
      animcmd 12, 3
      animcmd 13, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_38E2: @ 0x085B1558, index: 15
  .set ANIM_COUNT, 13
  .2byte ANIM_COUNT, 79 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 0, 0, 7
    animation 0, 7, 7
    animation 0, 14, 4
    animation 0, 18, 6
    animation 32, 24, 3
    animation 32, 30, 4
    animation 32, 38, 4
    animation 32, 46, 3
    animation 32, 52, 3
    animation 0, 58, 7
    animation 0, 65, 5
    animation 0, 70, 6
    animation 0, 76, 3
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 16, 7
      animcmd 17, 7
      animcmd 18, 7
      animcmd 19, 7
      animcmd 20, 7
      animcmd 21, 7
      animcmd 22, 7
    @ cmd_idx 7
      animcmd 16, 7
      animcmd 17, 7
      animcmd 18, 7
      animcmd 23, 7
      animcmd 24, 7
      animcmd 25, 7
      animcmd 26, 7
    @ cmd_idx 14
      animcmd 27, 8
      animcmd 28, 8
      animcmd 29, 8
      animcmd 28, 8
    @ cmd_idx 18
      animcmd 32, 6
      animcmd 33, 6
      animcmd 34, 6
      animcmd 35, 6
      animcmd 36, 6
      animcmd 37, 6
    @ cmd_idx 24
      animcmd 38, 4
      animcmd 39, 4
      animcmd 40, 4
      animcmd 44, 4
      animcmd 45, 4
      animcmd 46, 4
    @ cmd_idx 30
      animcmd 38, 5
      animcmd 39, 5
      animcmd 42, 5
      animcmd 43, 5
      animcmd 44, 5
      animcmd 45, 5
      animcmd 48, 5
      animcmd 49, 5
    @ cmd_idx 38
      animcmd 38, 5
      animcmd 39, 5
      animcmd 42, 5
      animcmd 41, 5
      animcmd 44, 5
      animcmd 45, 5
      animcmd 48, 5
      animcmd 47, 5
    @ cmd_idx 46
      animcmd 51, 12
      animcmd 52, 12
      animcmd 53, 12
      animcmd 54, 12
      animcmd 55, 12
      animcmd 56, 12
    @ cmd_idx 52
      animcmd 65, 7
      animcmd 66, 7
      animcmd 67, 7
      animcmd 68, 7
      animcmd 69, 7
      animcmd 70, 7
    @ cmd_idx 58
      animcmd 71, 7
      animcmd 72, 7
      animcmd 73, 7
      animcmd 74, 7
      animcmd 75, 7
      animcmd 76, 7
      animcmd 77, 7
    @ cmd_idx 65
      animcmd 78, 7
      animcmd 79, 7
      animcmd 80, 7
      animcmd 81, 7
      animcmd 82, 7
    @ cmd_idx 70
      animcmd 83, 7
      animcmd 84, 7
      animcmd 85, 7
      animcmd 86, 7
      animcmd 87, 7
      animcmd 88, 7
    @ cmd_idx 76
      animcmd 89, 15
      animcmd 90, 15
      animcmd 91, 15
  .4byte 0 @ terminator?

.balign 4, 0
Animation_3D95: @ 0x085B1634, index: 16
  .set ANIM_COUNT, 33
  .2byte ANIM_COUNT, 116 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 80, 0, 1
    animation 80, 5, 1
    animation 80, 10, 1
    animation 80, 15, 1
    animation 80, 20, 1
    animation 80, 25, 1
    animation 80, 30, 1
    animation 80, 35, 1
    animation 16, 40, 3
    animation 16, 43, 3
    animation 16, 46, 3
    animation 16, 49, 3
    animation 16, 52, 3
    animation 16, 55, 3
    animation 16, 58, 3
    animation 16, 61, 3
    animation 16, 64, 3
    animation 16, 67, 3
    animation 16, 70, 3
    animation 16, 73, 3
    animation 16, 76, 3
    animation 16, 79, 3
    animation 16, 82, 3
    animation 16, 85, 3
    animation 16, 88, 1
    animation 16, 89, 1
    animation 16, 90, 1
    animation 16, 91, 1
    animation 16, 92, 1
    animation 16, 93, 1
    animation 16, 94, 1
    animation 16, 95, 1
    animation 80, 96, 4
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 8
      animcmd 1, 8
      animcmd 2, 8
      animcmd 3, 8
      animcmd 4, 8
    @ cmd_idx 5
      animcmd 7, 8
      animcmd 8, 8
      animcmd 9, 8
      animcmd 10, 8
      animcmd 11, 8
    @ cmd_idx 10
      animcmd 14, 8
      animcmd 15, 8
      animcmd 16, 8
      animcmd 17, 8
      animcmd 18, 8
    @ cmd_idx 15
      animcmd 21, 8
      animcmd 22, 8
      animcmd 23, 8
      animcmd 24, 8
      animcmd 25, 8
    @ cmd_idx 20
      animcmd 28, 8
      animcmd 29, 8
      animcmd 30, 8
      animcmd 31, 8
      animcmd 32, 8
    @ cmd_idx 25
      animcmd 35, 8
      animcmd 36, 8
      animcmd 37, 8
      animcmd 38, 8
      animcmd 39, 8
    @ cmd_idx 30
      animcmd 42, 8
      animcmd 43, 8
      animcmd 44, 8
      animcmd 45, 8
      animcmd 46, 8
    @ cmd_idx 35
      animcmd 49, 8
      animcmd 50, 8
      animcmd 51, 8
      animcmd 52, 8
      animcmd 53, 8
    @ cmd_idx 40
      animcmd 0, 1
      animcmd 5, 8
      animcmd 6, 1
    @ cmd_idx 43
      animcmd 7, 1
      animcmd 12, 8
      animcmd 13, 1
    @ cmd_idx 46
      animcmd 14, 1
      animcmd 19, 8
      animcmd 20, 1
    @ cmd_idx 49
      animcmd 21, 1
      animcmd 26, 8
      animcmd 27, 1
    @ cmd_idx 52
      animcmd 28, 1
      animcmd 33, 8
      animcmd 34, 1
    @ cmd_idx 55
      animcmd 35, 1
      animcmd 40, 8
      animcmd 41, 1
    @ cmd_idx 58
      animcmd 42, 1
      animcmd 47, 8
      animcmd 48, 1
    @ cmd_idx 61
      animcmd 49, 1
      animcmd 54, 8
      animcmd 55, 1
    @ cmd_idx 64
      animcmd 6, 1
      animcmd 5, 8
      animcmd 0, 1
    @ cmd_idx 67
      animcmd 13, 1
      animcmd 12, 8
      animcmd 7, 1
    @ cmd_idx 70
      animcmd 20, 1
      animcmd 19, 8
      animcmd 14, 1
    @ cmd_idx 73
      animcmd 27, 1
      animcmd 26, 8
      animcmd 21, 1
    @ cmd_idx 76
      animcmd 34, 1
      animcmd 33, 8
      animcmd 28, 1
    @ cmd_idx 79
      animcmd 41, 1
      animcmd 40, 8
      animcmd 35, 1
    @ cmd_idx 82
      animcmd 48, 1
      animcmd 47, 8
      animcmd 42, 1
    @ cmd_idx 85
      animcmd 55, 1
      animcmd 54, 8
      animcmd 49, 1
    @ cmd_idx 88
      animcmd 6, 8
    @ cmd_idx 89
      animcmd 13, 8
    @ cmd_idx 90
      animcmd 20, 8
    @ cmd_idx 91
      animcmd 27, 8
    @ cmd_idx 92
      animcmd 34, 8
    @ cmd_idx 93
      animcmd 41, 8
    @ cmd_idx 94
      animcmd 48, 8
    @ cmd_idx 95
      animcmd 55, 8
    @ cmd_idx 96
      animcmd 56, 8
      animcmd 35, 4
      animcmd 61, 8
      animcmd 35, 4
      animcmd 57, 8
      animcmd 36, 4
      animcmd 62, 8
      animcmd 36, 4
      animcmd 58, 8
      animcmd 37, 4
      animcmd 63, 8
      animcmd 37, 4
      animcmd 59, 8
      animcmd 38, 4
      animcmd 64, 8
      animcmd 38, 4
      animcmd 60, 8
      animcmd 39, 4
      animcmd 65, 8
      animcmd 39, 4
  .4byte 0 @ terminator?

.balign 4, 0
Animation_3DC2: @ 0x085B17A8, index: 17
  .set ANIM_COUNT, 2
  .2byte ANIM_COUNT, 5 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 4
    animation 16, 4, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 6
      animcmd 1, 8
      animcmd 2, 10
      animcmd 3, 10
    @ cmd_idx 4
      animcmd 4, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_3F72: @ 0x085B17C4, index: 18
  .set ANIM_COUNT, 3
  .2byte ANIM_COUNT, 6 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 1
    animation 16, 1, 1
    animation 64, 2, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 1
    @ cmd_idx 1
      animcmd 1, 1
    @ cmd_idx 2
      animcmd 2, 1
      animcmd 3, 1
      animcmd 4, 1
      animcmd 5, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_4EC0: @ 0x085B17E4, index: 19
  .set ANIM_COUNT, 4
  .2byte ANIM_COUNT, 38 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 32, 0, 9
    animation 32, 18, 7
    animation 16, 32, 3
    animation 16, 35, 3
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 12, 6
      animcmd 10, 6
      animcmd 11, 6
      animcmd 12, 6
      animcmd 10, 6
      animcmd 11, 6
      animcmd 12, 6
      animcmd 10, 6
      animcmd 11, 6
      animcmd 2, 6
      animcmd 0, 6
      animcmd 1, 6
      animcmd 2, 6
      animcmd 0, 6
      animcmd 1, 6
      animcmd 2, 6
      animcmd 0, 6
      animcmd 1, 6
    @ cmd_idx 18
      animcmd 13, 6
      animcmd 14, 6
      animcmd 15, 6
      animcmd 16, 6
      animcmd 17, 6
      animcmd 18, 6
      animcmd 19, 6
      animcmd 3, 6
      animcmd 4, 6
      animcmd 5, 6
      animcmd 6, 6
      animcmd 7, 6
      animcmd 8, 6
      animcmd 9, 6
    @ cmd_idx 32
      animcmd 20, 6
      animcmd 21, 6
      animcmd 22, 6
    @ cmd_idx 35
      animcmd 23, 6
      animcmd 24, 6
      animcmd 25, 6
  .4byte 0 @ terminator?

.balign 4, 0
Animation_5BB7: @ 0x085B1848, index: 20
  .set ANIM_COUNT, 6
  .2byte ANIM_COUNT, 20 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 32, 0, 4
    animation 32, 8, 1
    animation 16, 10, 2
    animation 16, 12, 2
    animation 16, 14, 3
    animation 16, 17, 3
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 3
      animcmd 1, 3
      animcmd 2, 2
      animcmd 3, 2
      animcmd 4, 3
      animcmd 5, 3
      animcmd 6, 2
      animcmd 7, 2
    @ cmd_idx 8
      animcmd 8, 10
      animcmd 9, 10
    @ cmd_idx 10
      animcmd 10, 5
      animcmd 11, 5
    @ cmd_idx 12
      animcmd 13, 5
      animcmd 14, 5
    @ cmd_idx 14
      animcmd 10, 4
      animcmd 11, 4
      animcmd 12, 4
    @ cmd_idx 17
      animcmd 13, 4
      animcmd 14, 4
      animcmd 15, 4
  .4byte 0 @ terminator?

.balign 4, 0
Animation_5C4D: @ 0x085B1890, index: 21
  .set ANIM_COUNT, 2
  .2byte ANIM_COUNT, 4 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 32, 0, 1
    animation 32, 2, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 15
      animcmd 1, 15
    @ cmd_idx 2
      animcmd 2, 15
      animcmd 3, 15
  .4byte 0 @ terminator?

.balign 4, 0
Animation_62C7: @ 0x085B18A8, index: 22
  .set ANIM_COUNT, 4
  .2byte ANIM_COUNT, 38 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 80, 0, 4
    animation 32, 20, 4
    animation 32, 28, 4
    animation 32, 36, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 2
      animcmd 1, 2
      animcmd 2, 2
      animcmd 1, 2
      animcmd 3, 2
      animcmd 4, 2
      animcmd 5, 2
      animcmd 4, 2
      animcmd 6, 2
      animcmd 7, 2
      animcmd 8, 2
      animcmd 7, 2
      animcmd 9, 2
      animcmd 10, 2
      animcmd 11, 2
      animcmd 10, 2
      animcmd 12, 2
      animcmd 13, 2
      animcmd 14, 2
      animcmd 13, 2
    @ cmd_idx 20
      animcmd 15, 2
      animcmd 16, 2
      animcmd 17, 2
      animcmd 16, 2
      animcmd 21, 2
      animcmd 22, 2
      animcmd 23, 2
      animcmd 22, 2
    @ cmd_idx 28
      animcmd 18, 2
      animcmd 19, 2
      animcmd 20, 2
      animcmd 19, 2
      animcmd 24, 2
      animcmd 25, 2
      animcmd 26, 2
      animcmd 25, 2
    @ cmd_idx 36
      animcmd 27, 1
      animcmd 28, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_6830: @ 0x085B190C, index: 23
  .set ANIM_COUNT, 4
  .2byte ANIM_COUNT, 12 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 3
    animation 16, 3, 3
    animation 16, 6, 3
    animation 16, 9, 3
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 2
      animcmd 3, 4
      animcmd 4, 3
    @ cmd_idx 3
      animcmd 1, 2
      animcmd 5, 4
      animcmd 6, 3
    @ cmd_idx 6
      animcmd 2, 2
      animcmd 5, 4
      animcmd 6, 3
    @ cmd_idx 9
      animcmd 7, 2
      animcmd 8, 4
      animcmd 9, 3
  .4byte 0 @ terminator?

.balign 4, 0
Animation_74C9: @ 0x085B193C, index: 24
  .set ANIM_COUNT, 2
  .2byte ANIM_COUNT, 4 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 1
    animation 48, 1, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 3, 1
    @ cmd_idx 1
      animcmd 0, 1
      animcmd 1, 1
      animcmd 2, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_78E1: @ 0x085B1954, index: 25
  .set ANIM_COUNT, 5
  .2byte ANIM_COUNT, 28 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 0, 0, 4
    animation 0, 4, 6
    animation 0, 10, 6
    animation 0, 16, 8
    animation 0, 24, 4
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 4
      animcmd 1, 4
      animcmd 2, 4
      animcmd 3, 4
    @ cmd_idx 4
      animcmd 15, 2
      animcmd 14, 2
      animcmd 13, 2
      animcmd 12, 2
      animcmd 11, 2
      animcmd 10, 2
    @ cmd_idx 10
      animcmd 10, 6
      animcmd 11, 6
      animcmd 12, 6
      animcmd 13, 6
      animcmd 14, 6
      animcmd 15, 6
    @ cmd_idx 16
      animcmd 16, 4
      animcmd 21, 4
      animcmd 18, 4
      animcmd 19, 4
      animcmd 17, 4
      animcmd 20, 4
      animcmd 18, 4
      animcmd 21, 4
    @ cmd_idx 24
      animcmd 22, 4
      animcmd 23, 4
      animcmd 24, 4
      animcmd 25, 4
  .4byte 0 @ terminator?

.balign 4, 0
Animation_7B03: @ 0x085B19A8, index: 26
  .set ANIM_COUNT, 8
  .2byte ANIM_COUNT, 73 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 32, 0, 6
    animation 32, 12, 6
    animation 80, 24, 1
    animation 32, 29, 1
    animation 32, 31, 1
    animation 32, 33, 13
    animation 32, 59, 6
    animation 32, 71, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 1
      animcmd 1, 7
      animcmd 0, 5
      animcmd 2, 3
      animcmd 3, 3
      animcmd 2, 1
      animcmd 4, 1
      animcmd 5, 7
      animcmd 4, 5
      animcmd 6, 3
      animcmd 7, 3
      animcmd 6, 1
    @ cmd_idx 12
      animcmd 8, 1
      animcmd 9, 10
      animcmd 8, 7
      animcmd 10, 4
      animcmd 11, 4
      animcmd 10, 1
      animcmd 12, 1
      animcmd 13, 10
      animcmd 12, 7
      animcmd 14, 4
      animcmd 15, 4
      animcmd 14, 1
    @ cmd_idx 24
      animcmd 16, 1
      animcmd 17, 1
      animcmd 18, 1
      animcmd 19, 1
      animcmd 20, 1
    @ cmd_idx 29
      animcmd 21, 1
      animcmd 22, 1
    @ cmd_idx 31
      animcmd 23, 1
      animcmd 28, 1
    @ cmd_idx 33
      animcmd 24, 8
      animcmd 26, 6
      animcmd 25, 6
      animcmd 26, 2
      animcmd 27, 6
      animcmd 26, 1
      animcmd 25, 4
      animcmd 26, 2
      animcmd 27, 6
      animcmd 26, 1
      animcmd 25, 4
      animcmd 26, 2
      animcmd 24, 8
      animcmd 29, 8
      animcmd 31, 6
      animcmd 30, 6
      animcmd 31, 2
      animcmd 32, 6
      animcmd 31, 1
      animcmd 30, 4
      animcmd 31, 2
      animcmd 32, 6
      animcmd 31, 1
      animcmd 30, 4
      animcmd 31, 2
      animcmd 29, 8
    @ cmd_idx 59
      animcmd 33, 10
      animcmd 34, 8
      animcmd 35, 5
      animcmd 34, 8
      animcmd 35, 5
      animcmd 33, 6
      animcmd 36, 10
      animcmd 37, 8
      animcmd 38, 5
      animcmd 37, 8
      animcmd 38, 5
      animcmd 36, 6
    @ cmd_idx 71
      animcmd 24, 8
      animcmd 29, 8
  .4byte 0 @ terminator?

.balign 4, 0
Animation_871C: @ 0x085B1A64, index: 27
  .set ANIM_COUNT, 3
  .2byte ANIM_COUNT, 12 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 4
    animation 16, 4, 4
    animation 16, 8, 4
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 8, 2
      animcmd 9, 8
      animcmd 10, 8
      animcmd 11, 8
    @ cmd_idx 4
      animcmd 0, 4
      animcmd 1, 4
      animcmd 2, 4
      animcmd 3, 4
    @ cmd_idx 8
      animcmd 4, 4
      animcmd 5, 4
      animcmd 6, 4
      animcmd 7, 4
  .4byte 0 @ terminator?

.balign 4, 0
Animation_87EF: @ 0x085B1A90, index: 28
  .set ANIM_COUNT, 3
  .2byte ANIM_COUNT, 12 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 32, 0, 1
    animation 16, 2, 5
    animation 16, 7, 5
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 1
      animcmd 1, 1
    @ cmd_idx 2
      animcmd 0, 1
      animcmd 2, 10
      animcmd 3, 10
      animcmd 4, 10
      animcmd 1, 1
    @ cmd_idx 7
      animcmd 1, 1
      animcmd 4, 10
      animcmd 3, 10
      animcmd 2, 10
      animcmd 0, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_8DC7: @ 0x085B1ABC, index: 29
  .set ANIM_COUNT, 2
  .2byte ANIM_COUNT, 2 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 1
    animation 16, 1, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 1
    @ cmd_idx 1
      animcmd 1, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_931E: @ 0x085B1AD0, index: 30
  .set ANIM_COUNT, 5
  .2byte ANIM_COUNT, 25 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 6
    animation 16, 6, 6
    animation 16, 12, 5
    animation 16, 17, 5
    animation 16, 22, 3
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 2
      animcmd 1, 6
      animcmd 2, 6
      animcmd 3, 6
      animcmd 4, 6
      animcmd 5, 6
    @ cmd_idx 6
      animcmd 14, 2
      animcmd 15, 6
      animcmd 16, 6
      animcmd 17, 6
      animcmd 18, 6
      animcmd 19, 6
    @ cmd_idx 12
      animcmd 6, 5
      animcmd 7, 5
      animcmd 8, 5
      animcmd 9, 5
      animcmd 10, 5
    @ cmd_idx 17
      animcmd 6, 3
      animcmd 7, 3
      animcmd 8, 3
      animcmd 9, 3
      animcmd 10, 3
    @ cmd_idx 22
      animcmd 11, 3
      animcmd 12, 3
      animcmd 13, 3
  .4byte 0 @ terminator?

.balign 4, 0
Animation_95D9: @ 0x085B1B20, index: 31
  .set ANIM_COUNT, 1
  .2byte ANIM_COUNT, 24 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 32, 0, 12
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 3
      animcmd 2, 3
      animcmd 0, 3
      animcmd 2, 3
      animcmd 0, 3
      animcmd 2, 3
      animcmd 0, 3
      animcmd 1, 6
      animcmd 2, 6
      animcmd 3, 6
      animcmd 4, 6
      animcmd 3, 4
      animcmd 5, 3
      animcmd 7, 3
      animcmd 5, 3
      animcmd 7, 3
      animcmd 5, 3
      animcmd 7, 3
      animcmd 5, 3
      animcmd 6, 6
      animcmd 7, 6
      animcmd 8, 6
      animcmd 9, 6
      animcmd 8, 3
  .4byte 0 @ terminator?

.balign 4, 0
Animation_9607: @ 0x085B1B5C, index: 32
  .set ANIM_COUNT, 7
  .2byte ANIM_COUNT, 42 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 80, 0, 6
    animation 16, 30, 4
    animation 16, 34, 1
    animation 16, 35, 1
    animation 16, 36, 1
    animation 16, 37, 1
    animation 16, 38, 4
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 4
      animcmd 1, 4
      animcmd 2, 4
      animcmd 3, 4
      animcmd 4, 4
      animcmd 5, 4
      animcmd 6, 4
      animcmd 7, 4
      animcmd 8, 4
      animcmd 9, 4
      animcmd 10, 4
      animcmd 11, 4
      animcmd 12, 4
      animcmd 13, 4
      animcmd 14, 4
      animcmd 15, 4
      animcmd 16, 4
      animcmd 17, 4
      animcmd 18, 4
      animcmd 19, 4
      animcmd 20, 4
      animcmd 21, 4
      animcmd 22, 4
      animcmd 23, 4
      animcmd 24, 4
      animcmd 25, 4
      animcmd 26, 4
      animcmd 27, 4
      animcmd 28, 4
      animcmd 29, 4
    @ cmd_idx 30
      animcmd 30, 6
      animcmd 31, 6
      animcmd 32, 6
      animcmd 33, 6
    @ cmd_idx 34
      animcmd 34, 1
    @ cmd_idx 35
      animcmd 35, 1
    @ cmd_idx 36
      animcmd 36, 1
    @ cmd_idx 37
      animcmd 37, 1
    @ cmd_idx 38
      animcmd 38, 8
      animcmd 39, 8
      animcmd 40, 8
      animcmd 41, 8
  .4byte 0 @ terminator?

.balign 4, 0
Animation_99DD: @ 0x085B1BD4, index: 33
  .set ANIM_COUNT, 11
  .2byte ANIM_COUNT, 46 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 7
    animation 16, 7, 3
    animation 16, 10, 3
    animation 32, 13, 4
    animation 32, 21, 3
    animation 16, 27, 5
    animation 16, 32, 2
    animation 16, 34, 1
    animation 32, 35, 1
    animation 32, 37, 4
    animation 16, 45, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 10
      animcmd 1, 10
      animcmd 2, 10
      animcmd 3, 10
      animcmd 4, 10
      animcmd 5, 10
      animcmd 6, 10
    @ cmd_idx 7
      animcmd 7, 6
      animcmd 8, 6
      animcmd 9, 6
    @ cmd_idx 10
      animcmd 10, 6
      animcmd 11, 5
      animcmd 12, 4
    @ cmd_idx 13
      animcmd 14, 10
      animcmd 15, 10
      animcmd 16, 10
      animcmd 17, 10
      animcmd 21, 10
      animcmd 22, 10
      animcmd 23, 10
      animcmd 24, 10
    @ cmd_idx 21
      animcmd 18, 6
      animcmd 19, 6
      animcmd 20, 6
      animcmd 25, 6
      animcmd 26, 6
      animcmd 27, 6
    @ cmd_idx 27
      animcmd 28, 8
      animcmd 29, 6
      animcmd 30, 6
      animcmd 31, 6
      animcmd 32, 6
    @ cmd_idx 32
      animcmd 33, 4
      animcmd 34, 4
    @ cmd_idx 34
      animcmd 13, 2
    @ cmd_idx 35
      animcmd 36, 1
      animcmd 35, 1
    @ cmd_idx 37
      animcmd 16, 2
      animcmd 18, 6
      animcmd 19, 6
      animcmd 20, 6
      animcmd 23, 2
      animcmd 25, 6
      animcmd 26, 6
      animcmd 27, 6
    @ cmd_idx 45
      animcmd 37, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_9AF2: @ 0x085B1C64, index: 34
  .set ANIM_COUNT, 7
  .2byte ANIM_COUNT, 19 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 1
    animation 16, 1, 3
    animation 16, 4, 3
    animation 16, 7, 3
    animation 16, 10, 5
    animation 16, 15, 3
    animation 16, 18, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 1
    @ cmd_idx 1
      animcmd 0, 1
      animcmd 4, 8
      animcmd 5, 8
    @ cmd_idx 4
      animcmd 6, 8
      animcmd 7, 8
      animcmd 0, 8
    @ cmd_idx 7
      animcmd 5, 8
      animcmd 4, 8
      animcmd 0, 1
    @ cmd_idx 10
      animcmd 3, 15
      animcmd 3, 5
      animcmd 1, 6
      animcmd 4, 8
      animcmd 6, 1
    @ cmd_idx 15
      animcmd 0, 1
      animcmd 1, 8
      animcmd 2, 1
    @ cmd_idx 18
      animcmd 2, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_A4B2: @ 0x085B1CB0, index: 35
  .set ANIM_COUNT, 9
  .2byte ANIM_COUNT, 69 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 32, 0, 1
    animation 32, 2, 8
    animation 48, 18, 3
    animation 32, 27, 3
    animation 32, 33, 4
    animation 32, 41, 1
    animation 32, 43, 7
    animation 32, 57, 3
    animation 32, 63, 3
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 1
      animcmd 1, 1
    @ cmd_idx 2
      animcmd 2, 12
      animcmd 3, 12
      animcmd 4, 12
      animcmd 5, 12
      animcmd 6, 12
      animcmd 7, 12
      animcmd 8, 12
      animcmd 9, 12
      animcmd 10, 12
      animcmd 11, 12
      animcmd 12, 12
      animcmd 13, 12
      animcmd 14, 12
      animcmd 15, 12
      animcmd 16, 12
      animcmd 17, 12
    @ cmd_idx 18
      animcmd 18, 8
      animcmd 19, 8
      animcmd 18, 8, xflip=1
      animcmd 20, 8
      animcmd 21, 8
      animcmd 22, 8
      animcmd 23, 8
      animcmd 24, 8
      animcmd 23, 8, xflip=1
    @ cmd_idx 27
      animcmd 25, 2
      animcmd 26, 4
      animcmd 27, 4
      animcmd 31, 2
      animcmd 32, 4
      animcmd 33, 4
    @ cmd_idx 33
      animcmd 25, 2
      animcmd 28, 6
      animcmd 29, 6
      animcmd 30, 10
      animcmd 31, 2
      animcmd 34, 6
      animcmd 35, 6
      animcmd 36, 10
    @ cmd_idx 41
      animcmd 30, 1
      animcmd 36, 1
    @ cmd_idx 43
      animcmd 37, 4
      animcmd 38, 15
      animcmd 38, 1
      animcmd 39, 8
      animcmd 40, 8
      animcmd 38, 4
      animcmd 37, 4
      animcmd 41, 4
      animcmd 42, 15
      animcmd 42, 1
      animcmd 43, 8
      animcmd 44, 8
      animcmd 42, 4
      animcmd 41, 4
    @ cmd_idx 57
      animcmd 30, 6
      animcmd 29, 6
      animcmd 28, 10
      animcmd 36, 6
      animcmd 35, 6
      animcmd 34, 10
    @ cmd_idx 63
      animcmd 28, 6
      animcmd 29, 6
      animcmd 30, 2
      animcmd 34, 6
      animcmd 35, 6
      animcmd 36, 2
  .4byte 0 @ terminator?

.balign 4, 0
Animation_A929: @ 0x085B1D68, index: 36
  .set ANIM_COUNT, 10
  .2byte ANIM_COUNT, 52 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 3
    animation 32, 3, 8
    animation 16, 19, 8
    animation 16, 27, 6
    animation 16, 33, 6
    animation 16, 39, 1
    animation 16, 40, 1
    animation 48, 41, 1
    animation 16, 44, 1
    animation 16, 45, 7
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 10
      animcmd 1, 10
      animcmd 2, 15
    @ cmd_idx 3
      animcmd 3, 5
      animcmd 2, 5
      animcmd 4, 3
      animcmd 2, 3
      animcmd 3, 5
      animcmd 2, 5
      animcmd 4, 3
      animcmd 2, 3
      animcmd 3, 3
      animcmd 2, 3
      animcmd 4, 5
      animcmd 2, 5
      animcmd 3, 3
      animcmd 2, 3
      animcmd 4, 5
      animcmd 2, 5
    @ cmd_idx 19
      animcmd 2, 15
      animcmd 5, 5
      animcmd 6, 5
      animcmd 7, 15
      animcmd 7, 15
      animcmd 7, 15
      animcmd 7, 15
      animcmd 7, 10
    @ cmd_idx 27
      animcmd 8, 7
      animcmd 9, 7
      animcmd 10, 10
      animcmd 11, 13
      animcmd 10, 7
      animcmd 9, 7
    @ cmd_idx 33
      animcmd 15, 6
      animcmd 12, 6
      animcmd 13, 5
      animcmd 5, 4
      animcmd 14, 4
      animcmd 2, 1
    @ cmd_idx 39
      animcmd 12, 1
    @ cmd_idx 40
      animcmd 16, 1
    @ cmd_idx 41
      animcmd 17, 1
      animcmd 18, 1
      animcmd 19, 1
    @ cmd_idx 44
      animcmd 9, 1
    @ cmd_idx 45
      animcmd 8, 7
      animcmd 9, 7
      animcmd 10, 10
      animcmd 11, 13
      animcmd 10, 7
      animcmd 9, 7
      animcmd 2, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_AF44: @ 0x085B1E00, index: 37
  .set ANIM_COUNT, 4
  .2byte ANIM_COUNT, 26 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 80, 0, 1
    animation 80, 5, 3
    animation 32, 20, 1
    animation 32, 22, 2
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 15, 8
      animcmd 16, 8
      animcmd 17, 8
      animcmd 18, 8
      animcmd 19, 8
    @ cmd_idx 5
      animcmd 0, 3
      animcmd 1, 3
      animcmd 2, 3
      animcmd 3, 3
      animcmd 4, 3
      animcmd 5, 3
      animcmd 6, 3
      animcmd 7, 3
      animcmd 8, 3
      animcmd 9, 3
      animcmd 10, 3
      animcmd 11, 3
      animcmd 12, 3
      animcmd 13, 3
      animcmd 14, 3
    @ cmd_idx 20
      animcmd 20, 8
      animcmd 21, 8
    @ cmd_idx 22
      animcmd 3, 6
      animcmd 16, 1
      animcmd 9, 6
      animcmd 18, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_B6EE: @ 0x085B1E4C, index: 38
  .set ANIM_COUNT, 6
  .2byte ANIM_COUNT, 36 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 32, 0, 1
    animation 32, 2, 4
    animation 32, 10, 4
    animation 32, 18, 4
    animation 32, 26, 2
    animation 32, 30, 3
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 1
      animcmd 2, 1
    @ cmd_idx 2
      animcmd 0, 8
      animcmd 1, 8
      animcmd 0, 8
      animcmd 1, 8
      animcmd 2, 7
      animcmd 3, 7
      animcmd 2, 7
      animcmd 3, 7
    @ cmd_idx 10
      animcmd 0, 1
      animcmd 4, 15
      animcmd 4, 1
      animcmd 9, 8
      animcmd 2, 1
      animcmd 5, 15
      animcmd 5, 1
      animcmd 13, 8
    @ cmd_idx 18
      animcmd 8, 10
      animcmd 9, 10
      animcmd 10, 10
      animcmd 11, 10
      animcmd 12, 10
      animcmd 13, 10
      animcmd 14, 10
      animcmd 15, 10
    @ cmd_idx 26
      animcmd 0, 1
      animcmd 6, 2
      animcmd 2, 1
      animcmd 7, 2
    @ cmd_idx 30
      animcmd 0, 1
      animcmd 2, 6
      animcmd 2, 1, xflip=1
      animcmd 2, 1
      animcmd 0, 6
      animcmd 2, 1, xflip=1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_B952: @ 0x085B1EB4, index: 39
  .set ANIM_COUNT, 3
  .2byte ANIM_COUNT, 4 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 1
    animation 16, 1, 2
    animation 16, 3, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 1
    @ cmd_idx 1
      animcmd 1, 5
      animcmd 2, 5
    @ cmd_idx 3
      animcmd 3, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_C102: @ 0x085B1ED0, index: 40
  .set ANIM_COUNT, 16
  .2byte ANIM_COUNT, 122 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 80, 0, 4
    animation 80, 20, 1
    animation 80, 25, 4
    animation 80, 45, 1
    animation 80, 50, 1
    animation 80, 55, 1
    animation 48, 60, 1
    animation 16, 63, 1
    animation 80, 64, 1
    animation 80, 69, 1
    animation 80, 74, 1
    animation 80, 79, 1
    animation 80, 84, 1
    animation 80, 89, 3
    animation 80, 104, 3
    animation 16, 119, 3
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 13, 6
      animcmd 12, 6
      animcmd 13, 6
      animcmd 14, 6
      animcmd 10, 6
      animcmd 9, 6
      animcmd 10, 6
      animcmd 11, 6
      animcmd 7, 6
      animcmd 6, 6
      animcmd 7, 6
      animcmd 8, 6
      animcmd 4, 6
      animcmd 3, 6
      animcmd 4, 6
      animcmd 5, 6
      animcmd 1, 6
      animcmd 0, 6
      animcmd 1, 6
      animcmd 2, 6
    @ cmd_idx 20
      animcmd 24, 1
      animcmd 25, 1, xflip=1
      animcmd 26, 1, xflip=1
      animcmd 27, 1, xflip=1
      animcmd 28, 1
    @ cmd_idx 25
      animcmd 16, 6
      animcmd 15, 6
      animcmd 16, 6
      animcmd 17, 6
      animcmd 19, 6, xflip=1
      animcmd 18, 6, xflip=1
      animcmd 19, 6, xflip=1
      animcmd 20, 6, xflip=1
      animcmd 22, 6
      animcmd 21, 6
      animcmd 22, 6
      animcmd 23, 6
      animcmd 19, 6
      animcmd 18, 6
      animcmd 19, 6
      animcmd 20, 6
      animcmd 16, 6
      animcmd 15, 6
      animcmd 16, 6
      animcmd 17, 6
    @ cmd_idx 45
      animcmd 13, 1
      animcmd 10, 1
      animcmd 7, 1
      animcmd 4, 1
      animcmd 1, 1
    @ cmd_idx 50
      animcmd 16, 1, yflip=1
      animcmd 19, 1, yflip=1
      animcmd 22, 1
      animcmd 19, 1
      animcmd 16, 1
    @ cmd_idx 55
      animcmd 48, 1
      animcmd 47, 1
      animcmd 46, 1
      animcmd 45, 1
      animcmd 44, 1
    @ cmd_idx 60
      animcmd 30, 1
      animcmd 33, 1
      animcmd 36, 1
    @ cmd_idx 63
      animcmd 39, 1
    @ cmd_idx 64
      animcmd 53, 1
      animcmd 52, 1
      animcmd 51, 1
      animcmd 50, 1
      animcmd 49, 1
    @ cmd_idx 69
      animcmd 41, 1
      animcmd 42, 1, xflip=1
      animcmd 43, 1
      animcmd 42, 1
      animcmd 41, 1
    @ cmd_idx 74
      animcmd 63, 1
      animcmd 62, 1
      animcmd 61, 1
      animcmd 60, 1
      animcmd 59, 1
    @ cmd_idx 79
      animcmd 58, 1
      animcmd 57, 1
      animcmd 56, 1
      animcmd 55, 1
      animcmd 54, 1
    @ cmd_idx 84
      animcmd 68, 1
      animcmd 67, 1
      animcmd 66, 1
      animcmd 65, 1
      animcmd 64, 1
    @ cmd_idx 89
      animcmd 93, 3
      animcmd 94, 3
      animcmd 95, 3
      animcmd 90, 3
      animcmd 91, 3
      animcmd 92, 3
      animcmd 87, 3
      animcmd 88, 3
      animcmd 89, 3
      animcmd 84, 3
      animcmd 85, 3
      animcmd 86, 3
      animcmd 81, 3
      animcmd 82, 3
      animcmd 83, 3
    @ cmd_idx 104
      animcmd 69, 3
      animcmd 70, 3
      animcmd 71, 3
      animcmd 72, 3, xflip=1
      animcmd 73, 3, xflip=1
      animcmd 74, 3, xflip=1
      animcmd 75, 3
      animcmd 76, 3
      animcmd 77, 3
      animcmd 72, 3
      animcmd 73, 3
      animcmd 74, 3
      animcmd 69, 3
      animcmd 70, 3
      animcmd 71, 3
    @ cmd_idx 119
      animcmd 78, 3
      animcmd 79, 3
      animcmd 80, 3
  .4byte 0 @ terminator?

.balign 4, 0
Animation_C160: @ 0x085B200C, index: 41
  .set ANIM_COUNT, 2
  .2byte ANIM_COUNT, 4 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 0, 0, 1
    animation 0, 1, 3
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 1
    @ cmd_idx 1
      animcmd 1, 3
      animcmd 2, 3
      animcmd 3, 3
  .4byte 0 @ terminator?

.balign 4, 0
Animation_C6A0: @ 0x085B2024, index: 42
  .set ANIM_COUNT, 21
  .2byte ANIM_COUNT, 83 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 80, 0, 4
    animation 16, 20, 4
    animation 16, 24, 4
    animation 16, 28, 4
    animation 16, 32, 4
    animation 16, 36, 4
    animation 16, 40, 8
    animation 16, 48, 4
    animation 16, 52, 4
    animation 16, 56, 4
    animation 16, 60, 4
    animation 16, 64, 2
    animation 16, 66, 1
    animation 16, 67, 1
    animation 32, 68, 1
    animation 32, 70, 1
    animation 32, 72, 2
    animation 32, 76, 1
    animation 16, 78, 2
    animation 16, 80, 1
    animation 32, 81, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 10
      animcmd 1, 10
      animcmd 2, 10
      animcmd 1, 10
      animcmd 3, 10
      animcmd 4, 10
      animcmd 5, 10
      animcmd 4, 10
      animcmd 6, 10
      animcmd 7, 10
      animcmd 8, 10
      animcmd 7, 10
      animcmd 9, 10
      animcmd 10, 10
      animcmd 11, 10
      animcmd 10, 10
      animcmd 12, 10
      animcmd 13, 10
      animcmd 14, 10
      animcmd 13, 10
    @ cmd_idx 20
      animcmd 15, 6
      animcmd 16, 6
      animcmd 17, 6
      animcmd 18, 6
    @ cmd_idx 24
      animcmd 19, 10
      animcmd 20, 10
      animcmd 21, 10
      animcmd 20, 10
    @ cmd_idx 28
      animcmd 22, 10
      animcmd 23, 10
      animcmd 24, 10
      animcmd 23, 10
    @ cmd_idx 32
      animcmd 25, 10
      animcmd 26, 10
      animcmd 27, 10
      animcmd 26, 10
    @ cmd_idx 36
      animcmd 28, 10
      animcmd 29, 10
      animcmd 30, 10
      animcmd 29, 10
    @ cmd_idx 40
      animcmd 31, 10
      animcmd 31, 10
      animcmd 32, 10
      animcmd 32, 10
      animcmd 33, 10
      animcmd 33, 10
      animcmd 32, 10
      animcmd 32, 10
    @ cmd_idx 48
      animcmd 34, 10
      animcmd 34, 10
      animcmd 34, 10
      animcmd 34, 10
    @ cmd_idx 52
      animcmd 35, 10
      animcmd 35, 10
      animcmd 35, 10
      animcmd 35, 10
    @ cmd_idx 56
      animcmd 36, 10
      animcmd 36, 10
      animcmd 36, 10
      animcmd 36, 10
    @ cmd_idx 60
      animcmd 18, 6
      animcmd 17, 6
      animcmd 16, 6
      animcmd 15, 6
    @ cmd_idx 64
      animcmd 37, 6
      animcmd 38, 1
    @ cmd_idx 66
      animcmd 39, 1
    @ cmd_idx 67
      animcmd 40, 1
    @ cmd_idx 68
      animcmd 41, 1
      animcmd 46, 1
    @ cmd_idx 70
      animcmd 42, 1
      animcmd 47, 1
    @ cmd_idx 72
      animcmd 43, 4
      animcmd 44, 4
      animcmd 48, 4
      animcmd 49, 4
    @ cmd_idx 76
      animcmd 45, 6
      animcmd 50, 6
    @ cmd_idx 78
      animcmd 38, 1
      animcmd 37, 6
    @ cmd_idx 80
      animcmd 38, 1
    @ cmd_idx 81
      animcmd 43, 1
      animcmd 48, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_D1B8: @ 0x085B2128, index: 43
  .set ANIM_COUNT, 18
  .2byte ANIM_COUNT, 54 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 6
    animation 16, 6, 1
    animation 16, 7, 1
    animation 16, 8, 8
    animation 16, 16, 3
    animation 16, 19, 3
    animation 16, 22, 3
    animation 16, 25, 1
    animation 16, 26, 1
    animation 16, 27, 2
    animation 16, 29, 2
    animation 16, 31, 2
    animation 16, 33, 3
    animation 16, 36, 3
    animation 16, 39, 3
    animation 16, 42, 4
    animation 16, 46, 4
    animation 16, 50, 4
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 6, 6
      animcmd 7, 4
      animcmd 7, 15
      animcmd 7, 15
      animcmd 8, 4
      animcmd 9, 4
    @ cmd_idx 6
      animcmd 10, 1
    @ cmd_idx 7
      animcmd 11, 1
    @ cmd_idx 8
      animcmd 12, 4
      animcmd 13, 4
      animcmd 14, 4
      animcmd 15, 4
      animcmd 16, 4
      animcmd 17, 4
      animcmd 18, 6
      animcmd 19, 6
    @ cmd_idx 16
      animcmd 20, 3
      animcmd 21, 1
      animcmd 22, 2
    @ cmd_idx 19
      animcmd 24, 3
      animcmd 25, 1
      animcmd 26, 2
    @ cmd_idx 22
      animcmd 28, 3
      animcmd 29, 1
      animcmd 30, 2
    @ cmd_idx 25
      animcmd 32, 1
    @ cmd_idx 26
      animcmd 33, 1
    @ cmd_idx 27
      animcmd 23, 4
      animcmd 21, 2
    @ cmd_idx 29
      animcmd 27, 4
      animcmd 25, 2
    @ cmd_idx 31
      animcmd 31, 4
      animcmd 29, 2
    @ cmd_idx 33
      animcmd 3, 5
      animcmd 4, 5
      animcmd 5, 5
    @ cmd_idx 36
      animcmd 0, 4
      animcmd 1, 4
      animcmd 2, 6
    @ cmd_idx 39
      animcmd 36, 4
      animcmd 37, 4
      animcmd 38, 6
    @ cmd_idx 42
      animcmd 39, 6
      animcmd 40, 6
      animcmd 41, 6
      animcmd 42, 6
    @ cmd_idx 46
      animcmd 43, 6
      animcmd 44, 6
      animcmd 45, 6
      animcmd 46, 6
    @ cmd_idx 50
      animcmd 47, 6
      animcmd 48, 6
      animcmd 49, 6
      animcmd 50, 6
  .4byte 0 @ terminator?

.balign 4, 0
Animation_D41F: @ 0x085B21E4, index: 44
  .set ANIM_COUNT, 9
  .2byte ANIM_COUNT, 15 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 0, 0, 1
    animation 0, 1, 3
    animation 0, 4, 2
    animation 0, 6, 2
    animation 0, 8, 1
    animation 0, 9, 1
    animation 0, 10, 1
    animation 0, 11, 1
    animation 0, 12, 3
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 1
    @ cmd_idx 1
      animcmd 1, 1
      animcmd 2, 1
      animcmd 3, 1
    @ cmd_idx 4
      animcmd 4, 4
      animcmd 5, 2
    @ cmd_idx 6
      animcmd 6, 4
      animcmd 7, 2
    @ cmd_idx 8
      animcmd 8, 1
    @ cmd_idx 9
      animcmd 9, 1
    @ cmd_idx 10
      animcmd 10, 1
    @ cmd_idx 11
      animcmd 11, 1
    @ cmd_idx 12
      animcmd 12, 3
      animcmd 13, 3
      animcmd 14, 3
  .4byte 0 @ terminator?

.balign 4, 0
Animation_D6C8: @ 0x085B2230, index: 45
  .set ANIM_COUNT, 4
  .2byte ANIM_COUNT, 33 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 80, 0, 2
    animation 80, 10, 3
    animation 80, 25, 1
    animation 16, 30, 3
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 20, 3
      animcmd 21, 3
      animcmd 22, 3
      animcmd 23, 3
      animcmd 24, 3
      animcmd 25, 3
      animcmd 26, 3
      animcmd 27, 3
      animcmd 28, 3
      animcmd 29, 3
    @ cmd_idx 10
      animcmd 0, 1
      animcmd 1, 1
      animcmd 2, 1
      animcmd 3, 1
      animcmd 4, 1
      animcmd 5, 1
      animcmd 6, 1
      animcmd 7, 1
      animcmd 8, 1
      animcmd 9, 1
      animcmd 10, 1
      animcmd 11, 1
      animcmd 12, 1
      animcmd 13, 1
      animcmd 14, 1
    @ cmd_idx 25
      animcmd 15, 1
      animcmd 16, 1
      animcmd 17, 1
      animcmd 18, 1
      animcmd 19, 1
    @ cmd_idx 30
      animcmd 30, 5
      animcmd 31, 4
      animcmd 32, 4
  .4byte 0 @ terminator?

.balign 4, 0
Animation_DA5E: @ 0x085B228C, index: 46
  .set ANIM_COUNT, 21
  .2byte ANIM_COUNT, 202 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 32, 0, 1
    animation 48, 2, 4
    animation 32, 14, 10
    animation 32, 34, 2
    animation 32, 38, 2
    animation 32, 42, 3
    animation 32, 48, 2
    animation 32, 52, 11
    animation 32, 74, 4
    animation 32, 82, 4
    animation 32, 90, 2
    animation 32, 94, 2
    animation 16, 98, 10
    animation 16, 108, 10
    animation 16, 118, 10
    animation 16, 128, 10
    animation 16, 138, 10
    animation 16, 148, 10
    animation 16, 158, 10
    animation 16, 168, 10
    animation 96, 178, 4
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 40, 2
      animcmd 41, 2
    @ cmd_idx 2
      animcmd 42, 8, xflip=1
      animcmd 43, 14
      animcmd 43, 2
      animcmd 42, 8
      animcmd 44, 8
      animcmd 45, 14
      animcmd 45, 2
      animcmd 46, 8
      animcmd 47, 8
      animcmd 48, 14
      animcmd 48, 2
      animcmd 47, 8, xflip=1
    @ cmd_idx 14
      animcmd 0, 9
      animcmd 1, 15
      animcmd 1, 3
      animcmd 2, 8
      animcmd 3, 5
      animcmd 4, 9
      animcmd 5, 15
      animcmd 5, 3
      animcmd 6, 8
      animcmd 7, 5
      animcmd 8, 9
      animcmd 9, 15
      animcmd 9, 3
      animcmd 10, 8
      animcmd 11, 5
      animcmd 12, 9
      animcmd 13, 15
      animcmd 13, 3
      animcmd 14, 8
      animcmd 15, 5
    @ cmd_idx 34
      animcmd 16, 2
      animcmd 17, 6
      animcmd 24, 2
      animcmd 25, 6
    @ cmd_idx 38
      animcmd 16, 2
      animcmd 17, 4
      animcmd 24, 2
      animcmd 25, 4
    @ cmd_idx 42
      animcmd 17, 4
      animcmd 18, 6
      animcmd 19, 2
      animcmd 25, 4
      animcmd 26, 6
      animcmd 27, 2
    @ cmd_idx 48
      animcmd 18, 8
      animcmd 17, 6
      animcmd 26, 8
      animcmd 25, 6
    @ cmd_idx 52
      animcmd 17, 4
      animcmd 18, 6
      animcmd 20, 4
      animcmd 19, 4
      animcmd 20, 15
      animcmd 20, 15
      animcmd 20, 2
      animcmd 21, 8
      animcmd 22, 8
      animcmd 23, 15
      animcmd 23, 9
      animcmd 25, 4
      animcmd 26, 6
      animcmd 28, 4
      animcmd 27, 4
      animcmd 28, 15
      animcmd 28, 15
      animcmd 28, 2
      animcmd 29, 8
      animcmd 30, 8
      animcmd 31, 15
      animcmd 31, 9
    @ cmd_idx 74
      animcmd 32, 8
      animcmd 33, 6
      animcmd 34, 4
      animcmd 35, 5
      animcmd 36, 8
      animcmd 37, 6
      animcmd 38, 4
      animcmd 39, 5
    @ cmd_idx 82
      animcmd 32, 3
      animcmd 33, 3
      animcmd 34, 3
      animcmd 35, 3
      animcmd 36, 3
      animcmd 37, 3
      animcmd 38, 3
      animcmd 39, 3
    @ cmd_idx 90
      animcmd 40, 2
      animcmd 49, 6
      animcmd 41, 2
      animcmd 51, 6
    @ cmd_idx 94
      animcmd 49, 6
      animcmd 50, 6
      animcmd 51, 6
      animcmd 52, 6
    @ cmd_idx 98
      animcmd 60, 2
      animcmd 71, 3
      animcmd 54, 3
      animcmd 55, 4
      animcmd 54, 3
      animcmd 53, 2
      animcmd 56, 4
      animcmd 53, 4
      animcmd 54, 5
      animcmd 53, 2
    @ cmd_idx 108
      animcmd 53, 2
      animcmd 61, 3
      animcmd 66, 3
      animcmd 67, 4
      animcmd 66, 3
      animcmd 60, 2
      animcmd 61, 4
      animcmd 60, 4
      animcmd 66, 5
      animcmd 60, 2
    @ cmd_idx 118
      animcmd 60, 2
      animcmd 71, 3
      animcmd 69, 3
      animcmd 70, 4
      animcmd 69, 3
      animcmd 68, 2
      animcmd 71, 4
      animcmd 68, 4
      animcmd 69, 5
      animcmd 68, 2
    @ cmd_idx 128
      animcmd 68, 2
      animcmd 66, 3
      animcmd 61, 3
      animcmd 62, 4
      animcmd 61, 3
      animcmd 60, 2
      animcmd 66, 4
      animcmd 60, 4
      animcmd 61, 5
      animcmd 60, 2
    @ cmd_idx 138
      animcmd 82, 2
      animcmd 78, 3
      animcmd 76, 3
      animcmd 77, 4
      animcmd 76, 3
      animcmd 75, 2
      animcmd 78, 4
      animcmd 75, 4
      animcmd 76, 5
      animcmd 75, 2
    @ cmd_idx 148
      animcmd 75, 2
      animcmd 83, 3
      animcmd 88, 3
      animcmd 89, 4
      animcmd 88, 3
      animcmd 82, 2
      animcmd 83, 4
      animcmd 82, 4
      animcmd 88, 5
      animcmd 82, 2
    @ cmd_idx 158
      animcmd 82, 2
      animcmd 93, 3
      animcmd 91, 3
      animcmd 92, 4
      animcmd 91, 3
      animcmd 90, 2
      animcmd 93, 4
      animcmd 90, 4
      animcmd 91, 5
      animcmd 90, 2
    @ cmd_idx 168
      animcmd 90, 2
      animcmd 88, 3
      animcmd 83, 3
      animcmd 84, 4
      animcmd 83, 3
      animcmd 82, 2
      animcmd 88, 4
      animcmd 82, 4
      animcmd 83, 5
      animcmd 82, 2
    @ cmd_idx 178
      animcmd 53, 3
      animcmd 57, 3
      animcmd 58, 3
      animcmd 59, 3
      animcmd 60, 3
      animcmd 63, 3
      animcmd 64, 3
      animcmd 65, 3
      animcmd 68, 3
      animcmd 72, 3
      animcmd 73, 3
      animcmd 74, 3
      animcmd 75, 3
      animcmd 79, 3
      animcmd 80, 3
      animcmd 81, 3
      animcmd 82, 3
      animcmd 85, 3
      animcmd 86, 3
      animcmd 87, 3
      animcmd 90, 3
      animcmd 94, 3
      animcmd 95, 3
      animcmd 96, 3
  .4byte 0 @ terminator?

.balign 4, 0
Animation_DCEB: @ 0x085B247C, index: 47
  .set ANIM_COUNT, 9
  .2byte ANIM_COUNT, 36 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 7
    animation 16, 7, 3
    animation 16, 10, 3
    animation 32, 13, 4
    animation 32, 21, 3
    animation 16, 27, 5
    animation 16, 32, 2
    animation 16, 34, 1
    animation 16, 35, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 10
      animcmd 1, 10
      animcmd 2, 10
      animcmd 3, 10
      animcmd 4, 10
      animcmd 5, 10
      animcmd 6, 10
    @ cmd_idx 7
      animcmd 7, 6
      animcmd 8, 6
      animcmd 9, 6
    @ cmd_idx 10
      animcmd 10, 6
      animcmd 11, 5
      animcmd 12, 4
    @ cmd_idx 13
      animcmd 14, 10
      animcmd 15, 10
      animcmd 16, 10
      animcmd 17, 10
      animcmd 21, 10
      animcmd 22, 10
      animcmd 23, 10
      animcmd 24, 10
    @ cmd_idx 21
      animcmd 18, 6
      animcmd 19, 6
      animcmd 20, 6
      animcmd 25, 6
      animcmd 26, 6
      animcmd 27, 6
    @ cmd_idx 27
      animcmd 28, 8
      animcmd 29, 6
      animcmd 30, 6
      animcmd 31, 6
      animcmd 32, 6
    @ cmd_idx 32
      animcmd 33, 4
      animcmd 34, 4
    @ cmd_idx 34
      animcmd 13, 2
    @ cmd_idx 35
      animcmd 35, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_E677: @ 0x085B24F0, index: 48
  .set ANIM_COUNT, 3
  .2byte ANIM_COUNT, 3 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 16, 0, 1
    animation 16, 1, 1
    animation 16, 2, 1
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 1
    @ cmd_idx 1
      animcmd 1, 1
    @ cmd_idx 2
      animcmd 2, 1
  .4byte 0 @ terminator?

.balign 4, 0
Animation_F62B: @ 0x085B250C, index: 49
  .set ANIM_COUNT, 3
  .2byte ANIM_COUNT, 26 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 0, 0, 9
    animation 0, 9, 11
    animation 0, 20, 6
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 0, 5
      animcmd 1, 5
      animcmd 2, 5
      animcmd 3, 5
      animcmd 4, 5
      animcmd 5, 5
      animcmd 6, 5
      animcmd 7, 5
      animcmd 8, 5
    @ cmd_idx 9
      animcmd 9, 4
      animcmd 10, 4
      animcmd 14, 4
      animcmd 11, 4
      animcmd 12, 4
      animcmd 10, 4
      animcmd 13, 4
      animcmd 11, 4
      animcmd 14, 4
      animcmd 10, 4
      animcmd 9, 4
    @ cmd_idx 20
      animcmd 9, 3
      animcmd 11, 2
      animcmd 14, 3
      animcmd 11, 2
      animcmd 10, 3
      animcmd 9, 3
  .4byte 0 @ terminator?

.balign 4, 0
Animation_F6E7: @ 0x085B2554, index: 50
  .set ANIM_COUNT, 14
  .2byte ANIM_COUNT, 168 @ animation_count, cmd_count
  @ Animations, variant_count, cmd_idx, cmd_count
    animation 32, 0, 1
    animation 32, 2, 27
    animation 32, 56, 10
    animation 32, 76, 8
    animation 32, 92, 8
    animation 32, 108, 2
    animation 32, 112, 2
    animation 32, 116, 4
    animation 32, 124, 7
    animation 32, 138, 1
    animation 32, 140, 3
    animation 32, 146, 1
    animation 32, 148, 6
    animation 64, 160, 2
  @ animcmd spriteidx, duration
    @ cmd_idx 0
      animcmd 8, 1
      animcmd 0, 1
    @ cmd_idx 2
      animcmd 9, 10
      animcmd 10, 8
      animcmd 11, 8
      animcmd 10, 8
      animcmd 11, 8
      animcmd 10, 8
      animcmd 11, 8
      animcmd 12, 8
      animcmd 13, 8
      animcmd 12, 8
      animcmd 13, 8
      animcmd 12, 8
      animcmd 13, 8
      animcmd 10, 10
      animcmd 14, 8
      animcmd 15, 8
      animcmd 14, 8
      animcmd 15, 8
      animcmd 14, 8
      animcmd 15, 8
      animcmd 10, 8
      animcmd 11, 8
      animcmd 10, 8
      animcmd 11, 8
      animcmd 10, 8
      animcmd 11, 8
      animcmd 9, 10
      animcmd 1, 10
      animcmd 2, 8
      animcmd 3, 8
      animcmd 2, 8
      animcmd 3, 8
      animcmd 2, 8
      animcmd 3, 8
      animcmd 4, 8
      animcmd 5, 8
      animcmd 4, 8
      animcmd 5, 8
      animcmd 4, 8
      animcmd 5, 8
      animcmd 2, 10
      animcmd 6, 8
      animcmd 7, 8
      animcmd 6, 8
      animcmd 7, 8
      animcmd 6, 8
      animcmd 7, 8
      animcmd 2, 8
      animcmd 3, 8
      animcmd 2, 8
      animcmd 3, 8
      animcmd 2, 8
      animcmd 3, 8
      animcmd 1, 10
    @ cmd_idx 56
      animcmd 19, 15
      animcmd 19, 15
      animcmd 20, 8
      animcmd 21, 8
      animcmd 20, 8
      animcmd 21, 8
      animcmd 20, 8
      animcmd 21, 8
      animcmd 20, 8
      animcmd 21, 8
      animcmd 16, 15
      animcmd 16, 15
      animcmd 17, 8
      animcmd 18, 8
      animcmd 17, 8
      animcmd 18, 8
      animcmd 17, 8
      animcmd 18, 8
      animcmd 17, 8
      animcmd 18, 8
    @ cmd_idx 76
      animcmd 30, 8
      animcmd 31, 8
      animcmd 32, 8
      animcmd 33, 8
      animcmd 34, 8
      animcmd 35, 8
      animcmd 36, 8
      animcmd 37, 8
      animcmd 22, 8
      animcmd 23, 8
      animcmd 24, 8
      animcmd 25, 8
      animcmd 26, 8
      animcmd 27, 8
      animcmd 28, 8
      animcmd 29, 8
    @ cmd_idx 92
      animcmd 56, 5
      animcmd 57, 5
      animcmd 58, 5
      animcmd 59, 5
      animcmd 60, 5
      animcmd 61, 5
      animcmd 62, 5
      animcmd 63, 5
      animcmd 48, 5
      animcmd 49, 5
      animcmd 50, 5
      animcmd 51, 5
      animcmd 52, 5
      animcmd 53, 5
      animcmd 54, 5
      animcmd 55, 5
    @ cmd_idx 108
      animcmd 19, 8
      animcmd 41, 15
      animcmd 16, 8
      animcmd 38, 15
    @ cmd_idx 112
      animcmd 42, 4
      animcmd 43, 4
      animcmd 39, 4
      animcmd 40, 4
    @ cmd_idx 116
      animcmd 19, 4
      animcmd 41, 15
      animcmd 41, 5
      animcmd 19, 8
      animcmd 16, 4
      animcmd 38, 15
      animcmd 38, 5
      animcmd 16, 4
    @ cmd_idx 124
      animcmd 46, 6
      animcmd 47, 6
      animcmd 46, 6
      animcmd 47, 6
      animcmd 46, 6
      animcmd 47, 6
      animcmd 19, 12
      animcmd 44, 6
      animcmd 45, 6
      animcmd 44, 6
      animcmd 45, 6
      animcmd 44, 6
      animcmd 45, 6
      animcmd 16, 12
    @ cmd_idx 138
      animcmd 67, 1
      animcmd 64, 1
    @ cmd_idx 140
      animcmd 69, 4
      animcmd 68, 1
      animcmd 68, 2
      animcmd 66, 4
      animcmd 65, 1
      animcmd 65, 2
    @ cmd_idx 146
      animcmd 69, 8
      animcmd 66, 8
    @ cmd_idx 148
      animcmd 67, 2
      animcmd 69, 6
      animcmd 68, 15
      animcmd 68, 3
      animcmd 72, 14
      animcmd 73, 2
      animcmd 64, 2
      animcmd 66, 6
      animcmd 65, 15
      animcmd 65, 3
      animcmd 70, 14
      animcmd 71, 2
    @ cmd_idx 160
      animcmd 74, 12
      animcmd 75, 12
      animcmd 76, 12
      animcmd 77, 12
      animcmd 78, 12
      animcmd 79, 12
      animcmd 80, 12
      animcmd 81, 12
  .4byte 0 @ terminator?

